/*
 * SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
 * SPDX-License-Identifier: Apache-2.0
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

//! Doc-gate: every counter and histogram declared through the instrumentation
//! framework (`#[derive(Event)]`) must have a row in the checked-in metrics
//! catalogue, `docs/observability/core_metrics.md`.
//!
//! The catalogue is regenerated by the `test_integration` metrics test, which
//! scrapes `/metrics`. That leaves a gap the CI repo-clean check cannot see: a
//! metric no test exercises is never scraped, so it can land with no catalogue
//! row and nothing complains. This check closes it from the source side --
//! it reads the `#[event(...)]` declarations directly, so a metric is caught
//! whether or not any test drives it at runtime.
//!
//! The scan parses each source file with `syn` and walks its item tree, so the
//! metric name is read as a proper Rust string literal (raw strings included),
//! `#[cfg(test)]` fixtures are excluded by their attribute or an enclosing
//! module's, and `#[event(...)]` in a doc-comment example is never seen (a doc
//! comment is not an item). It fails closed: a counter/histogram whose name
//! cannot be read, or an event-bearing file that cannot be parsed, is an error,
//! never a silent skip.
//!
//! `name_unchecked` events are exempt: their exposed `/metrics` name is a
//! sanitized/suffixed transform of the declared name (dotted OpenTelemetry
//! names, the doubled `_total_total`), not the verbatim string, so a source
//! match is not meaningful. Cataloguing those precisely wants the events
//! registry from #3221; until then they stay documented by scrape-and-retain.

use std::path::{Path, PathBuf};

use eyre::{Context, bail};
use proc_macro2::{TokenStream, TokenTree};
use syn::{Attribute, Item, ItemStruct, Meta};
use walkdir::WalkDir;

static REPO_ROOT: &str = concat!(env!("CARGO_MANIFEST_DIR"), "/../.."); // crates/xtask/../..
const CATALOGUE: &str = "docs/observability/core_metrics.md";

/// A counter or histogram declared by a `#[derive(Event)]` `#[event(...)]`
/// site, keyed by its verbatim exposed name.
struct DeclaredMetric {
    name: String,
    kind: &'static str,
    describe: Option<String>,
    source: PathBuf,
}

pub fn check() -> eyre::Result<()> {
    let repo_root = PathBuf::from(REPO_ROOT).canonicalize()?;
    let catalogue = std::fs::read_to_string(repo_root.join(CATALOGUE))
        .with_context(|| format!("reading {CATALOGUE}"))?;

    let mut declared = Vec::new();
    for dir in ["crates", "rest-api"] {
        collect(&repo_root.join(dir), &repo_root, &mut declared)?;
    }

    let missing: Vec<&DeclaredMetric> = declared
        .iter()
        .filter(|m| !catalogue.contains(&format!("<td>{}</td>", m.name)))
        .collect();

    if missing.is_empty() {
        println!(
            "OK: all {} framework counters/histograms are documented in {CATALOGUE}.",
            declared.len(),
        );
        return Ok(());
    }

    eprintln!(
        "{} framework metric(s) are declared with #[derive(Event)] but missing from \
         {CATALOGUE}:\n",
        missing.len(),
    );
    for m in &missing {
        eprintln!("  {} ({}) -- {}", m.name, m.kind, m.source.display());
        eprintln!("      {}", suggested_row(m));
    }
    eprintln!(
        "\nEvery counter/histogram declared through the instrumentation framework needs a row \
         in {CATALOGUE}, so the metric is documented even when no test scrapes it. Add the \
         row(s) above, in name-sorted position, with the Description column set to the event's \
         `describe` text. (name_unchecked events are exempt -- their exposed name is a \
         sanitized transform; see #3221.)"
    );
    std::process::exit(1);
}

fn collect(dir: &Path, repo_root: &Path, out: &mut Vec<DeclaredMetric>) -> eyre::Result<()> {
    for entry in WalkDir::new(dir)
        .into_iter()
        .filter_map(Result::ok)
        .filter(|e| e.file_type().is_file())
    {
        let path = entry.path();
        if path.extension().and_then(|e| e.to_str()) != Some("rs") {
            continue;
        }
        let rel = path.strip_prefix(repo_root).unwrap_or(path);
        if skip_path(rel) {
            continue;
        }
        let src =
            std::fs::read_to_string(path).with_context(|| format!("reading {}", path.display()))?;
        // Only files that declare an event are worth parsing; but once a file
        // does, a parse failure is loud -- never a silent skip of a metric.
        if !src.contains("#[event(") {
            continue;
        }
        let file = syn::parse_file(&src).with_context(|| {
            format!(
                "{} declares #[event(...)] but the metric-docs gate could not parse it",
                rel.display()
            )
        })?;
        collect_items(&file.items, false, rel, out)?;
    }
    Ok(())
}

/// Walks the module item tree, carrying whether an enclosing module is
/// `#[cfg(test)]`. Production events are module-level structs, so fn bodies and
/// impl blocks (where test fixtures live) are deliberately not descended into.
fn collect_items(
    items: &[Item],
    in_test: bool,
    source: &Path,
    out: &mut Vec<DeclaredMetric>,
) -> eyre::Result<()> {
    for item in items {
        match item {
            Item::Mod(module) => {
                let module_in_test = in_test || has_cfg_test(&module.attrs);
                if let Some((_, sub_items)) = &module.content {
                    collect_items(sub_items, module_in_test, source, out)?;
                }
            }
            Item::Struct(item_struct) => {
                if in_test || has_cfg_test(&item_struct.attrs) || !derives_event(&item_struct.attrs)
                {
                    continue;
                }
                if let Some(metric) = event_metric(item_struct, source)? {
                    out.push(metric);
                }
            }
            _ => {}
        }
    }
    Ok(())
}

/// Reads the `#[event(...)]` of a `#[derive(Event)]` struct. `Ok(None)` when it
/// declares no counter/histogram (metric = none) or is `name_unchecked`;
/// errors (fails closed) when a counter/histogram's name cannot be read.
fn event_metric(item: &ItemStruct, source: &Path) -> eyre::Result<Option<DeclaredMetric>> {
    let Some(attr) = item.attrs.iter().find(|a| a.path().is_ident("event")) else {
        // `#[derive(Event)]` with no `#[event(...)]`; the derive itself rejects
        // this, so it is not the gate's job to report.
        return Ok(None);
    };

    let mut name = None;
    let mut metric = None;
    let mut describe = None;
    let mut name_unchecked = false;
    attr.parse_nested_meta(|meta| {
        if meta.path.is_ident("name") {
            name = Some(meta.value()?.parse::<syn::LitStr>()?.value());
        } else if meta.path.is_ident("metric") {
            metric = Some(meta.value()?.parse::<syn::Ident>()?.to_string());
        } else if meta.path.is_ident("describe") {
            describe = Some(meta.value()?.parse::<syn::LitStr>()?.value());
        } else if meta.path.is_ident("name_unchecked") {
            name_unchecked = true;
        } else if meta.path.is_ident("describe_unchecked") {
            // A flag with no value, and no bearing on documentation.
        } else if meta.path.is_ident("component")
            || meta.path.is_ident("message")
            || meta.path.is_ident("unit")
        {
            // String-valued keys the gate ignores; consumed to keep parsing.
            let _: syn::LitStr = meta.value()?.parse()?;
        } else if meta.path.is_ident("log") {
            let _: syn::Ident = meta.value()?.parse()?;
        } else {
            // An event key the derive defines but this gate has not been taught:
            // fail closed so the two stay in sync.
            return Err(meta.error("metric-docs gate: unrecognized `event` key"));
        }
        Ok(())
    })
    .with_context(|| format!("parsing #[event(...)] in {}", source.display()))?;

    let kind = match metric.as_deref() {
        Some("counter") => "counter",
        Some("histogram") => "histogram",
        // metric = none, or no metric side: nothing to catalogue.
        _ => return Ok(None),
    };
    if name_unchecked {
        return Ok(None);
    }
    let Some(name) = name else {
        bail!(
            "{}: an #[event(...)] with metric = {kind} has no readable name; the metric-docs \
             gate will not skip it silently",
            source.display(),
        );
    };
    Ok(Some(DeclaredMetric {
        name,
        kind,
        describe,
        source: source.to_path_buf(),
    }))
}

/// The instrumentation crate's own `#[event]` sites are doc examples and test
/// fixtures; xtask (this crate) only mentions `#[event(` in scanner strings;
/// `tests`/`benches` trees and `tests.rs` modules are never production metrics.
fn skip_path(rel: &Path) -> bool {
    let path = rel.to_string_lossy();
    if path.starts_with("crates/instrument/")
        || path.starts_with("crates/instrument-macros/")
        || path.starts_with("crates/xtask/")
    {
        return true;
    }
    if matches!(
        rel.file_stem().and_then(|s| s.to_str()),
        Some("tests" | "test")
    ) {
        return true;
    }
    rel.components().any(|c| {
        matches!(
            c.as_os_str().to_str(),
            Some("tests") | Some("benches") | Some("target")
        )
    })
}

/// Whether `#[derive(...)]` names `Event` (bare or path-qualified, e.g.
/// `carbide_instrument::Event`).
fn derives_event(attrs: &[Attribute]) -> bool {
    attrs.iter().any(|attr| {
        attr.path().is_ident("derive")
            && matches!(&attr.meta, Meta::List(list) if tokens_have_ident(list.tokens.clone(), "Event"))
    })
}

/// Whether an attribute list carries `#[cfg(test)]` (also inside `all(...)` /
/// `any(...)`), ignoring a `not(test)` subtree.
fn has_cfg_test(attrs: &[Attribute]) -> bool {
    attrs.iter().any(|attr| {
        attr.path().is_ident("cfg")
            && matches!(&attr.meta, Meta::List(list) if predicate_mentions_test(list.tokens.clone()))
    })
}

/// A `test` predicate is active in a `cfg(...)` token stream: recurse into
/// `all(...)`/`any(...)` groups, but skip a `not(...)` subtree (its `test`
/// would negate to non-test).
fn predicate_mentions_test(tokens: TokenStream) -> bool {
    let mut iter = tokens.into_iter().peekable();
    while let Some(tt) = iter.next() {
        match tt {
            TokenTree::Ident(ident) if ident == "not" => {
                // Drop the argument group of `not(...)`.
                if matches!(iter.peek(), Some(TokenTree::Group(_))) {
                    iter.next();
                }
            }
            TokenTree::Ident(ident) if ident == "test" => return true,
            TokenTree::Group(group) if predicate_mentions_test(group.stream()) => return true,
            _ => {}
        }
    }
    false
}

/// Whether a token stream contains the identifier `wanted` at any nesting.
fn tokens_have_ident(tokens: TokenStream, wanted: &str) -> bool {
    tokens.into_iter().any(|tt| match tt {
        TokenTree::Ident(ident) => ident == wanted,
        TokenTree::Group(group) => tokens_have_ident(group.stream(), wanted),
        _ => false,
    })
}

/// The `<tr>` row a developer should add to the catalogue for a missing metric.
fn suggested_row(m: &DeclaredMetric) -> String {
    format!(
        "<tr><td>{}</td><td>{}</td><td>{}</td></tr>",
        m.name,
        m.kind,
        html_escape(m.describe.as_deref().unwrap_or("")),
    )
}

/// HTML entity escaping matching the catalogue generator (`askama_escape::Html`).
fn html_escape(s: &str) -> String {
    let mut out = String::with_capacity(s.len());
    for c in s.chars() {
        match c {
            '&' => out.push_str("&amp;"),
            '<' => out.push_str("&lt;"),
            '>' => out.push_str("&gt;"),
            '"' => out.push_str("&quot;"),
            '\'' => out.push_str("&#39;"),
            _ => out.push(c),
        }
    }
    out
}

#[cfg(test)]
mod tests {
    use std::path::Path;

    use super::{DeclaredMetric, collect_items};

    /// Collect the counter/histogram metrics the gate would require from a
    /// snippet of source (the same item walk the real scan uses).
    fn declared(src: &str) -> Vec<DeclaredMetric> {
        let file = syn::parse_file(src).expect("snippet parses");
        let mut out = Vec::new();
        collect_items(&file.items, false, Path::new("snippet.rs"), &mut out)
            .expect("no fail-closed error");
        out
    }

    /// A raw-string metric name (which the derive accepts) is read, not
    /// silently skipped -- the codex P2 hole.
    #[test]
    fn raw_string_name_is_collected() {
        let metrics = declared(
            r##"
            #[derive(Event)]
            #[event(name = r"carbide_raw_total", component = "c", log = off, metric = counter,
                    describe = "Number of raw things")]
            struct RawNamed;

            #[derive(Event)]
            #[event(name = r#"carbide_hashed_total"#, component = "c", log = off, metric = counter,
                    describe = "Number of hashed things")]
            struct HashNamed;
            "##,
        );
        let names: Vec<&str> = metrics.iter().map(|m| m.name.as_str()).collect();
        assert!(
            names.contains(&"carbide_raw_total"),
            "raw string name r\"...\" must be read, got {names:?}"
        );
        assert!(
            names.contains(&"carbide_hashed_total"),
            "raw string name r#\"...\"# must be read, got {names:?}"
        );
    }

    /// A cooked string name still round-trips (escapes handled by LitStr).
    #[test]
    fn cooked_string_name_is_collected() {
        let metrics = declared(
            r#"
            #[derive(Event)]
            #[event(name = "carbide_cooked_total", component = "c", log = off, metric = counter,
                    describe = "Number of cooked things")]
            struct Cooked;
            "#,
        );
        assert_eq!(metrics.len(), 1);
        assert_eq!(metrics[0].name, "carbide_cooked_total");
    }

    /// Events under `#[cfg(test)]` -- on the struct or an enclosing module --
    /// are excluded, so unit-test fixtures do not demand catalogue rows.
    #[test]
    fn cfg_test_events_are_excluded() {
        let metrics = declared(
            r#"
            #[derive(Event)]
            #[event(name = "carbide_prod_total", component = "c", log = off, metric = counter,
                    describe = "Number of prod things")]
            struct Prod;

            #[cfg(test)]
            mod tests {
                #[derive(Event)]
                #[event(name = "carbide_modfixture_total", component = "c", log = off,
                        metric = counter, describe = "Number of fixtures")]
                struct ModFixture;
            }

            #[cfg(test)]
            #[derive(Event)]
            #[event(name = "carbide_structfixture_total", component = "c", log = off,
                    metric = counter, describe = "Number of fixtures")]
            struct StructFixture;
            "#,
        );
        let names: Vec<&str> = metrics.iter().map(|m| m.name.as_str()).collect();
        assert_eq!(
            names,
            vec!["carbide_prod_total"],
            "only the non-test event should be collected, got {names:?}"
        );
    }

    /// `metric = none` and `name_unchecked` events are not catalogue rows.
    #[test]
    fn non_metric_and_grandfathered_are_skipped() {
        let metrics = declared(
            r#"
            #[derive(Event)]
            #[event(name = "carbide_logonly", component = "c", metric = none, message = "hi")]
            struct LogOnly;

            #[derive(Event)]
            #[event(name = "carbide_legacy_total_total", name_unchecked, component = "c",
                    log = off, metric = counter, describe = "Total number", describe_unchecked)]
            struct Legacy;
            "#,
        );
        let names: Vec<&str> = metrics.iter().map(|m| m.name.as_str()).collect();
        assert!(names.is_empty(), "got {names:?}");
    }
}
