// SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
// SPDX-License-Identifier: Apache-2.0

/*
NVIDIA Infra Controller REST API

NVIDIA Infra Controller REST API allows users to create and manage resources, e.g., VPCs, Subnets, and Instances, across all connected NVIDIA Infra Controller datacenters, also referred to as Sites.

API version: 2.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package standard

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the TenantAccountSiteCapability type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &TenantAccountSiteCapability{}

// TenantAccountSiteCapability struct for TenantAccountSiteCapability
type TenantAccountSiteCapability struct {
	Scope TenantAccountSiteCapabilityScope `json:"scope"`
	// Required when scope is limited; must be omitted or empty when scope is global
	SiteIds []string `json:"siteIds,omitempty"`
	// Whether TargetedInstanceCreation is enabled for the scope
	TargetedInstanceCreation bool `json:"targetedInstanceCreation"`
}

type _TenantAccountSiteCapability TenantAccountSiteCapability

// NewTenantAccountSiteCapability instantiates a new TenantAccountSiteCapability object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTenantAccountSiteCapability(scope TenantAccountSiteCapabilityScope, targetedInstanceCreation bool) *TenantAccountSiteCapability {
	this := TenantAccountSiteCapability{}
	this.Scope = scope
	this.TargetedInstanceCreation = targetedInstanceCreation
	return &this
}

// NewTenantAccountSiteCapabilityWithDefaults instantiates a new TenantAccountSiteCapability object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTenantAccountSiteCapabilityWithDefaults() *TenantAccountSiteCapability {
	this := TenantAccountSiteCapability{}
	return &this
}

// GetScope returns the Scope field value
func (o *TenantAccountSiteCapability) GetScope() TenantAccountSiteCapabilityScope {
	if o == nil {
		var ret TenantAccountSiteCapabilityScope
		return ret
	}

	return o.Scope
}

// GetScopeOk returns a tuple with the Scope field value
// and a boolean to check if the value has been set.
func (o *TenantAccountSiteCapability) GetScopeOk() (*TenantAccountSiteCapabilityScope, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Scope, true
}

// SetScope sets field value
func (o *TenantAccountSiteCapability) SetScope(v TenantAccountSiteCapabilityScope) {
	o.Scope = v
}

// GetSiteIds returns the SiteIds field value if set, zero value otherwise.
func (o *TenantAccountSiteCapability) GetSiteIds() []string {
	if o == nil || IsNil(o.SiteIds) {
		var ret []string
		return ret
	}
	return o.SiteIds
}

// GetSiteIdsOk returns a tuple with the SiteIds field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TenantAccountSiteCapability) GetSiteIdsOk() ([]string, bool) {
	if o == nil || IsNil(o.SiteIds) {
		return nil, false
	}
	return o.SiteIds, true
}

// HasSiteIds returns a boolean if a field has been set.
func (o *TenantAccountSiteCapability) HasSiteIds() bool {
	if o != nil && !IsNil(o.SiteIds) {
		return true
	}

	return false
}

// SetSiteIds gets a reference to the given []string and assigns it to the SiteIds field.
func (o *TenantAccountSiteCapability) SetSiteIds(v []string) {
	o.SiteIds = v
}

// GetTargetedInstanceCreation returns the TargetedInstanceCreation field value
func (o *TenantAccountSiteCapability) GetTargetedInstanceCreation() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.TargetedInstanceCreation
}

// GetTargetedInstanceCreationOk returns a tuple with the TargetedInstanceCreation field value
// and a boolean to check if the value has been set.
func (o *TenantAccountSiteCapability) GetTargetedInstanceCreationOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TargetedInstanceCreation, true
}

// SetTargetedInstanceCreation sets field value
func (o *TenantAccountSiteCapability) SetTargetedInstanceCreation(v bool) {
	o.TargetedInstanceCreation = v
}

func (o TenantAccountSiteCapability) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o TenantAccountSiteCapability) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["scope"] = o.Scope
	if !IsNil(o.SiteIds) {
		toSerialize["siteIds"] = o.SiteIds
	}
	toSerialize["targetedInstanceCreation"] = o.TargetedInstanceCreation
	return toSerialize, nil
}

func (o *TenantAccountSiteCapability) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"scope",
		"targetedInstanceCreation",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if value, exists := allProperties[requiredProperty]; !exists || value == nil {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varTenantAccountSiteCapability := _TenantAccountSiteCapability{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varTenantAccountSiteCapability)

	if err != nil {
		return err
	}

	*o = TenantAccountSiteCapability(varTenantAccountSiteCapability)

	return err
}

type NullableTenantAccountSiteCapability struct {
	value *TenantAccountSiteCapability
	isSet bool
}

func (v NullableTenantAccountSiteCapability) Get() *TenantAccountSiteCapability {
	return v.value
}

func (v *NullableTenantAccountSiteCapability) Set(val *TenantAccountSiteCapability) {
	v.value = val
	v.isSet = true
}

func (v NullableTenantAccountSiteCapability) IsSet() bool {
	return v.isSet
}

func (v *NullableTenantAccountSiteCapability) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTenantAccountSiteCapability(val *TenantAccountSiteCapability) *NullableTenantAccountSiteCapability {
	return &NullableTenantAccountSiteCapability{value: val, isSet: true}
}

func (v NullableTenantAccountSiteCapability) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTenantAccountSiteCapability) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
