// SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
// SPDX-License-Identifier: Apache-2.0

/*
NVIDIA Infra Controller REST API

NVIDIA Infra Controller REST API allows users to create and manage resources, e.g., VPCs, Subnets, and Instances, across all connected NVIDIA Infra Controller datacenters, also referred to as Sites.

API version: 2.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package standard

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the DpuReprovisionRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DpuReprovisionRequest{}

// DpuReprovisionRequest Request to trigger DPU reprovisioning for a Machine
type DpuReprovisionRequest struct {
	// Use `Set` to start reprovisioning, `Clear` to remove a pending request, or `Restart` to restart DPUs that already have a request. Restart accepts a host Machine ID only.
	Mode string `json:"mode"`
	// Deprecated compatibility field. Firmware is always verified and updated during reprovisioning.
	// Deprecated
	UpdateFirmware *bool `json:"updateFirmware,omitempty"`
	// Acknowledges that an Instance is currently attached to the Machine and this action may disrupt Tenant workload on the Instance.
	AcknowledgeAttachedInstance *bool `json:"acknowledgeAttachedInstance,omitempty"`
}

type _DpuReprovisionRequest DpuReprovisionRequest

// NewDpuReprovisionRequest instantiates a new DpuReprovisionRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDpuReprovisionRequest(mode string) *DpuReprovisionRequest {
	this := DpuReprovisionRequest{}
	this.Mode = mode
	var updateFirmware bool = false
	this.UpdateFirmware = &updateFirmware
	return &this
}

// NewDpuReprovisionRequestWithDefaults instantiates a new DpuReprovisionRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDpuReprovisionRequestWithDefaults() *DpuReprovisionRequest {
	this := DpuReprovisionRequest{}
	var updateFirmware bool = false
	this.UpdateFirmware = &updateFirmware
	return &this
}

// GetMode returns the Mode field value
func (o *DpuReprovisionRequest) GetMode() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Mode
}

// GetModeOk returns a tuple with the Mode field value
// and a boolean to check if the value has been set.
func (o *DpuReprovisionRequest) GetModeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Mode, true
}

// SetMode sets field value
func (o *DpuReprovisionRequest) SetMode(v string) {
	o.Mode = v
}

// GetUpdateFirmware returns the UpdateFirmware field value if set, zero value otherwise.
// Deprecated
func (o *DpuReprovisionRequest) GetUpdateFirmware() bool {
	if o == nil || IsNil(o.UpdateFirmware) {
		var ret bool
		return ret
	}
	return *o.UpdateFirmware
}

// GetUpdateFirmwareOk returns a tuple with the UpdateFirmware field value if set, nil otherwise
// and a boolean to check if the value has been set.
// Deprecated
func (o *DpuReprovisionRequest) GetUpdateFirmwareOk() (*bool, bool) {
	if o == nil || IsNil(o.UpdateFirmware) {
		return nil, false
	}
	return o.UpdateFirmware, true
}

// HasUpdateFirmware returns a boolean if a field has been set.
func (o *DpuReprovisionRequest) HasUpdateFirmware() bool {
	if o != nil && !IsNil(o.UpdateFirmware) {
		return true
	}

	return false
}

// SetUpdateFirmware gets a reference to the given bool and assigns it to the UpdateFirmware field.
// Deprecated
func (o *DpuReprovisionRequest) SetUpdateFirmware(v bool) {
	o.UpdateFirmware = &v
}

// GetAcknowledgeAttachedInstance returns the AcknowledgeAttachedInstance field value if set, zero value otherwise.
func (o *DpuReprovisionRequest) GetAcknowledgeAttachedInstance() bool {
	if o == nil || IsNil(o.AcknowledgeAttachedInstance) {
		var ret bool
		return ret
	}
	return *o.AcknowledgeAttachedInstance
}

// GetAcknowledgeAttachedInstanceOk returns a tuple with the AcknowledgeAttachedInstance field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DpuReprovisionRequest) GetAcknowledgeAttachedInstanceOk() (*bool, bool) {
	if o == nil || IsNil(o.AcknowledgeAttachedInstance) {
		return nil, false
	}
	return o.AcknowledgeAttachedInstance, true
}

// HasAcknowledgeAttachedInstance returns a boolean if a field has been set.
func (o *DpuReprovisionRequest) HasAcknowledgeAttachedInstance() bool {
	if o != nil && !IsNil(o.AcknowledgeAttachedInstance) {
		return true
	}

	return false
}

// SetAcknowledgeAttachedInstance gets a reference to the given bool and assigns it to the AcknowledgeAttachedInstance field.
func (o *DpuReprovisionRequest) SetAcknowledgeAttachedInstance(v bool) {
	o.AcknowledgeAttachedInstance = &v
}

func (o DpuReprovisionRequest) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DpuReprovisionRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["mode"] = o.Mode
	if !IsNil(o.UpdateFirmware) {
		toSerialize["updateFirmware"] = o.UpdateFirmware
	}
	if !IsNil(o.AcknowledgeAttachedInstance) {
		toSerialize["acknowledgeAttachedInstance"] = o.AcknowledgeAttachedInstance
	}
	return toSerialize, nil
}

func (o *DpuReprovisionRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"mode",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if value, exists := allProperties[requiredProperty]; !exists || value == nil {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varDpuReprovisionRequest := _DpuReprovisionRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varDpuReprovisionRequest)

	if err != nil {
		return err
	}

	*o = DpuReprovisionRequest(varDpuReprovisionRequest)

	return err
}

type NullableDpuReprovisionRequest struct {
	value *DpuReprovisionRequest
	isSet bool
}

func (v NullableDpuReprovisionRequest) Get() *DpuReprovisionRequest {
	return v.value
}

func (v *NullableDpuReprovisionRequest) Set(val *DpuReprovisionRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableDpuReprovisionRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableDpuReprovisionRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDpuReprovisionRequest(val *DpuReprovisionRequest) *NullableDpuReprovisionRequest {
	return &NullableDpuReprovisionRequest{value: val, isSet: true}
}

func (v NullableDpuReprovisionRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDpuReprovisionRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
