// SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
// SPDX-License-Identifier: Apache-2.0

/*
NVIDIA Infra Controller REST API

NVIDIA Infra Controller REST API allows users to create and manage resources, e.g., VPCs, Subnets, and Instances, across all connected NVIDIA Infra Controller datacenters, also referred to as Sites.

API version: 2.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package standard

import (
	"encoding/json"
	"time"
)

// checks if the ExpectedRack type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ExpectedRack{}

// ExpectedRack An Expected Rack represents a rack that is expected to be discovered at a Site. The `rackId` is an operator-supplied string identifier (not a UUID) that uniquely identifies the rack within the Site. Each Expected Rack references a Rack Profile that describes the rack's expected layout and capabilities.  Chassis identity and physical location information are conveyed via well-known label keys in `labels`: - `chassis.manufacturer`, `chassis.serial-number`, `chassis.model` - `location.region`, `location.datacenter`, `location.room`, `location.position`
type ExpectedRack struct {
	// Unique identifier (UUID) for the Expected Rack
	Id *string `json:"id,omitempty"`
	// Operator-supplied identifier for the rack (string, not UUID). Unique within a Site.
	RackId *string `json:"rackId,omitempty"`
	// ID of the Site the Expected Rack belongs to
	SiteId *string `json:"siteId,omitempty"`
	// Identifier of the Rack Profile this rack conforms to
	RackProfileId *string `json:"rackProfileId,omitempty"`
	// Human-readable name of the Expected Rack
	Name *string `json:"name,omitempty"`
	// Human-readable description of the Expected Rack
	Description *string `json:"description,omitempty"`
	// User-defined key-value pairs for organizing and categorizing Expected Racks. Well-known keys (`chassis.*`, `location.*`) are used to convey chassis identity and physical location.
	Labels map[string]string `json:"labels,omitempty"`
	// ISO 8601 datetime when the Expected Rack was created
	Created *time.Time `json:"created,omitempty"`
	// ISO 8601 datetime when the Expected Rack was last updated
	Updated *time.Time `json:"updated,omitempty"`
}

// NewExpectedRack instantiates a new ExpectedRack object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewExpectedRack() *ExpectedRack {
	this := ExpectedRack{}
	return &this
}

// NewExpectedRackWithDefaults instantiates a new ExpectedRack object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewExpectedRackWithDefaults() *ExpectedRack {
	this := ExpectedRack{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *ExpectedRack) GetId() string {
	if o == nil || IsNil(o.Id) {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ExpectedRack) GetIdOk() (*string, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *ExpectedRack) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *ExpectedRack) SetId(v string) {
	o.Id = &v
}

// GetRackId returns the RackId field value if set, zero value otherwise.
func (o *ExpectedRack) GetRackId() string {
	if o == nil || IsNil(o.RackId) {
		var ret string
		return ret
	}
	return *o.RackId
}

// GetRackIdOk returns a tuple with the RackId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ExpectedRack) GetRackIdOk() (*string, bool) {
	if o == nil || IsNil(o.RackId) {
		return nil, false
	}
	return o.RackId, true
}

// HasRackId returns a boolean if a field has been set.
func (o *ExpectedRack) HasRackId() bool {
	if o != nil && !IsNil(o.RackId) {
		return true
	}

	return false
}

// SetRackId gets a reference to the given string and assigns it to the RackId field.
func (o *ExpectedRack) SetRackId(v string) {
	o.RackId = &v
}

// GetSiteId returns the SiteId field value if set, zero value otherwise.
func (o *ExpectedRack) GetSiteId() string {
	if o == nil || IsNil(o.SiteId) {
		var ret string
		return ret
	}
	return *o.SiteId
}

// GetSiteIdOk returns a tuple with the SiteId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ExpectedRack) GetSiteIdOk() (*string, bool) {
	if o == nil || IsNil(o.SiteId) {
		return nil, false
	}
	return o.SiteId, true
}

// HasSiteId returns a boolean if a field has been set.
func (o *ExpectedRack) HasSiteId() bool {
	if o != nil && !IsNil(o.SiteId) {
		return true
	}

	return false
}

// SetSiteId gets a reference to the given string and assigns it to the SiteId field.
func (o *ExpectedRack) SetSiteId(v string) {
	o.SiteId = &v
}

// GetRackProfileId returns the RackProfileId field value if set, zero value otherwise.
func (o *ExpectedRack) GetRackProfileId() string {
	if o == nil || IsNil(o.RackProfileId) {
		var ret string
		return ret
	}
	return *o.RackProfileId
}

// GetRackProfileIdOk returns a tuple with the RackProfileId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ExpectedRack) GetRackProfileIdOk() (*string, bool) {
	if o == nil || IsNil(o.RackProfileId) {
		return nil, false
	}
	return o.RackProfileId, true
}

// HasRackProfileId returns a boolean if a field has been set.
func (o *ExpectedRack) HasRackProfileId() bool {
	if o != nil && !IsNil(o.RackProfileId) {
		return true
	}

	return false
}

// SetRackProfileId gets a reference to the given string and assigns it to the RackProfileId field.
func (o *ExpectedRack) SetRackProfileId(v string) {
	o.RackProfileId = &v
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *ExpectedRack) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ExpectedRack) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *ExpectedRack) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *ExpectedRack) SetName(v string) {
	o.Name = &v
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *ExpectedRack) GetDescription() string {
	if o == nil || IsNil(o.Description) {
		var ret string
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ExpectedRack) GetDescriptionOk() (*string, bool) {
	if o == nil || IsNil(o.Description) {
		return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *ExpectedRack) HasDescription() bool {
	if o != nil && !IsNil(o.Description) {
		return true
	}

	return false
}

// SetDescription gets a reference to the given string and assigns it to the Description field.
func (o *ExpectedRack) SetDescription(v string) {
	o.Description = &v
}

// GetLabels returns the Labels field value if set, zero value otherwise.
func (o *ExpectedRack) GetLabels() map[string]string {
	if o == nil || IsNil(o.Labels) {
		var ret map[string]string
		return ret
	}
	return o.Labels
}

// GetLabelsOk returns a tuple with the Labels field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ExpectedRack) GetLabelsOk() (map[string]string, bool) {
	if o == nil || IsNil(o.Labels) {
		return map[string]string{}, false
	}
	return o.Labels, true
}

// HasLabels returns a boolean if a field has been set.
func (o *ExpectedRack) HasLabels() bool {
	if o != nil && !IsNil(o.Labels) {
		return true
	}

	return false
}

// SetLabels gets a reference to the given map[string]string and assigns it to the Labels field.
func (o *ExpectedRack) SetLabels(v map[string]string) {
	o.Labels = v
}

// GetCreated returns the Created field value if set, zero value otherwise.
func (o *ExpectedRack) GetCreated() time.Time {
	if o == nil || IsNil(o.Created) {
		var ret time.Time
		return ret
	}
	return *o.Created
}

// GetCreatedOk returns a tuple with the Created field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ExpectedRack) GetCreatedOk() (*time.Time, bool) {
	if o == nil || IsNil(o.Created) {
		return nil, false
	}
	return o.Created, true
}

// HasCreated returns a boolean if a field has been set.
func (o *ExpectedRack) HasCreated() bool {
	if o != nil && !IsNil(o.Created) {
		return true
	}

	return false
}

// SetCreated gets a reference to the given time.Time and assigns it to the Created field.
func (o *ExpectedRack) SetCreated(v time.Time) {
	o.Created = &v
}

// GetUpdated returns the Updated field value if set, zero value otherwise.
func (o *ExpectedRack) GetUpdated() time.Time {
	if o == nil || IsNil(o.Updated) {
		var ret time.Time
		return ret
	}
	return *o.Updated
}

// GetUpdatedOk returns a tuple with the Updated field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ExpectedRack) GetUpdatedOk() (*time.Time, bool) {
	if o == nil || IsNil(o.Updated) {
		return nil, false
	}
	return o.Updated, true
}

// HasUpdated returns a boolean if a field has been set.
func (o *ExpectedRack) HasUpdated() bool {
	if o != nil && !IsNil(o.Updated) {
		return true
	}

	return false
}

// SetUpdated gets a reference to the given time.Time and assigns it to the Updated field.
func (o *ExpectedRack) SetUpdated(v time.Time) {
	o.Updated = &v
}

func (o ExpectedRack) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ExpectedRack) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.RackId) {
		toSerialize["rackId"] = o.RackId
	}
	if !IsNil(o.SiteId) {
		toSerialize["siteId"] = o.SiteId
	}
	if !IsNil(o.RackProfileId) {
		toSerialize["rackProfileId"] = o.RackProfileId
	}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if !IsNil(o.Description) {
		toSerialize["description"] = o.Description
	}
	if !IsNil(o.Labels) {
		toSerialize["labels"] = o.Labels
	}
	if !IsNil(o.Created) {
		toSerialize["created"] = o.Created
	}
	if !IsNil(o.Updated) {
		toSerialize["updated"] = o.Updated
	}
	return toSerialize, nil
}

type NullableExpectedRack struct {
	value *ExpectedRack
	isSet bool
}

func (v NullableExpectedRack) Get() *ExpectedRack {
	return v.value
}

func (v *NullableExpectedRack) Set(val *ExpectedRack) {
	v.value = val
	v.isSet = true
}

func (v NullableExpectedRack) IsSet() bool {
	return v.isSet
}

func (v *NullableExpectedRack) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableExpectedRack(val *ExpectedRack) *NullableExpectedRack {
	return &NullableExpectedRack{value: val, isSet: true}
}

func (v NullableExpectedRack) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableExpectedRack) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
