// SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
// SPDX-License-Identifier: Apache-2.0

/*
NVIDIA Infra Controller REST API

NVIDIA Infra Controller REST API allows users to create and manage resources, e.g., VPCs, Subnets, and Instances, across all connected NVIDIA Infra Controller datacenters, also referred to as Sites.

API version: 2.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package standard

import (
	"encoding/json"
	"time"
)

// checks if the InfiniBandPartition type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &InfiniBandPartition{}

// InfiniBandPartition InfiniBand Partitions are network segments utilizing InfiniBand topology
type InfiniBandPartition struct {
	// Unique UUID v4 identifier for the InfiniBand Partition
	Id *string `json:"id,omitempty"`
	// Name of the InfiniBand Partition
	Name *string `json:"name,omitempty"`
	// Description of the InfiniBand Partition
	Description NullableString `json:"description,omitempty"`
	// ID of the Site
	SiteId *string `json:"siteId,omitempty"`
	// ID of the Tenant
	TenantId *string `json:"tenantId,omitempty"`
	// ID of the Site Controller InfiniBand partition corresponding to this InfiniBand Partition
	ControllerIBPartitionId NullableString `json:"controllerIBPartitionId,omitempty"`
	// Partition key assigned to the InfiniBand Partition
	PartitionKey NullableString `json:"partitionKey,omitempty"`
	// Partition name assigned to the InfiniBand Partition
	PartitionName NullableString `json:"partitionName,omitempty"`
	// Service level configured for the InfiniBand Partition
	ServiceLevel NullableInt32 `json:"serviceLevel,omitempty"`
	// Rate limit configured for the InfiniBand Partition
	RateLimit NullableFloat32 `json:"rateLimit,omitempty"`
	// MTU configured for the InfiniBand Partition
	Mtu NullableInt32 `json:"mtu,omitempty"`
	// Whether SHARP is enabled for the InfiniBand Partition
	EnableSharp *bool `json:"enableSharp,omitempty"`
	// String key-value pairs describing InfiniBand Partition labels. Up to 10 key-value pairs can be specified
	Labels map[string]string `json:"labels,omitempty"`
	// Status of the InfiniBand Partition
	Status *InfiniBandPartitionStatus `json:"status,omitempty"`
	// Chronological status history for the InfiniBand Partition
	StatusHistory []StatusDetail `json:"statusHistory,omitempty"`
	// Date/time when the InfiniBand Partition was created
	Created *time.Time `json:"created,omitempty"`
	// Date/time when the InfiniBand Partition was last updated
	Updated *time.Time `json:"updated,omitempty"`
}

// NewInfiniBandPartition instantiates a new InfiniBandPartition object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewInfiniBandPartition() *InfiniBandPartition {
	this := InfiniBandPartition{}
	return &this
}

// NewInfiniBandPartitionWithDefaults instantiates a new InfiniBandPartition object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewInfiniBandPartitionWithDefaults() *InfiniBandPartition {
	this := InfiniBandPartition{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *InfiniBandPartition) GetId() string {
	if o == nil || IsNil(o.Id) {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InfiniBandPartition) GetIdOk() (*string, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *InfiniBandPartition) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *InfiniBandPartition) SetId(v string) {
	o.Id = &v
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *InfiniBandPartition) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InfiniBandPartition) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *InfiniBandPartition) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *InfiniBandPartition) SetName(v string) {
	o.Name = &v
}

// GetDescription returns the Description field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *InfiniBandPartition) GetDescription() string {
	if o == nil || IsNil(o.Description.Get()) {
		var ret string
		return ret
	}
	return *o.Description.Get()
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *InfiniBandPartition) GetDescriptionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Description.Get(), o.Description.IsSet()
}

// HasDescription returns a boolean if a field has been set.
func (o *InfiniBandPartition) HasDescription() bool {
	if o != nil && o.Description.IsSet() {
		return true
	}

	return false
}

// SetDescription gets a reference to the given NullableString and assigns it to the Description field.
func (o *InfiniBandPartition) SetDescription(v string) {
	o.Description.Set(&v)
}

// SetDescriptionNil sets the value for Description to be an explicit nil
func (o *InfiniBandPartition) SetDescriptionNil() {
	o.Description.Set(nil)
}

// UnsetDescription ensures that no value is present for Description, not even an explicit nil
func (o *InfiniBandPartition) UnsetDescription() {
	o.Description.Unset()
}

// GetSiteId returns the SiteId field value if set, zero value otherwise.
func (o *InfiniBandPartition) GetSiteId() string {
	if o == nil || IsNil(o.SiteId) {
		var ret string
		return ret
	}
	return *o.SiteId
}

// GetSiteIdOk returns a tuple with the SiteId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InfiniBandPartition) GetSiteIdOk() (*string, bool) {
	if o == nil || IsNil(o.SiteId) {
		return nil, false
	}
	return o.SiteId, true
}

// HasSiteId returns a boolean if a field has been set.
func (o *InfiniBandPartition) HasSiteId() bool {
	if o != nil && !IsNil(o.SiteId) {
		return true
	}

	return false
}

// SetSiteId gets a reference to the given string and assigns it to the SiteId field.
func (o *InfiniBandPartition) SetSiteId(v string) {
	o.SiteId = &v
}

// GetTenantId returns the TenantId field value if set, zero value otherwise.
func (o *InfiniBandPartition) GetTenantId() string {
	if o == nil || IsNil(o.TenantId) {
		var ret string
		return ret
	}
	return *o.TenantId
}

// GetTenantIdOk returns a tuple with the TenantId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InfiniBandPartition) GetTenantIdOk() (*string, bool) {
	if o == nil || IsNil(o.TenantId) {
		return nil, false
	}
	return o.TenantId, true
}

// HasTenantId returns a boolean if a field has been set.
func (o *InfiniBandPartition) HasTenantId() bool {
	if o != nil && !IsNil(o.TenantId) {
		return true
	}

	return false
}

// SetTenantId gets a reference to the given string and assigns it to the TenantId field.
func (o *InfiniBandPartition) SetTenantId(v string) {
	o.TenantId = &v
}

// GetControllerIBPartitionId returns the ControllerIBPartitionId field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *InfiniBandPartition) GetControllerIBPartitionId() string {
	if o == nil || IsNil(o.ControllerIBPartitionId.Get()) {
		var ret string
		return ret
	}
	return *o.ControllerIBPartitionId.Get()
}

// GetControllerIBPartitionIdOk returns a tuple with the ControllerIBPartitionId field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *InfiniBandPartition) GetControllerIBPartitionIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.ControllerIBPartitionId.Get(), o.ControllerIBPartitionId.IsSet()
}

// HasControllerIBPartitionId returns a boolean if a field has been set.
func (o *InfiniBandPartition) HasControllerIBPartitionId() bool {
	if o != nil && o.ControllerIBPartitionId.IsSet() {
		return true
	}

	return false
}

// SetControllerIBPartitionId gets a reference to the given NullableString and assigns it to the ControllerIBPartitionId field.
func (o *InfiniBandPartition) SetControllerIBPartitionId(v string) {
	o.ControllerIBPartitionId.Set(&v)
}

// SetControllerIBPartitionIdNil sets the value for ControllerIBPartitionId to be an explicit nil
func (o *InfiniBandPartition) SetControllerIBPartitionIdNil() {
	o.ControllerIBPartitionId.Set(nil)
}

// UnsetControllerIBPartitionId ensures that no value is present for ControllerIBPartitionId, not even an explicit nil
func (o *InfiniBandPartition) UnsetControllerIBPartitionId() {
	o.ControllerIBPartitionId.Unset()
}

// GetPartitionKey returns the PartitionKey field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *InfiniBandPartition) GetPartitionKey() string {
	if o == nil || IsNil(o.PartitionKey.Get()) {
		var ret string
		return ret
	}
	return *o.PartitionKey.Get()
}

// GetPartitionKeyOk returns a tuple with the PartitionKey field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *InfiniBandPartition) GetPartitionKeyOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.PartitionKey.Get(), o.PartitionKey.IsSet()
}

// HasPartitionKey returns a boolean if a field has been set.
func (o *InfiniBandPartition) HasPartitionKey() bool {
	if o != nil && o.PartitionKey.IsSet() {
		return true
	}

	return false
}

// SetPartitionKey gets a reference to the given NullableString and assigns it to the PartitionKey field.
func (o *InfiniBandPartition) SetPartitionKey(v string) {
	o.PartitionKey.Set(&v)
}

// SetPartitionKeyNil sets the value for PartitionKey to be an explicit nil
func (o *InfiniBandPartition) SetPartitionKeyNil() {
	o.PartitionKey.Set(nil)
}

// UnsetPartitionKey ensures that no value is present for PartitionKey, not even an explicit nil
func (o *InfiniBandPartition) UnsetPartitionKey() {
	o.PartitionKey.Unset()
}

// GetPartitionName returns the PartitionName field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *InfiniBandPartition) GetPartitionName() string {
	if o == nil || IsNil(o.PartitionName.Get()) {
		var ret string
		return ret
	}
	return *o.PartitionName.Get()
}

// GetPartitionNameOk returns a tuple with the PartitionName field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *InfiniBandPartition) GetPartitionNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.PartitionName.Get(), o.PartitionName.IsSet()
}

// HasPartitionName returns a boolean if a field has been set.
func (o *InfiniBandPartition) HasPartitionName() bool {
	if o != nil && o.PartitionName.IsSet() {
		return true
	}

	return false
}

// SetPartitionName gets a reference to the given NullableString and assigns it to the PartitionName field.
func (o *InfiniBandPartition) SetPartitionName(v string) {
	o.PartitionName.Set(&v)
}

// SetPartitionNameNil sets the value for PartitionName to be an explicit nil
func (o *InfiniBandPartition) SetPartitionNameNil() {
	o.PartitionName.Set(nil)
}

// UnsetPartitionName ensures that no value is present for PartitionName, not even an explicit nil
func (o *InfiniBandPartition) UnsetPartitionName() {
	o.PartitionName.Unset()
}

// GetServiceLevel returns the ServiceLevel field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *InfiniBandPartition) GetServiceLevel() int32 {
	if o == nil || IsNil(o.ServiceLevel.Get()) {
		var ret int32
		return ret
	}
	return *o.ServiceLevel.Get()
}

// GetServiceLevelOk returns a tuple with the ServiceLevel field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *InfiniBandPartition) GetServiceLevelOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.ServiceLevel.Get(), o.ServiceLevel.IsSet()
}

// HasServiceLevel returns a boolean if a field has been set.
func (o *InfiniBandPartition) HasServiceLevel() bool {
	if o != nil && o.ServiceLevel.IsSet() {
		return true
	}

	return false
}

// SetServiceLevel gets a reference to the given NullableInt32 and assigns it to the ServiceLevel field.
func (o *InfiniBandPartition) SetServiceLevel(v int32) {
	o.ServiceLevel.Set(&v)
}

// SetServiceLevelNil sets the value for ServiceLevel to be an explicit nil
func (o *InfiniBandPartition) SetServiceLevelNil() {
	o.ServiceLevel.Set(nil)
}

// UnsetServiceLevel ensures that no value is present for ServiceLevel, not even an explicit nil
func (o *InfiniBandPartition) UnsetServiceLevel() {
	o.ServiceLevel.Unset()
}

// GetRateLimit returns the RateLimit field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *InfiniBandPartition) GetRateLimit() float32 {
	if o == nil || IsNil(o.RateLimit.Get()) {
		var ret float32
		return ret
	}
	return *o.RateLimit.Get()
}

// GetRateLimitOk returns a tuple with the RateLimit field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *InfiniBandPartition) GetRateLimitOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return o.RateLimit.Get(), o.RateLimit.IsSet()
}

// HasRateLimit returns a boolean if a field has been set.
func (o *InfiniBandPartition) HasRateLimit() bool {
	if o != nil && o.RateLimit.IsSet() {
		return true
	}

	return false
}

// SetRateLimit gets a reference to the given NullableFloat32 and assigns it to the RateLimit field.
func (o *InfiniBandPartition) SetRateLimit(v float32) {
	o.RateLimit.Set(&v)
}

// SetRateLimitNil sets the value for RateLimit to be an explicit nil
func (o *InfiniBandPartition) SetRateLimitNil() {
	o.RateLimit.Set(nil)
}

// UnsetRateLimit ensures that no value is present for RateLimit, not even an explicit nil
func (o *InfiniBandPartition) UnsetRateLimit() {
	o.RateLimit.Unset()
}

// GetMtu returns the Mtu field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *InfiniBandPartition) GetMtu() int32 {
	if o == nil || IsNil(o.Mtu.Get()) {
		var ret int32
		return ret
	}
	return *o.Mtu.Get()
}

// GetMtuOk returns a tuple with the Mtu field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *InfiniBandPartition) GetMtuOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.Mtu.Get(), o.Mtu.IsSet()
}

// HasMtu returns a boolean if a field has been set.
func (o *InfiniBandPartition) HasMtu() bool {
	if o != nil && o.Mtu.IsSet() {
		return true
	}

	return false
}

// SetMtu gets a reference to the given NullableInt32 and assigns it to the Mtu field.
func (o *InfiniBandPartition) SetMtu(v int32) {
	o.Mtu.Set(&v)
}

// SetMtuNil sets the value for Mtu to be an explicit nil
func (o *InfiniBandPartition) SetMtuNil() {
	o.Mtu.Set(nil)
}

// UnsetMtu ensures that no value is present for Mtu, not even an explicit nil
func (o *InfiniBandPartition) UnsetMtu() {
	o.Mtu.Unset()
}

// GetEnableSharp returns the EnableSharp field value if set, zero value otherwise.
func (o *InfiniBandPartition) GetEnableSharp() bool {
	if o == nil || IsNil(o.EnableSharp) {
		var ret bool
		return ret
	}
	return *o.EnableSharp
}

// GetEnableSharpOk returns a tuple with the EnableSharp field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InfiniBandPartition) GetEnableSharpOk() (*bool, bool) {
	if o == nil || IsNil(o.EnableSharp) {
		return nil, false
	}
	return o.EnableSharp, true
}

// HasEnableSharp returns a boolean if a field has been set.
func (o *InfiniBandPartition) HasEnableSharp() bool {
	if o != nil && !IsNil(o.EnableSharp) {
		return true
	}

	return false
}

// SetEnableSharp gets a reference to the given bool and assigns it to the EnableSharp field.
func (o *InfiniBandPartition) SetEnableSharp(v bool) {
	o.EnableSharp = &v
}

// GetLabels returns the Labels field value if set, zero value otherwise.
func (o *InfiniBandPartition) GetLabels() map[string]string {
	if o == nil || IsNil(o.Labels) {
		var ret map[string]string
		return ret
	}
	return o.Labels
}

// GetLabelsOk returns a tuple with the Labels field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InfiniBandPartition) GetLabelsOk() (map[string]string, bool) {
	if o == nil || IsNil(o.Labels) {
		return map[string]string{}, false
	}
	return o.Labels, true
}

// HasLabels returns a boolean if a field has been set.
func (o *InfiniBandPartition) HasLabels() bool {
	if o != nil && !IsNil(o.Labels) {
		return true
	}

	return false
}

// SetLabels gets a reference to the given map[string]string and assigns it to the Labels field.
func (o *InfiniBandPartition) SetLabels(v map[string]string) {
	o.Labels = v
}

// GetStatus returns the Status field value if set, zero value otherwise.
func (o *InfiniBandPartition) GetStatus() InfiniBandPartitionStatus {
	if o == nil || IsNil(o.Status) {
		var ret InfiniBandPartitionStatus
		return ret
	}
	return *o.Status
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InfiniBandPartition) GetStatusOk() (*InfiniBandPartitionStatus, bool) {
	if o == nil || IsNil(o.Status) {
		return nil, false
	}
	return o.Status, true
}

// HasStatus returns a boolean if a field has been set.
func (o *InfiniBandPartition) HasStatus() bool {
	if o != nil && !IsNil(o.Status) {
		return true
	}

	return false
}

// SetStatus gets a reference to the given InfiniBandPartitionStatus and assigns it to the Status field.
func (o *InfiniBandPartition) SetStatus(v InfiniBandPartitionStatus) {
	o.Status = &v
}

// GetStatusHistory returns the StatusHistory field value if set, zero value otherwise.
func (o *InfiniBandPartition) GetStatusHistory() []StatusDetail {
	if o == nil || IsNil(o.StatusHistory) {
		var ret []StatusDetail
		return ret
	}
	return o.StatusHistory
}

// GetStatusHistoryOk returns a tuple with the StatusHistory field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InfiniBandPartition) GetStatusHistoryOk() ([]StatusDetail, bool) {
	if o == nil || IsNil(o.StatusHistory) {
		return nil, false
	}
	return o.StatusHistory, true
}

// HasStatusHistory returns a boolean if a field has been set.
func (o *InfiniBandPartition) HasStatusHistory() bool {
	if o != nil && !IsNil(o.StatusHistory) {
		return true
	}

	return false
}

// SetStatusHistory gets a reference to the given []StatusDetail and assigns it to the StatusHistory field.
func (o *InfiniBandPartition) SetStatusHistory(v []StatusDetail) {
	o.StatusHistory = v
}

// GetCreated returns the Created field value if set, zero value otherwise.
func (o *InfiniBandPartition) GetCreated() time.Time {
	if o == nil || IsNil(o.Created) {
		var ret time.Time
		return ret
	}
	return *o.Created
}

// GetCreatedOk returns a tuple with the Created field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InfiniBandPartition) GetCreatedOk() (*time.Time, bool) {
	if o == nil || IsNil(o.Created) {
		return nil, false
	}
	return o.Created, true
}

// HasCreated returns a boolean if a field has been set.
func (o *InfiniBandPartition) HasCreated() bool {
	if o != nil && !IsNil(o.Created) {
		return true
	}

	return false
}

// SetCreated gets a reference to the given time.Time and assigns it to the Created field.
func (o *InfiniBandPartition) SetCreated(v time.Time) {
	o.Created = &v
}

// GetUpdated returns the Updated field value if set, zero value otherwise.
func (o *InfiniBandPartition) GetUpdated() time.Time {
	if o == nil || IsNil(o.Updated) {
		var ret time.Time
		return ret
	}
	return *o.Updated
}

// GetUpdatedOk returns a tuple with the Updated field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InfiniBandPartition) GetUpdatedOk() (*time.Time, bool) {
	if o == nil || IsNil(o.Updated) {
		return nil, false
	}
	return o.Updated, true
}

// HasUpdated returns a boolean if a field has been set.
func (o *InfiniBandPartition) HasUpdated() bool {
	if o != nil && !IsNil(o.Updated) {
		return true
	}

	return false
}

// SetUpdated gets a reference to the given time.Time and assigns it to the Updated field.
func (o *InfiniBandPartition) SetUpdated(v time.Time) {
	o.Updated = &v
}

func (o InfiniBandPartition) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o InfiniBandPartition) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if o.Description.IsSet() {
		toSerialize["description"] = o.Description.Get()
	}
	if !IsNil(o.SiteId) {
		toSerialize["siteId"] = o.SiteId
	}
	if !IsNil(o.TenantId) {
		toSerialize["tenantId"] = o.TenantId
	}
	if o.ControllerIBPartitionId.IsSet() {
		toSerialize["controllerIBPartitionId"] = o.ControllerIBPartitionId.Get()
	}
	if o.PartitionKey.IsSet() {
		toSerialize["partitionKey"] = o.PartitionKey.Get()
	}
	if o.PartitionName.IsSet() {
		toSerialize["partitionName"] = o.PartitionName.Get()
	}
	if o.ServiceLevel.IsSet() {
		toSerialize["serviceLevel"] = o.ServiceLevel.Get()
	}
	if o.RateLimit.IsSet() {
		toSerialize["rateLimit"] = o.RateLimit.Get()
	}
	if o.Mtu.IsSet() {
		toSerialize["mtu"] = o.Mtu.Get()
	}
	if !IsNil(o.EnableSharp) {
		toSerialize["enableSharp"] = o.EnableSharp
	}
	if !IsNil(o.Labels) {
		toSerialize["labels"] = o.Labels
	}
	if !IsNil(o.Status) {
		toSerialize["status"] = o.Status
	}
	if !IsNil(o.StatusHistory) {
		toSerialize["statusHistory"] = o.StatusHistory
	}
	if !IsNil(o.Created) {
		toSerialize["created"] = o.Created
	}
	if !IsNil(o.Updated) {
		toSerialize["updated"] = o.Updated
	}
	return toSerialize, nil
}

type NullableInfiniBandPartition struct {
	value *InfiniBandPartition
	isSet bool
}

func (v NullableInfiniBandPartition) Get() *InfiniBandPartition {
	return v.value
}

func (v *NullableInfiniBandPartition) Set(val *InfiniBandPartition) {
	v.value = val
	v.isSet = true
}

func (v NullableInfiniBandPartition) IsSet() bool {
	return v.isSet
}

func (v *NullableInfiniBandPartition) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableInfiniBandPartition(val *InfiniBandPartition) *NullableInfiniBandPartition {
	return &NullableInfiniBandPartition{value: val, isSet: true}
}

func (v NullableInfiniBandPartition) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableInfiniBandPartition) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
