// SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
// SPDX-License-Identifier: Apache-2.0

/*
NVIDIA Infra Controller REST API

NVIDIA Infra Controller REST API allows users to create and manage resources, e.g., VPCs, Subnets, and Instances, across all connected NVIDIA Infra Controller datacenters, also referred to as Sites.

API version: 2.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package standard

import (
	"encoding/json"
	"time"
)

// checks if the Instance type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &Instance{}

// Instance Instance is a baremetal Machine that has been provisioned for a Tenant
type Instance struct {
	// Unique identifier for the Instance
	Id *string `json:"id,omitempty"`
	// Name for the Instance
	Name *string `json:"name,omitempty"`
	// Description for the Instance
	Description NullableString `json:"description,omitempty"`
	// ID of the Tenant the Instance belongs to
	TenantId *string `json:"tenantId,omitempty"`
	// ID of the Infrastructure Provider that owns the Site where the Instance is located
	InfrastructureProviderId *string `json:"infrastructureProviderId,omitempty"`
	// ID of the Site where the Instance is located
	SiteId *string `json:"siteId,omitempty"`
	// ID of the Instance Type
	InstanceTypeId NullableString `json:"instanceTypeId,omitempty"`
	// ID of the VPC
	VpcId *string `json:"vpcId,omitempty"`
	// IDs of VPCs attached to the Instance through non-primary interfaces
	SecondaryVpcIds []string `json:"secondaryVpcIds,omitempty"`
	// ID of the Machine
	MachineId NullableString `json:"machineId,omitempty"`
	// ID of the Operating System
	OperatingSystemId NullableString `json:"operatingSystemId,omitempty"`
	// ID of the attached Network Security Group, if any
	NetworkSecurityGroupId NullableString `json:"networkSecurityGroupId,omitempty"`
	// Propagation details for the attached Network Security Group
	NetworkSecurityGroupPropagationDetails *NetworkSecurityGroupPropagationDetails `json:"networkSecurityGroupPropagationDetails,omitempty"`
	// Indicates if the Network Security Group is inherited from VPC
	NetworkSecurityGroupInherited *bool `json:"networkSecurityGroupInherited,omitempty"`
	// ID of the Instance in Site Controller
	ControllerInstanceId NullableString `json:"controllerInstanceId,omitempty"`
	// Attribute which is inherited from Operating System
	IpxeScript NullableString `json:"ipxeScript,omitempty"`
	// Indicates whether the Instance should always execute custom iPXE script when rebooting
	AlwaysBootWithCustomIpxe *bool `json:"alwaysBootWithCustomIpxe,omitempty"`
	// Indicates whether the Phone Home service should be enabled or disabled for the Instance
	PhoneHomeEnabled *bool `json:"phoneHomeEnabled,omitempty"`
	// UserData is inherited from Operating System or specified by user if allowed
	UserData NullableString `json:"userData,omitempty"`
	// User-specified Instance labels
	Labels map[string]string `json:"labels,omitempty"`
	// Indicates whether an update is available for the Instance. Updates can be applied on reboot
	IsUpdatePending *bool `json:"isUpdatePending,omitempty"`
	// Serial Console URL for the Instance. Format: ssh://<id>@siteSerialConsoleHostname
	SerialConsoleUrl NullableString `json:"serialConsoleUrl,omitempty"`
	// True when this Instance uses NICo auto-resolved networking from the host's underlay (HostInband) network segments. When true, the caller's request `interfaces` list was empty, this `interfaces` field remains empty on readback, and the resolved per-interface details surface under `status.network.interfaces`.
	AutoNetwork *bool `json:"autoNetwork,omitempty"`
	// Interfaces are list of the subnet associated with the Instance
	Interfaces []Interface `json:"interfaces,omitempty"`
	// InfiniBandInterfaces are list of the InfiniBandInterface associated with the Instance
	InfinibandInterfaces []InfiniBandInterface `json:"infinibandInterfaces,omitempty"`
	// NVLinkInterfaces are list of the NVLinkInterface associated with the Instance
	NvLinkInterfaces []NVLinkInterface `json:"nvLinkInterfaces,omitempty"`
	// DPU Extension Services deployed on DPUs of this Instance
	DpuExtensionServiceDeployments []DpuExtensionServiceDeployment `json:"dpuExtensionServiceDeployments,omitempty"`
	// IDs of SSH Key Groups associated with this Instance
	SshKeyGroupIds []string `json:"sshKeyGroupIds,omitempty"`
	// IDs of SSH Key Groups associated with this Instance
	SshKeyGroups []SshKeyGroup `json:"sshKeyGroups,omitempty"`
	// base64 encoded TPM EK Certificate associated with this Instance
	TpmEkCertificate NullableString `json:"tpmEkCertificate,omitempty"`
	// Status of the Instance
	Status *InstanceStatus `json:"status,omitempty"`
	// Chronological status history for the Instance
	StatusHistory []StatusDetail `json:"statusHistory,omitempty"`
	// Deprecations active for this resource. Returned only if there are active deprecations.
	Deprecations []Deprecation `json:"deprecations,omitempty"`
	// Date/time when the Instance was created
	Created *time.Time `json:"created,omitempty"`
	// Date/time when the Instance was last updated
	Updated *time.Time `json:"updated,omitempty"`
}

// NewInstance instantiates a new Instance object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewInstance() *Instance {
	this := Instance{}
	return &this
}

// NewInstanceWithDefaults instantiates a new Instance object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewInstanceWithDefaults() *Instance {
	this := Instance{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *Instance) GetId() string {
	if o == nil || IsNil(o.Id) {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Instance) GetIdOk() (*string, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *Instance) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *Instance) SetId(v string) {
	o.Id = &v
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *Instance) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Instance) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *Instance) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *Instance) SetName(v string) {
	o.Name = &v
}

// GetDescription returns the Description field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *Instance) GetDescription() string {
	if o == nil || IsNil(o.Description.Get()) {
		var ret string
		return ret
	}
	return *o.Description.Get()
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *Instance) GetDescriptionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Description.Get(), o.Description.IsSet()
}

// HasDescription returns a boolean if a field has been set.
func (o *Instance) HasDescription() bool {
	if o != nil && o.Description.IsSet() {
		return true
	}

	return false
}

// SetDescription gets a reference to the given NullableString and assigns it to the Description field.
func (o *Instance) SetDescription(v string) {
	o.Description.Set(&v)
}

// SetDescriptionNil sets the value for Description to be an explicit nil
func (o *Instance) SetDescriptionNil() {
	o.Description.Set(nil)
}

// UnsetDescription ensures that no value is present for Description, not even an explicit nil
func (o *Instance) UnsetDescription() {
	o.Description.Unset()
}

// GetTenantId returns the TenantId field value if set, zero value otherwise.
func (o *Instance) GetTenantId() string {
	if o == nil || IsNil(o.TenantId) {
		var ret string
		return ret
	}
	return *o.TenantId
}

// GetTenantIdOk returns a tuple with the TenantId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Instance) GetTenantIdOk() (*string, bool) {
	if o == nil || IsNil(o.TenantId) {
		return nil, false
	}
	return o.TenantId, true
}

// HasTenantId returns a boolean if a field has been set.
func (o *Instance) HasTenantId() bool {
	if o != nil && !IsNil(o.TenantId) {
		return true
	}

	return false
}

// SetTenantId gets a reference to the given string and assigns it to the TenantId field.
func (o *Instance) SetTenantId(v string) {
	o.TenantId = &v
}

// GetInfrastructureProviderId returns the InfrastructureProviderId field value if set, zero value otherwise.
func (o *Instance) GetInfrastructureProviderId() string {
	if o == nil || IsNil(o.InfrastructureProviderId) {
		var ret string
		return ret
	}
	return *o.InfrastructureProviderId
}

// GetInfrastructureProviderIdOk returns a tuple with the InfrastructureProviderId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Instance) GetInfrastructureProviderIdOk() (*string, bool) {
	if o == nil || IsNil(o.InfrastructureProviderId) {
		return nil, false
	}
	return o.InfrastructureProviderId, true
}

// HasInfrastructureProviderId returns a boolean if a field has been set.
func (o *Instance) HasInfrastructureProviderId() bool {
	if o != nil && !IsNil(o.InfrastructureProviderId) {
		return true
	}

	return false
}

// SetInfrastructureProviderId gets a reference to the given string and assigns it to the InfrastructureProviderId field.
func (o *Instance) SetInfrastructureProviderId(v string) {
	o.InfrastructureProviderId = &v
}

// GetSiteId returns the SiteId field value if set, zero value otherwise.
func (o *Instance) GetSiteId() string {
	if o == nil || IsNil(o.SiteId) {
		var ret string
		return ret
	}
	return *o.SiteId
}

// GetSiteIdOk returns a tuple with the SiteId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Instance) GetSiteIdOk() (*string, bool) {
	if o == nil || IsNil(o.SiteId) {
		return nil, false
	}
	return o.SiteId, true
}

// HasSiteId returns a boolean if a field has been set.
func (o *Instance) HasSiteId() bool {
	if o != nil && !IsNil(o.SiteId) {
		return true
	}

	return false
}

// SetSiteId gets a reference to the given string and assigns it to the SiteId field.
func (o *Instance) SetSiteId(v string) {
	o.SiteId = &v
}

// GetInstanceTypeId returns the InstanceTypeId field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *Instance) GetInstanceTypeId() string {
	if o == nil || IsNil(o.InstanceTypeId.Get()) {
		var ret string
		return ret
	}
	return *o.InstanceTypeId.Get()
}

// GetInstanceTypeIdOk returns a tuple with the InstanceTypeId field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *Instance) GetInstanceTypeIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.InstanceTypeId.Get(), o.InstanceTypeId.IsSet()
}

// HasInstanceTypeId returns a boolean if a field has been set.
func (o *Instance) HasInstanceTypeId() bool {
	if o != nil && o.InstanceTypeId.IsSet() {
		return true
	}

	return false
}

// SetInstanceTypeId gets a reference to the given NullableString and assigns it to the InstanceTypeId field.
func (o *Instance) SetInstanceTypeId(v string) {
	o.InstanceTypeId.Set(&v)
}

// SetInstanceTypeIdNil sets the value for InstanceTypeId to be an explicit nil
func (o *Instance) SetInstanceTypeIdNil() {
	o.InstanceTypeId.Set(nil)
}

// UnsetInstanceTypeId ensures that no value is present for InstanceTypeId, not even an explicit nil
func (o *Instance) UnsetInstanceTypeId() {
	o.InstanceTypeId.Unset()
}

// GetVpcId returns the VpcId field value if set, zero value otherwise.
func (o *Instance) GetVpcId() string {
	if o == nil || IsNil(o.VpcId) {
		var ret string
		return ret
	}
	return *o.VpcId
}

// GetVpcIdOk returns a tuple with the VpcId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Instance) GetVpcIdOk() (*string, bool) {
	if o == nil || IsNil(o.VpcId) {
		return nil, false
	}
	return o.VpcId, true
}

// HasVpcId returns a boolean if a field has been set.
func (o *Instance) HasVpcId() bool {
	if o != nil && !IsNil(o.VpcId) {
		return true
	}

	return false
}

// SetVpcId gets a reference to the given string and assigns it to the VpcId field.
func (o *Instance) SetVpcId(v string) {
	o.VpcId = &v
}

// GetSecondaryVpcIds returns the SecondaryVpcIds field value if set, zero value otherwise.
func (o *Instance) GetSecondaryVpcIds() []string {
	if o == nil || IsNil(o.SecondaryVpcIds) {
		var ret []string
		return ret
	}
	return o.SecondaryVpcIds
}

// GetSecondaryVpcIdsOk returns a tuple with the SecondaryVpcIds field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Instance) GetSecondaryVpcIdsOk() ([]string, bool) {
	if o == nil || IsNil(o.SecondaryVpcIds) {
		return nil, false
	}
	return o.SecondaryVpcIds, true
}

// HasSecondaryVpcIds returns a boolean if a field has been set.
func (o *Instance) HasSecondaryVpcIds() bool {
	if o != nil && !IsNil(o.SecondaryVpcIds) {
		return true
	}

	return false
}

// SetSecondaryVpcIds gets a reference to the given []string and assigns it to the SecondaryVpcIds field.
func (o *Instance) SetSecondaryVpcIds(v []string) {
	o.SecondaryVpcIds = v
}

// GetMachineId returns the MachineId field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *Instance) GetMachineId() string {
	if o == nil || IsNil(o.MachineId.Get()) {
		var ret string
		return ret
	}
	return *o.MachineId.Get()
}

// GetMachineIdOk returns a tuple with the MachineId field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *Instance) GetMachineIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.MachineId.Get(), o.MachineId.IsSet()
}

// HasMachineId returns a boolean if a field has been set.
func (o *Instance) HasMachineId() bool {
	if o != nil && o.MachineId.IsSet() {
		return true
	}

	return false
}

// SetMachineId gets a reference to the given NullableString and assigns it to the MachineId field.
func (o *Instance) SetMachineId(v string) {
	o.MachineId.Set(&v)
}

// SetMachineIdNil sets the value for MachineId to be an explicit nil
func (o *Instance) SetMachineIdNil() {
	o.MachineId.Set(nil)
}

// UnsetMachineId ensures that no value is present for MachineId, not even an explicit nil
func (o *Instance) UnsetMachineId() {
	o.MachineId.Unset()
}

// GetOperatingSystemId returns the OperatingSystemId field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *Instance) GetOperatingSystemId() string {
	if o == nil || IsNil(o.OperatingSystemId.Get()) {
		var ret string
		return ret
	}
	return *o.OperatingSystemId.Get()
}

// GetOperatingSystemIdOk returns a tuple with the OperatingSystemId field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *Instance) GetOperatingSystemIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.OperatingSystemId.Get(), o.OperatingSystemId.IsSet()
}

// HasOperatingSystemId returns a boolean if a field has been set.
func (o *Instance) HasOperatingSystemId() bool {
	if o != nil && o.OperatingSystemId.IsSet() {
		return true
	}

	return false
}

// SetOperatingSystemId gets a reference to the given NullableString and assigns it to the OperatingSystemId field.
func (o *Instance) SetOperatingSystemId(v string) {
	o.OperatingSystemId.Set(&v)
}

// SetOperatingSystemIdNil sets the value for OperatingSystemId to be an explicit nil
func (o *Instance) SetOperatingSystemIdNil() {
	o.OperatingSystemId.Set(nil)
}

// UnsetOperatingSystemId ensures that no value is present for OperatingSystemId, not even an explicit nil
func (o *Instance) UnsetOperatingSystemId() {
	o.OperatingSystemId.Unset()
}

// GetNetworkSecurityGroupId returns the NetworkSecurityGroupId field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *Instance) GetNetworkSecurityGroupId() string {
	if o == nil || IsNil(o.NetworkSecurityGroupId.Get()) {
		var ret string
		return ret
	}
	return *o.NetworkSecurityGroupId.Get()
}

// GetNetworkSecurityGroupIdOk returns a tuple with the NetworkSecurityGroupId field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *Instance) GetNetworkSecurityGroupIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.NetworkSecurityGroupId.Get(), o.NetworkSecurityGroupId.IsSet()
}

// HasNetworkSecurityGroupId returns a boolean if a field has been set.
func (o *Instance) HasNetworkSecurityGroupId() bool {
	if o != nil && o.NetworkSecurityGroupId.IsSet() {
		return true
	}

	return false
}

// SetNetworkSecurityGroupId gets a reference to the given NullableString and assigns it to the NetworkSecurityGroupId field.
func (o *Instance) SetNetworkSecurityGroupId(v string) {
	o.NetworkSecurityGroupId.Set(&v)
}

// SetNetworkSecurityGroupIdNil sets the value for NetworkSecurityGroupId to be an explicit nil
func (o *Instance) SetNetworkSecurityGroupIdNil() {
	o.NetworkSecurityGroupId.Set(nil)
}

// UnsetNetworkSecurityGroupId ensures that no value is present for NetworkSecurityGroupId, not even an explicit nil
func (o *Instance) UnsetNetworkSecurityGroupId() {
	o.NetworkSecurityGroupId.Unset()
}

// GetNetworkSecurityGroupPropagationDetails returns the NetworkSecurityGroupPropagationDetails field value if set, zero value otherwise.
func (o *Instance) GetNetworkSecurityGroupPropagationDetails() NetworkSecurityGroupPropagationDetails {
	if o == nil || IsNil(o.NetworkSecurityGroupPropagationDetails) {
		var ret NetworkSecurityGroupPropagationDetails
		return ret
	}
	return *o.NetworkSecurityGroupPropagationDetails
}

// GetNetworkSecurityGroupPropagationDetailsOk returns a tuple with the NetworkSecurityGroupPropagationDetails field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Instance) GetNetworkSecurityGroupPropagationDetailsOk() (*NetworkSecurityGroupPropagationDetails, bool) {
	if o == nil || IsNil(o.NetworkSecurityGroupPropagationDetails) {
		return nil, false
	}
	return o.NetworkSecurityGroupPropagationDetails, true
}

// HasNetworkSecurityGroupPropagationDetails returns a boolean if a field has been set.
func (o *Instance) HasNetworkSecurityGroupPropagationDetails() bool {
	if o != nil && !IsNil(o.NetworkSecurityGroupPropagationDetails) {
		return true
	}

	return false
}

// SetNetworkSecurityGroupPropagationDetails gets a reference to the given NetworkSecurityGroupPropagationDetails and assigns it to the NetworkSecurityGroupPropagationDetails field.
func (o *Instance) SetNetworkSecurityGroupPropagationDetails(v NetworkSecurityGroupPropagationDetails) {
	o.NetworkSecurityGroupPropagationDetails = &v
}

// GetNetworkSecurityGroupInherited returns the NetworkSecurityGroupInherited field value if set, zero value otherwise.
func (o *Instance) GetNetworkSecurityGroupInherited() bool {
	if o == nil || IsNil(o.NetworkSecurityGroupInherited) {
		var ret bool
		return ret
	}
	return *o.NetworkSecurityGroupInherited
}

// GetNetworkSecurityGroupInheritedOk returns a tuple with the NetworkSecurityGroupInherited field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Instance) GetNetworkSecurityGroupInheritedOk() (*bool, bool) {
	if o == nil || IsNil(o.NetworkSecurityGroupInherited) {
		return nil, false
	}
	return o.NetworkSecurityGroupInherited, true
}

// HasNetworkSecurityGroupInherited returns a boolean if a field has been set.
func (o *Instance) HasNetworkSecurityGroupInherited() bool {
	if o != nil && !IsNil(o.NetworkSecurityGroupInherited) {
		return true
	}

	return false
}

// SetNetworkSecurityGroupInherited gets a reference to the given bool and assigns it to the NetworkSecurityGroupInherited field.
func (o *Instance) SetNetworkSecurityGroupInherited(v bool) {
	o.NetworkSecurityGroupInherited = &v
}

// GetControllerInstanceId returns the ControllerInstanceId field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *Instance) GetControllerInstanceId() string {
	if o == nil || IsNil(o.ControllerInstanceId.Get()) {
		var ret string
		return ret
	}
	return *o.ControllerInstanceId.Get()
}

// GetControllerInstanceIdOk returns a tuple with the ControllerInstanceId field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *Instance) GetControllerInstanceIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.ControllerInstanceId.Get(), o.ControllerInstanceId.IsSet()
}

// HasControllerInstanceId returns a boolean if a field has been set.
func (o *Instance) HasControllerInstanceId() bool {
	if o != nil && o.ControllerInstanceId.IsSet() {
		return true
	}

	return false
}

// SetControllerInstanceId gets a reference to the given NullableString and assigns it to the ControllerInstanceId field.
func (o *Instance) SetControllerInstanceId(v string) {
	o.ControllerInstanceId.Set(&v)
}

// SetControllerInstanceIdNil sets the value for ControllerInstanceId to be an explicit nil
func (o *Instance) SetControllerInstanceIdNil() {
	o.ControllerInstanceId.Set(nil)
}

// UnsetControllerInstanceId ensures that no value is present for ControllerInstanceId, not even an explicit nil
func (o *Instance) UnsetControllerInstanceId() {
	o.ControllerInstanceId.Unset()
}

// GetIpxeScript returns the IpxeScript field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *Instance) GetIpxeScript() string {
	if o == nil || IsNil(o.IpxeScript.Get()) {
		var ret string
		return ret
	}
	return *o.IpxeScript.Get()
}

// GetIpxeScriptOk returns a tuple with the IpxeScript field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *Instance) GetIpxeScriptOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.IpxeScript.Get(), o.IpxeScript.IsSet()
}

// HasIpxeScript returns a boolean if a field has been set.
func (o *Instance) HasIpxeScript() bool {
	if o != nil && o.IpxeScript.IsSet() {
		return true
	}

	return false
}

// SetIpxeScript gets a reference to the given NullableString and assigns it to the IpxeScript field.
func (o *Instance) SetIpxeScript(v string) {
	o.IpxeScript.Set(&v)
}

// SetIpxeScriptNil sets the value for IpxeScript to be an explicit nil
func (o *Instance) SetIpxeScriptNil() {
	o.IpxeScript.Set(nil)
}

// UnsetIpxeScript ensures that no value is present for IpxeScript, not even an explicit nil
func (o *Instance) UnsetIpxeScript() {
	o.IpxeScript.Unset()
}

// GetAlwaysBootWithCustomIpxe returns the AlwaysBootWithCustomIpxe field value if set, zero value otherwise.
func (o *Instance) GetAlwaysBootWithCustomIpxe() bool {
	if o == nil || IsNil(o.AlwaysBootWithCustomIpxe) {
		var ret bool
		return ret
	}
	return *o.AlwaysBootWithCustomIpxe
}

// GetAlwaysBootWithCustomIpxeOk returns a tuple with the AlwaysBootWithCustomIpxe field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Instance) GetAlwaysBootWithCustomIpxeOk() (*bool, bool) {
	if o == nil || IsNil(o.AlwaysBootWithCustomIpxe) {
		return nil, false
	}
	return o.AlwaysBootWithCustomIpxe, true
}

// HasAlwaysBootWithCustomIpxe returns a boolean if a field has been set.
func (o *Instance) HasAlwaysBootWithCustomIpxe() bool {
	if o != nil && !IsNil(o.AlwaysBootWithCustomIpxe) {
		return true
	}

	return false
}

// SetAlwaysBootWithCustomIpxe gets a reference to the given bool and assigns it to the AlwaysBootWithCustomIpxe field.
func (o *Instance) SetAlwaysBootWithCustomIpxe(v bool) {
	o.AlwaysBootWithCustomIpxe = &v
}

// GetPhoneHomeEnabled returns the PhoneHomeEnabled field value if set, zero value otherwise.
func (o *Instance) GetPhoneHomeEnabled() bool {
	if o == nil || IsNil(o.PhoneHomeEnabled) {
		var ret bool
		return ret
	}
	return *o.PhoneHomeEnabled
}

// GetPhoneHomeEnabledOk returns a tuple with the PhoneHomeEnabled field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Instance) GetPhoneHomeEnabledOk() (*bool, bool) {
	if o == nil || IsNil(o.PhoneHomeEnabled) {
		return nil, false
	}
	return o.PhoneHomeEnabled, true
}

// HasPhoneHomeEnabled returns a boolean if a field has been set.
func (o *Instance) HasPhoneHomeEnabled() bool {
	if o != nil && !IsNil(o.PhoneHomeEnabled) {
		return true
	}

	return false
}

// SetPhoneHomeEnabled gets a reference to the given bool and assigns it to the PhoneHomeEnabled field.
func (o *Instance) SetPhoneHomeEnabled(v bool) {
	o.PhoneHomeEnabled = &v
}

// GetUserData returns the UserData field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *Instance) GetUserData() string {
	if o == nil || IsNil(o.UserData.Get()) {
		var ret string
		return ret
	}
	return *o.UserData.Get()
}

// GetUserDataOk returns a tuple with the UserData field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *Instance) GetUserDataOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.UserData.Get(), o.UserData.IsSet()
}

// HasUserData returns a boolean if a field has been set.
func (o *Instance) HasUserData() bool {
	if o != nil && o.UserData.IsSet() {
		return true
	}

	return false
}

// SetUserData gets a reference to the given NullableString and assigns it to the UserData field.
func (o *Instance) SetUserData(v string) {
	o.UserData.Set(&v)
}

// SetUserDataNil sets the value for UserData to be an explicit nil
func (o *Instance) SetUserDataNil() {
	o.UserData.Set(nil)
}

// UnsetUserData ensures that no value is present for UserData, not even an explicit nil
func (o *Instance) UnsetUserData() {
	o.UserData.Unset()
}

// GetLabels returns the Labels field value if set, zero value otherwise.
func (o *Instance) GetLabels() map[string]string {
	if o == nil || IsNil(o.Labels) {
		var ret map[string]string
		return ret
	}
	return o.Labels
}

// GetLabelsOk returns a tuple with the Labels field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Instance) GetLabelsOk() (map[string]string, bool) {
	if o == nil || IsNil(o.Labels) {
		return map[string]string{}, false
	}
	return o.Labels, true
}

// HasLabels returns a boolean if a field has been set.
func (o *Instance) HasLabels() bool {
	if o != nil && !IsNil(o.Labels) {
		return true
	}

	return false
}

// SetLabels gets a reference to the given map[string]string and assigns it to the Labels field.
func (o *Instance) SetLabels(v map[string]string) {
	o.Labels = v
}

// GetIsUpdatePending returns the IsUpdatePending field value if set, zero value otherwise.
func (o *Instance) GetIsUpdatePending() bool {
	if o == nil || IsNil(o.IsUpdatePending) {
		var ret bool
		return ret
	}
	return *o.IsUpdatePending
}

// GetIsUpdatePendingOk returns a tuple with the IsUpdatePending field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Instance) GetIsUpdatePendingOk() (*bool, bool) {
	if o == nil || IsNil(o.IsUpdatePending) {
		return nil, false
	}
	return o.IsUpdatePending, true
}

// HasIsUpdatePending returns a boolean if a field has been set.
func (o *Instance) HasIsUpdatePending() bool {
	if o != nil && !IsNil(o.IsUpdatePending) {
		return true
	}

	return false
}

// SetIsUpdatePending gets a reference to the given bool and assigns it to the IsUpdatePending field.
func (o *Instance) SetIsUpdatePending(v bool) {
	o.IsUpdatePending = &v
}

// GetSerialConsoleUrl returns the SerialConsoleUrl field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *Instance) GetSerialConsoleUrl() string {
	if o == nil || IsNil(o.SerialConsoleUrl.Get()) {
		var ret string
		return ret
	}
	return *o.SerialConsoleUrl.Get()
}

// GetSerialConsoleUrlOk returns a tuple with the SerialConsoleUrl field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *Instance) GetSerialConsoleUrlOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.SerialConsoleUrl.Get(), o.SerialConsoleUrl.IsSet()
}

// HasSerialConsoleUrl returns a boolean if a field has been set.
func (o *Instance) HasSerialConsoleUrl() bool {
	if o != nil && o.SerialConsoleUrl.IsSet() {
		return true
	}

	return false
}

// SetSerialConsoleUrl gets a reference to the given NullableString and assigns it to the SerialConsoleUrl field.
func (o *Instance) SetSerialConsoleUrl(v string) {
	o.SerialConsoleUrl.Set(&v)
}

// SetSerialConsoleUrlNil sets the value for SerialConsoleUrl to be an explicit nil
func (o *Instance) SetSerialConsoleUrlNil() {
	o.SerialConsoleUrl.Set(nil)
}

// UnsetSerialConsoleUrl ensures that no value is present for SerialConsoleUrl, not even an explicit nil
func (o *Instance) UnsetSerialConsoleUrl() {
	o.SerialConsoleUrl.Unset()
}

// GetAutoNetwork returns the AutoNetwork field value if set, zero value otherwise.
func (o *Instance) GetAutoNetwork() bool {
	if o == nil || IsNil(o.AutoNetwork) {
		var ret bool
		return ret
	}
	return *o.AutoNetwork
}

// GetAutoNetworkOk returns a tuple with the AutoNetwork field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Instance) GetAutoNetworkOk() (*bool, bool) {
	if o == nil || IsNil(o.AutoNetwork) {
		return nil, false
	}
	return o.AutoNetwork, true
}

// HasAutoNetwork returns a boolean if a field has been set.
func (o *Instance) HasAutoNetwork() bool {
	if o != nil && !IsNil(o.AutoNetwork) {
		return true
	}

	return false
}

// SetAutoNetwork gets a reference to the given bool and assigns it to the AutoNetwork field.
func (o *Instance) SetAutoNetwork(v bool) {
	o.AutoNetwork = &v
}

// GetInterfaces returns the Interfaces field value if set, zero value otherwise.
func (o *Instance) GetInterfaces() []Interface {
	if o == nil || IsNil(o.Interfaces) {
		var ret []Interface
		return ret
	}
	return o.Interfaces
}

// GetInterfacesOk returns a tuple with the Interfaces field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Instance) GetInterfacesOk() ([]Interface, bool) {
	if o == nil || IsNil(o.Interfaces) {
		return nil, false
	}
	return o.Interfaces, true
}

// HasInterfaces returns a boolean if a field has been set.
func (o *Instance) HasInterfaces() bool {
	if o != nil && !IsNil(o.Interfaces) {
		return true
	}

	return false
}

// SetInterfaces gets a reference to the given []Interface and assigns it to the Interfaces field.
func (o *Instance) SetInterfaces(v []Interface) {
	o.Interfaces = v
}

// GetInfinibandInterfaces returns the InfinibandInterfaces field value if set, zero value otherwise.
func (o *Instance) GetInfinibandInterfaces() []InfiniBandInterface {
	if o == nil || IsNil(o.InfinibandInterfaces) {
		var ret []InfiniBandInterface
		return ret
	}
	return o.InfinibandInterfaces
}

// GetInfinibandInterfacesOk returns a tuple with the InfinibandInterfaces field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Instance) GetInfinibandInterfacesOk() ([]InfiniBandInterface, bool) {
	if o == nil || IsNil(o.InfinibandInterfaces) {
		return nil, false
	}
	return o.InfinibandInterfaces, true
}

// HasInfinibandInterfaces returns a boolean if a field has been set.
func (o *Instance) HasInfinibandInterfaces() bool {
	if o != nil && !IsNil(o.InfinibandInterfaces) {
		return true
	}

	return false
}

// SetInfinibandInterfaces gets a reference to the given []InfiniBandInterface and assigns it to the InfinibandInterfaces field.
func (o *Instance) SetInfinibandInterfaces(v []InfiniBandInterface) {
	o.InfinibandInterfaces = v
}

// GetNvLinkInterfaces returns the NvLinkInterfaces field value if set, zero value otherwise.
func (o *Instance) GetNvLinkInterfaces() []NVLinkInterface {
	if o == nil || IsNil(o.NvLinkInterfaces) {
		var ret []NVLinkInterface
		return ret
	}
	return o.NvLinkInterfaces
}

// GetNvLinkInterfacesOk returns a tuple with the NvLinkInterfaces field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Instance) GetNvLinkInterfacesOk() ([]NVLinkInterface, bool) {
	if o == nil || IsNil(o.NvLinkInterfaces) {
		return nil, false
	}
	return o.NvLinkInterfaces, true
}

// HasNvLinkInterfaces returns a boolean if a field has been set.
func (o *Instance) HasNvLinkInterfaces() bool {
	if o != nil && !IsNil(o.NvLinkInterfaces) {
		return true
	}

	return false
}

// SetNvLinkInterfaces gets a reference to the given []NVLinkInterface and assigns it to the NvLinkInterfaces field.
func (o *Instance) SetNvLinkInterfaces(v []NVLinkInterface) {
	o.NvLinkInterfaces = v
}

// GetDpuExtensionServiceDeployments returns the DpuExtensionServiceDeployments field value if set, zero value otherwise.
func (o *Instance) GetDpuExtensionServiceDeployments() []DpuExtensionServiceDeployment {
	if o == nil || IsNil(o.DpuExtensionServiceDeployments) {
		var ret []DpuExtensionServiceDeployment
		return ret
	}
	return o.DpuExtensionServiceDeployments
}

// GetDpuExtensionServiceDeploymentsOk returns a tuple with the DpuExtensionServiceDeployments field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Instance) GetDpuExtensionServiceDeploymentsOk() ([]DpuExtensionServiceDeployment, bool) {
	if o == nil || IsNil(o.DpuExtensionServiceDeployments) {
		return nil, false
	}
	return o.DpuExtensionServiceDeployments, true
}

// HasDpuExtensionServiceDeployments returns a boolean if a field has been set.
func (o *Instance) HasDpuExtensionServiceDeployments() bool {
	if o != nil && !IsNil(o.DpuExtensionServiceDeployments) {
		return true
	}

	return false
}

// SetDpuExtensionServiceDeployments gets a reference to the given []DpuExtensionServiceDeployment and assigns it to the DpuExtensionServiceDeployments field.
func (o *Instance) SetDpuExtensionServiceDeployments(v []DpuExtensionServiceDeployment) {
	o.DpuExtensionServiceDeployments = v
}

// GetSshKeyGroupIds returns the SshKeyGroupIds field value if set, zero value otherwise.
func (o *Instance) GetSshKeyGroupIds() []string {
	if o == nil || IsNil(o.SshKeyGroupIds) {
		var ret []string
		return ret
	}
	return o.SshKeyGroupIds
}

// GetSshKeyGroupIdsOk returns a tuple with the SshKeyGroupIds field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Instance) GetSshKeyGroupIdsOk() ([]string, bool) {
	if o == nil || IsNil(o.SshKeyGroupIds) {
		return nil, false
	}
	return o.SshKeyGroupIds, true
}

// HasSshKeyGroupIds returns a boolean if a field has been set.
func (o *Instance) HasSshKeyGroupIds() bool {
	if o != nil && !IsNil(o.SshKeyGroupIds) {
		return true
	}

	return false
}

// SetSshKeyGroupIds gets a reference to the given []string and assigns it to the SshKeyGroupIds field.
func (o *Instance) SetSshKeyGroupIds(v []string) {
	o.SshKeyGroupIds = v
}

// GetSshKeyGroups returns the SshKeyGroups field value if set, zero value otherwise.
func (o *Instance) GetSshKeyGroups() []SshKeyGroup {
	if o == nil || IsNil(o.SshKeyGroups) {
		var ret []SshKeyGroup
		return ret
	}
	return o.SshKeyGroups
}

// GetSshKeyGroupsOk returns a tuple with the SshKeyGroups field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Instance) GetSshKeyGroupsOk() ([]SshKeyGroup, bool) {
	if o == nil || IsNil(o.SshKeyGroups) {
		return nil, false
	}
	return o.SshKeyGroups, true
}

// HasSshKeyGroups returns a boolean if a field has been set.
func (o *Instance) HasSshKeyGroups() bool {
	if o != nil && !IsNil(o.SshKeyGroups) {
		return true
	}

	return false
}

// SetSshKeyGroups gets a reference to the given []SshKeyGroup and assigns it to the SshKeyGroups field.
func (o *Instance) SetSshKeyGroups(v []SshKeyGroup) {
	o.SshKeyGroups = v
}

// GetTpmEkCertificate returns the TpmEkCertificate field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *Instance) GetTpmEkCertificate() string {
	if o == nil || IsNil(o.TpmEkCertificate.Get()) {
		var ret string
		return ret
	}
	return *o.TpmEkCertificate.Get()
}

// GetTpmEkCertificateOk returns a tuple with the TpmEkCertificate field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *Instance) GetTpmEkCertificateOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.TpmEkCertificate.Get(), o.TpmEkCertificate.IsSet()
}

// HasTpmEkCertificate returns a boolean if a field has been set.
func (o *Instance) HasTpmEkCertificate() bool {
	if o != nil && o.TpmEkCertificate.IsSet() {
		return true
	}

	return false
}

// SetTpmEkCertificate gets a reference to the given NullableString and assigns it to the TpmEkCertificate field.
func (o *Instance) SetTpmEkCertificate(v string) {
	o.TpmEkCertificate.Set(&v)
}

// SetTpmEkCertificateNil sets the value for TpmEkCertificate to be an explicit nil
func (o *Instance) SetTpmEkCertificateNil() {
	o.TpmEkCertificate.Set(nil)
}

// UnsetTpmEkCertificate ensures that no value is present for TpmEkCertificate, not even an explicit nil
func (o *Instance) UnsetTpmEkCertificate() {
	o.TpmEkCertificate.Unset()
}

// GetStatus returns the Status field value if set, zero value otherwise.
func (o *Instance) GetStatus() InstanceStatus {
	if o == nil || IsNil(o.Status) {
		var ret InstanceStatus
		return ret
	}
	return *o.Status
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Instance) GetStatusOk() (*InstanceStatus, bool) {
	if o == nil || IsNil(o.Status) {
		return nil, false
	}
	return o.Status, true
}

// HasStatus returns a boolean if a field has been set.
func (o *Instance) HasStatus() bool {
	if o != nil && !IsNil(o.Status) {
		return true
	}

	return false
}

// SetStatus gets a reference to the given InstanceStatus and assigns it to the Status field.
func (o *Instance) SetStatus(v InstanceStatus) {
	o.Status = &v
}

// GetStatusHistory returns the StatusHistory field value if set, zero value otherwise.
func (o *Instance) GetStatusHistory() []StatusDetail {
	if o == nil || IsNil(o.StatusHistory) {
		var ret []StatusDetail
		return ret
	}
	return o.StatusHistory
}

// GetStatusHistoryOk returns a tuple with the StatusHistory field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Instance) GetStatusHistoryOk() ([]StatusDetail, bool) {
	if o == nil || IsNil(o.StatusHistory) {
		return nil, false
	}
	return o.StatusHistory, true
}

// HasStatusHistory returns a boolean if a field has been set.
func (o *Instance) HasStatusHistory() bool {
	if o != nil && !IsNil(o.StatusHistory) {
		return true
	}

	return false
}

// SetStatusHistory gets a reference to the given []StatusDetail and assigns it to the StatusHistory field.
func (o *Instance) SetStatusHistory(v []StatusDetail) {
	o.StatusHistory = v
}

// GetDeprecations returns the Deprecations field value if set, zero value otherwise.
func (o *Instance) GetDeprecations() []Deprecation {
	if o == nil || IsNil(o.Deprecations) {
		var ret []Deprecation
		return ret
	}
	return o.Deprecations
}

// GetDeprecationsOk returns a tuple with the Deprecations field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Instance) GetDeprecationsOk() ([]Deprecation, bool) {
	if o == nil || IsNil(o.Deprecations) {
		return nil, false
	}
	return o.Deprecations, true
}

// HasDeprecations returns a boolean if a field has been set.
func (o *Instance) HasDeprecations() bool {
	if o != nil && !IsNil(o.Deprecations) {
		return true
	}

	return false
}

// SetDeprecations gets a reference to the given []Deprecation and assigns it to the Deprecations field.
func (o *Instance) SetDeprecations(v []Deprecation) {
	o.Deprecations = v
}

// GetCreated returns the Created field value if set, zero value otherwise.
func (o *Instance) GetCreated() time.Time {
	if o == nil || IsNil(o.Created) {
		var ret time.Time
		return ret
	}
	return *o.Created
}

// GetCreatedOk returns a tuple with the Created field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Instance) GetCreatedOk() (*time.Time, bool) {
	if o == nil || IsNil(o.Created) {
		return nil, false
	}
	return o.Created, true
}

// HasCreated returns a boolean if a field has been set.
func (o *Instance) HasCreated() bool {
	if o != nil && !IsNil(o.Created) {
		return true
	}

	return false
}

// SetCreated gets a reference to the given time.Time and assigns it to the Created field.
func (o *Instance) SetCreated(v time.Time) {
	o.Created = &v
}

// GetUpdated returns the Updated field value if set, zero value otherwise.
func (o *Instance) GetUpdated() time.Time {
	if o == nil || IsNil(o.Updated) {
		var ret time.Time
		return ret
	}
	return *o.Updated
}

// GetUpdatedOk returns a tuple with the Updated field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Instance) GetUpdatedOk() (*time.Time, bool) {
	if o == nil || IsNil(o.Updated) {
		return nil, false
	}
	return o.Updated, true
}

// HasUpdated returns a boolean if a field has been set.
func (o *Instance) HasUpdated() bool {
	if o != nil && !IsNil(o.Updated) {
		return true
	}

	return false
}

// SetUpdated gets a reference to the given time.Time and assigns it to the Updated field.
func (o *Instance) SetUpdated(v time.Time) {
	o.Updated = &v
}

func (o Instance) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o Instance) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if o.Description.IsSet() {
		toSerialize["description"] = o.Description.Get()
	}
	if !IsNil(o.TenantId) {
		toSerialize["tenantId"] = o.TenantId
	}
	if !IsNil(o.InfrastructureProviderId) {
		toSerialize["infrastructureProviderId"] = o.InfrastructureProviderId
	}
	if !IsNil(o.SiteId) {
		toSerialize["siteId"] = o.SiteId
	}
	if o.InstanceTypeId.IsSet() {
		toSerialize["instanceTypeId"] = o.InstanceTypeId.Get()
	}
	if !IsNil(o.VpcId) {
		toSerialize["vpcId"] = o.VpcId
	}
	if !IsNil(o.SecondaryVpcIds) {
		toSerialize["secondaryVpcIds"] = o.SecondaryVpcIds
	}
	if o.MachineId.IsSet() {
		toSerialize["machineId"] = o.MachineId.Get()
	}
	if o.OperatingSystemId.IsSet() {
		toSerialize["operatingSystemId"] = o.OperatingSystemId.Get()
	}
	if o.NetworkSecurityGroupId.IsSet() {
		toSerialize["networkSecurityGroupId"] = o.NetworkSecurityGroupId.Get()
	}
	if !IsNil(o.NetworkSecurityGroupPropagationDetails) {
		toSerialize["networkSecurityGroupPropagationDetails"] = o.NetworkSecurityGroupPropagationDetails
	}
	if !IsNil(o.NetworkSecurityGroupInherited) {
		toSerialize["networkSecurityGroupInherited"] = o.NetworkSecurityGroupInherited
	}
	if o.ControllerInstanceId.IsSet() {
		toSerialize["controllerInstanceId"] = o.ControllerInstanceId.Get()
	}
	if o.IpxeScript.IsSet() {
		toSerialize["ipxeScript"] = o.IpxeScript.Get()
	}
	if !IsNil(o.AlwaysBootWithCustomIpxe) {
		toSerialize["alwaysBootWithCustomIpxe"] = o.AlwaysBootWithCustomIpxe
	}
	if !IsNil(o.PhoneHomeEnabled) {
		toSerialize["phoneHomeEnabled"] = o.PhoneHomeEnabled
	}
	if o.UserData.IsSet() {
		toSerialize["userData"] = o.UserData.Get()
	}
	if !IsNil(o.Labels) {
		toSerialize["labels"] = o.Labels
	}
	if !IsNil(o.IsUpdatePending) {
		toSerialize["isUpdatePending"] = o.IsUpdatePending
	}
	if o.SerialConsoleUrl.IsSet() {
		toSerialize["serialConsoleUrl"] = o.SerialConsoleUrl.Get()
	}
	if !IsNil(o.AutoNetwork) {
		toSerialize["autoNetwork"] = o.AutoNetwork
	}
	if !IsNil(o.Interfaces) {
		toSerialize["interfaces"] = o.Interfaces
	}
	if !IsNil(o.InfinibandInterfaces) {
		toSerialize["infinibandInterfaces"] = o.InfinibandInterfaces
	}
	if !IsNil(o.NvLinkInterfaces) {
		toSerialize["nvLinkInterfaces"] = o.NvLinkInterfaces
	}
	if !IsNil(o.DpuExtensionServiceDeployments) {
		toSerialize["dpuExtensionServiceDeployments"] = o.DpuExtensionServiceDeployments
	}
	if !IsNil(o.SshKeyGroupIds) {
		toSerialize["sshKeyGroupIds"] = o.SshKeyGroupIds
	}
	if !IsNil(o.SshKeyGroups) {
		toSerialize["sshKeyGroups"] = o.SshKeyGroups
	}
	if o.TpmEkCertificate.IsSet() {
		toSerialize["tpmEkCertificate"] = o.TpmEkCertificate.Get()
	}
	if !IsNil(o.Status) {
		toSerialize["status"] = o.Status
	}
	if !IsNil(o.StatusHistory) {
		toSerialize["statusHistory"] = o.StatusHistory
	}
	if !IsNil(o.Deprecations) {
		toSerialize["deprecations"] = o.Deprecations
	}
	if !IsNil(o.Created) {
		toSerialize["created"] = o.Created
	}
	if !IsNil(o.Updated) {
		toSerialize["updated"] = o.Updated
	}
	return toSerialize, nil
}

type NullableInstance struct {
	value *Instance
	isSet bool
}

func (v NullableInstance) Get() *Instance {
	return v.value
}

func (v *NullableInstance) Set(val *Instance) {
	v.value = val
	v.isSet = true
}

func (v NullableInstance) IsSet() bool {
	return v.isSet
}

func (v *NullableInstance) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableInstance(val *Instance) *NullableInstance {
	return &NullableInstance{value: val, isSet: true}
}

func (v NullableInstance) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableInstance) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
