// SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
// SPDX-License-Identifier: Apache-2.0

/*
NVIDIA Infra Controller REST API

NVIDIA Infra Controller REST API allows users to create and manage resources, e.g., VPCs, Subnets, and Instances, across all connected NVIDIA Infra Controller datacenters, also referred to as Sites.

API version: 2.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package standard

import (
	"encoding/json"
)

// checks if the TenantCapabilities type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &TenantCapabilities{}

// TenantCapabilities Deprecated tenant-wide capability summary. TargetedInstanceCreation is no longer stored on the Tenant entity; it is configured on Tenant Account `siteCapabilities` (and may be overridden per Site via Tenant Site configuration).  On GET `/tenant/current`, `targetedInstanceCreation` is `true` when any Ready Tenant Account for the Tenant has the capability enabled. Embedded `TenantSummary.capabilities` in nested resources always reports `targetedInstanceCreation: false`.
type TenantCapabilities struct {
	// Deprecated in favor of TenantAccount.siteCapabilities. When returned on GET `/tenant/current`, indicates whether any Ready Tenant Account has TargetedInstanceCreation enabled. Always `false` on embedded TenantSummary objects.
	// Deprecated
	TargetedInstanceCreation *bool `json:"targetedInstanceCreation,omitempty"`
}

// NewTenantCapabilities instantiates a new TenantCapabilities object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTenantCapabilities() *TenantCapabilities {
	this := TenantCapabilities{}
	return &this
}

// NewTenantCapabilitiesWithDefaults instantiates a new TenantCapabilities object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTenantCapabilitiesWithDefaults() *TenantCapabilities {
	this := TenantCapabilities{}
	return &this
}

// GetTargetedInstanceCreation returns the TargetedInstanceCreation field value if set, zero value otherwise.
// Deprecated
func (o *TenantCapabilities) GetTargetedInstanceCreation() bool {
	if o == nil || IsNil(o.TargetedInstanceCreation) {
		var ret bool
		return ret
	}
	return *o.TargetedInstanceCreation
}

// GetTargetedInstanceCreationOk returns a tuple with the TargetedInstanceCreation field value if set, nil otherwise
// and a boolean to check if the value has been set.
// Deprecated
func (o *TenantCapabilities) GetTargetedInstanceCreationOk() (*bool, bool) {
	if o == nil || IsNil(o.TargetedInstanceCreation) {
		return nil, false
	}
	return o.TargetedInstanceCreation, true
}

// HasTargetedInstanceCreation returns a boolean if a field has been set.
func (o *TenantCapabilities) HasTargetedInstanceCreation() bool {
	if o != nil && !IsNil(o.TargetedInstanceCreation) {
		return true
	}

	return false
}

// SetTargetedInstanceCreation gets a reference to the given bool and assigns it to the TargetedInstanceCreation field.
// Deprecated
func (o *TenantCapabilities) SetTargetedInstanceCreation(v bool) {
	o.TargetedInstanceCreation = &v
}

func (o TenantCapabilities) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o TenantCapabilities) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.TargetedInstanceCreation) {
		toSerialize["targetedInstanceCreation"] = o.TargetedInstanceCreation
	}
	return toSerialize, nil
}

type NullableTenantCapabilities struct {
	value *TenantCapabilities
	isSet bool
}

func (v NullableTenantCapabilities) Get() *TenantCapabilities {
	return v.value
}

func (v *NullableTenantCapabilities) Set(val *TenantCapabilities) {
	v.value = val
	v.isSet = true
}

func (v NullableTenantCapabilities) IsSet() bool {
	return v.isSet
}

func (v *NullableTenantCapabilities) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTenantCapabilities(val *TenantCapabilities) *NullableTenantCapabilities {
	return &NullableTenantCapabilities{value: val, isSet: true}
}

func (v NullableTenantCapabilities) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTenantCapabilities) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
