// SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
// SPDX-License-Identifier: Apache-2.0

/*
NVIDIA Infra Controller REST API

NVIDIA Infra Controller REST API allows users to create and manage resources, e.g., VPCs, Subnets, and Instances, across all connected NVIDIA Infra Controller datacenters, also referred to as Sites.

API version: 2.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package standard

import (
	"encoding/json"
	"time"
)

// checks if the TenantAccount type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &TenantAccount{}

// TenantAccount Associates a Tenant with an Infrastructure Provider
type TenantAccount struct {
	// Unique UUID v4 identifier for the Tenant Account
	Id *string `json:"id,omitempty"`
	// ID of the Infrastructure Provider
	InfrastructureProviderId *string `json:"infrastructureProviderId,omitempty"`
	// Organization name of the Infrastructure Provider
	InfrastructureProviderOrg *string `json:"infrastructureProviderOrg,omitempty"`
	// ID of the Tenant
	TenantId NullableString `json:"tenantId,omitempty"`
	// Org of the Tenant
	TenantOrg NullableString `json:"tenantOrg,omitempty"`
	// Contact user for the Tenant
	TenantContact *User `json:"tenantContact,omitempty"`
	// Number of Allocations for the Tenant Account
	AllocationCount *int32 `json:"allocationCount,omitempty"`
	// Status of the Tenant Account
	Status *TenantAccountStatus `json:"status,omitempty"`
	// Chronological status history for the Tenant Account
	StatusHistory []StatusDetail `json:"statusHistory,omitempty"`
	// Deprecations active for this resource. Returned only if there are active deprecations.
	Deprecations []Deprecation `json:"deprecations,omitempty"`
	// Date/time when the Tenant Account was created
	Created *time.Time `json:"created,omitempty"`
	// Date/time when the Tenant Account was last updated
	Updated *time.Time `json:"updated,omitempty"`
	// Provider-scoped TargetedInstanceCreation settings for this Tenant Account
	SiteCapabilities []TenantAccountSiteCapability `json:"siteCapabilities,omitempty"`
}

// NewTenantAccount instantiates a new TenantAccount object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTenantAccount() *TenantAccount {
	this := TenantAccount{}
	return &this
}

// NewTenantAccountWithDefaults instantiates a new TenantAccount object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTenantAccountWithDefaults() *TenantAccount {
	this := TenantAccount{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *TenantAccount) GetId() string {
	if o == nil || IsNil(o.Id) {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TenantAccount) GetIdOk() (*string, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *TenantAccount) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *TenantAccount) SetId(v string) {
	o.Id = &v
}

// GetInfrastructureProviderId returns the InfrastructureProviderId field value if set, zero value otherwise.
func (o *TenantAccount) GetInfrastructureProviderId() string {
	if o == nil || IsNil(o.InfrastructureProviderId) {
		var ret string
		return ret
	}
	return *o.InfrastructureProviderId
}

// GetInfrastructureProviderIdOk returns a tuple with the InfrastructureProviderId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TenantAccount) GetInfrastructureProviderIdOk() (*string, bool) {
	if o == nil || IsNil(o.InfrastructureProviderId) {
		return nil, false
	}
	return o.InfrastructureProviderId, true
}

// HasInfrastructureProviderId returns a boolean if a field has been set.
func (o *TenantAccount) HasInfrastructureProviderId() bool {
	if o != nil && !IsNil(o.InfrastructureProviderId) {
		return true
	}

	return false
}

// SetInfrastructureProviderId gets a reference to the given string and assigns it to the InfrastructureProviderId field.
func (o *TenantAccount) SetInfrastructureProviderId(v string) {
	o.InfrastructureProviderId = &v
}

// GetInfrastructureProviderOrg returns the InfrastructureProviderOrg field value if set, zero value otherwise.
func (o *TenantAccount) GetInfrastructureProviderOrg() string {
	if o == nil || IsNil(o.InfrastructureProviderOrg) {
		var ret string
		return ret
	}
	return *o.InfrastructureProviderOrg
}

// GetInfrastructureProviderOrgOk returns a tuple with the InfrastructureProviderOrg field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TenantAccount) GetInfrastructureProviderOrgOk() (*string, bool) {
	if o == nil || IsNil(o.InfrastructureProviderOrg) {
		return nil, false
	}
	return o.InfrastructureProviderOrg, true
}

// HasInfrastructureProviderOrg returns a boolean if a field has been set.
func (o *TenantAccount) HasInfrastructureProviderOrg() bool {
	if o != nil && !IsNil(o.InfrastructureProviderOrg) {
		return true
	}

	return false
}

// SetInfrastructureProviderOrg gets a reference to the given string and assigns it to the InfrastructureProviderOrg field.
func (o *TenantAccount) SetInfrastructureProviderOrg(v string) {
	o.InfrastructureProviderOrg = &v
}

// GetTenantId returns the TenantId field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *TenantAccount) GetTenantId() string {
	if o == nil || IsNil(o.TenantId.Get()) {
		var ret string
		return ret
	}
	return *o.TenantId.Get()
}

// GetTenantIdOk returns a tuple with the TenantId field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *TenantAccount) GetTenantIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.TenantId.Get(), o.TenantId.IsSet()
}

// HasTenantId returns a boolean if a field has been set.
func (o *TenantAccount) HasTenantId() bool {
	if o != nil && o.TenantId.IsSet() {
		return true
	}

	return false
}

// SetTenantId gets a reference to the given NullableString and assigns it to the TenantId field.
func (o *TenantAccount) SetTenantId(v string) {
	o.TenantId.Set(&v)
}

// SetTenantIdNil sets the value for TenantId to be an explicit nil
func (o *TenantAccount) SetTenantIdNil() {
	o.TenantId.Set(nil)
}

// UnsetTenantId ensures that no value is present for TenantId, not even an explicit nil
func (o *TenantAccount) UnsetTenantId() {
	o.TenantId.Unset()
}

// GetTenantOrg returns the TenantOrg field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *TenantAccount) GetTenantOrg() string {
	if o == nil || IsNil(o.TenantOrg.Get()) {
		var ret string
		return ret
	}
	return *o.TenantOrg.Get()
}

// GetTenantOrgOk returns a tuple with the TenantOrg field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *TenantAccount) GetTenantOrgOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.TenantOrg.Get(), o.TenantOrg.IsSet()
}

// HasTenantOrg returns a boolean if a field has been set.
func (o *TenantAccount) HasTenantOrg() bool {
	if o != nil && o.TenantOrg.IsSet() {
		return true
	}

	return false
}

// SetTenantOrg gets a reference to the given NullableString and assigns it to the TenantOrg field.
func (o *TenantAccount) SetTenantOrg(v string) {
	o.TenantOrg.Set(&v)
}

// SetTenantOrgNil sets the value for TenantOrg to be an explicit nil
func (o *TenantAccount) SetTenantOrgNil() {
	o.TenantOrg.Set(nil)
}

// UnsetTenantOrg ensures that no value is present for TenantOrg, not even an explicit nil
func (o *TenantAccount) UnsetTenantOrg() {
	o.TenantOrg.Unset()
}

// GetTenantContact returns the TenantContact field value if set, zero value otherwise.
func (o *TenantAccount) GetTenantContact() User {
	if o == nil || IsNil(o.TenantContact) {
		var ret User
		return ret
	}
	return *o.TenantContact
}

// GetTenantContactOk returns a tuple with the TenantContact field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TenantAccount) GetTenantContactOk() (*User, bool) {
	if o == nil || IsNil(o.TenantContact) {
		return nil, false
	}
	return o.TenantContact, true
}

// HasTenantContact returns a boolean if a field has been set.
func (o *TenantAccount) HasTenantContact() bool {
	if o != nil && !IsNil(o.TenantContact) {
		return true
	}

	return false
}

// SetTenantContact gets a reference to the given User and assigns it to the TenantContact field.
func (o *TenantAccount) SetTenantContact(v User) {
	o.TenantContact = &v
}

// GetAllocationCount returns the AllocationCount field value if set, zero value otherwise.
func (o *TenantAccount) GetAllocationCount() int32 {
	if o == nil || IsNil(o.AllocationCount) {
		var ret int32
		return ret
	}
	return *o.AllocationCount
}

// GetAllocationCountOk returns a tuple with the AllocationCount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TenantAccount) GetAllocationCountOk() (*int32, bool) {
	if o == nil || IsNil(o.AllocationCount) {
		return nil, false
	}
	return o.AllocationCount, true
}

// HasAllocationCount returns a boolean if a field has been set.
func (o *TenantAccount) HasAllocationCount() bool {
	if o != nil && !IsNil(o.AllocationCount) {
		return true
	}

	return false
}

// SetAllocationCount gets a reference to the given int32 and assigns it to the AllocationCount field.
func (o *TenantAccount) SetAllocationCount(v int32) {
	o.AllocationCount = &v
}

// GetStatus returns the Status field value if set, zero value otherwise.
func (o *TenantAccount) GetStatus() TenantAccountStatus {
	if o == nil || IsNil(o.Status) {
		var ret TenantAccountStatus
		return ret
	}
	return *o.Status
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TenantAccount) GetStatusOk() (*TenantAccountStatus, bool) {
	if o == nil || IsNil(o.Status) {
		return nil, false
	}
	return o.Status, true
}

// HasStatus returns a boolean if a field has been set.
func (o *TenantAccount) HasStatus() bool {
	if o != nil && !IsNil(o.Status) {
		return true
	}

	return false
}

// SetStatus gets a reference to the given TenantAccountStatus and assigns it to the Status field.
func (o *TenantAccount) SetStatus(v TenantAccountStatus) {
	o.Status = &v
}

// GetStatusHistory returns the StatusHistory field value if set, zero value otherwise.
func (o *TenantAccount) GetStatusHistory() []StatusDetail {
	if o == nil || IsNil(o.StatusHistory) {
		var ret []StatusDetail
		return ret
	}
	return o.StatusHistory
}

// GetStatusHistoryOk returns a tuple with the StatusHistory field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TenantAccount) GetStatusHistoryOk() ([]StatusDetail, bool) {
	if o == nil || IsNil(o.StatusHistory) {
		return nil, false
	}
	return o.StatusHistory, true
}

// HasStatusHistory returns a boolean if a field has been set.
func (o *TenantAccount) HasStatusHistory() bool {
	if o != nil && !IsNil(o.StatusHistory) {
		return true
	}

	return false
}

// SetStatusHistory gets a reference to the given []StatusDetail and assigns it to the StatusHistory field.
func (o *TenantAccount) SetStatusHistory(v []StatusDetail) {
	o.StatusHistory = v
}

// GetDeprecations returns the Deprecations field value if set, zero value otherwise.
func (o *TenantAccount) GetDeprecations() []Deprecation {
	if o == nil || IsNil(o.Deprecations) {
		var ret []Deprecation
		return ret
	}
	return o.Deprecations
}

// GetDeprecationsOk returns a tuple with the Deprecations field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TenantAccount) GetDeprecationsOk() ([]Deprecation, bool) {
	if o == nil || IsNil(o.Deprecations) {
		return nil, false
	}
	return o.Deprecations, true
}

// HasDeprecations returns a boolean if a field has been set.
func (o *TenantAccount) HasDeprecations() bool {
	if o != nil && !IsNil(o.Deprecations) {
		return true
	}

	return false
}

// SetDeprecations gets a reference to the given []Deprecation and assigns it to the Deprecations field.
func (o *TenantAccount) SetDeprecations(v []Deprecation) {
	o.Deprecations = v
}

// GetCreated returns the Created field value if set, zero value otherwise.
func (o *TenantAccount) GetCreated() time.Time {
	if o == nil || IsNil(o.Created) {
		var ret time.Time
		return ret
	}
	return *o.Created
}

// GetCreatedOk returns a tuple with the Created field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TenantAccount) GetCreatedOk() (*time.Time, bool) {
	if o == nil || IsNil(o.Created) {
		return nil, false
	}
	return o.Created, true
}

// HasCreated returns a boolean if a field has been set.
func (o *TenantAccount) HasCreated() bool {
	if o != nil && !IsNil(o.Created) {
		return true
	}

	return false
}

// SetCreated gets a reference to the given time.Time and assigns it to the Created field.
func (o *TenantAccount) SetCreated(v time.Time) {
	o.Created = &v
}

// GetUpdated returns the Updated field value if set, zero value otherwise.
func (o *TenantAccount) GetUpdated() time.Time {
	if o == nil || IsNil(o.Updated) {
		var ret time.Time
		return ret
	}
	return *o.Updated
}

// GetUpdatedOk returns a tuple with the Updated field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TenantAccount) GetUpdatedOk() (*time.Time, bool) {
	if o == nil || IsNil(o.Updated) {
		return nil, false
	}
	return o.Updated, true
}

// HasUpdated returns a boolean if a field has been set.
func (o *TenantAccount) HasUpdated() bool {
	if o != nil && !IsNil(o.Updated) {
		return true
	}

	return false
}

// SetUpdated gets a reference to the given time.Time and assigns it to the Updated field.
func (o *TenantAccount) SetUpdated(v time.Time) {
	o.Updated = &v
}

// GetSiteCapabilities returns the SiteCapabilities field value if set, zero value otherwise.
func (o *TenantAccount) GetSiteCapabilities() []TenantAccountSiteCapability {
	if o == nil || IsNil(o.SiteCapabilities) {
		var ret []TenantAccountSiteCapability
		return ret
	}
	return o.SiteCapabilities
}

// GetSiteCapabilitiesOk returns a tuple with the SiteCapabilities field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TenantAccount) GetSiteCapabilitiesOk() ([]TenantAccountSiteCapability, bool) {
	if o == nil || IsNil(o.SiteCapabilities) {
		return nil, false
	}
	return o.SiteCapabilities, true
}

// HasSiteCapabilities returns a boolean if a field has been set.
func (o *TenantAccount) HasSiteCapabilities() bool {
	if o != nil && !IsNil(o.SiteCapabilities) {
		return true
	}

	return false
}

// SetSiteCapabilities gets a reference to the given []TenantAccountSiteCapability and assigns it to the SiteCapabilities field.
func (o *TenantAccount) SetSiteCapabilities(v []TenantAccountSiteCapability) {
	o.SiteCapabilities = v
}

func (o TenantAccount) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o TenantAccount) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.InfrastructureProviderId) {
		toSerialize["infrastructureProviderId"] = o.InfrastructureProviderId
	}
	if !IsNil(o.InfrastructureProviderOrg) {
		toSerialize["infrastructureProviderOrg"] = o.InfrastructureProviderOrg
	}
	if o.TenantId.IsSet() {
		toSerialize["tenantId"] = o.TenantId.Get()
	}
	if o.TenantOrg.IsSet() {
		toSerialize["tenantOrg"] = o.TenantOrg.Get()
	}
	if !IsNil(o.TenantContact) {
		toSerialize["tenantContact"] = o.TenantContact
	}
	if !IsNil(o.AllocationCount) {
		toSerialize["allocationCount"] = o.AllocationCount
	}
	if !IsNil(o.Status) {
		toSerialize["status"] = o.Status
	}
	if !IsNil(o.StatusHistory) {
		toSerialize["statusHistory"] = o.StatusHistory
	}
	if !IsNil(o.Deprecations) {
		toSerialize["deprecations"] = o.Deprecations
	}
	if !IsNil(o.Created) {
		toSerialize["created"] = o.Created
	}
	if !IsNil(o.Updated) {
		toSerialize["updated"] = o.Updated
	}
	if !IsNil(o.SiteCapabilities) {
		toSerialize["siteCapabilities"] = o.SiteCapabilities
	}
	return toSerialize, nil
}

type NullableTenantAccount struct {
	value *TenantAccount
	isSet bool
}

func (v NullableTenantAccount) Get() *TenantAccount {
	return v.value
}

func (v *NullableTenantAccount) Set(val *TenantAccount) {
	v.value = val
	v.isSet = true
}

func (v NullableTenantAccount) IsSet() bool {
	return v.isSet
}

func (v *NullableTenantAccount) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTenantAccount(val *TenantAccount) *NullableTenantAccount {
	return &NullableTenantAccount{value: val, isSet: true}
}

func (v NullableTenantAccount) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTenantAccount) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
