// SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
// SPDX-License-Identifier: Apache-2.0

/*
NVIDIA Infra Controller REST API

NVIDIA Infra Controller REST API allows users to create and manage resources, e.g., VPCs, Subnets, and Instances, across all connected NVIDIA Infra Controller datacenters, also referred to as Sites.

API version: 2.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package standard

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the ExpectedRackCreateRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ExpectedRackCreateRequest{}

// ExpectedRackCreateRequest Request data to create a new Expected Rack.  The `rackId` is an operator-supplied string identifier (not a UUID) that must be unique within the Site. Chassis identity and physical location information are conveyed via well-known label keys in `labels`: - `chassis.manufacturer`, `chassis.serial-number`, `chassis.model` - `location.region`, `location.datacenter`, `location.room`, `location.position`
type ExpectedRackCreateRequest struct {
	// ID of the Site the Expected Rack belongs to
	SiteId string `json:"siteId"`
	// Operator-supplied identifier for the rack (string, not UUID). Must be non-empty and unique within the Site.
	RackId string `json:"rackId"`
	// Identifier of the Rack Profile this rack conforms to. Must be non-empty.
	RackProfileId string `json:"rackProfileId"`
	// Human-readable name of the Expected Rack
	Name NullableString `json:"name,omitempty"`
	// Human-readable description of the Expected Rack
	Description NullableString `json:"description,omitempty"`
	// User-defined key-value pairs for organizing and categorizing Expected Racks. Well-known keys (`chassis.*`, `location.*`) are used to convey chassis identity and physical location.
	Labels map[string]string `json:"labels,omitempty"`
}

type _ExpectedRackCreateRequest ExpectedRackCreateRequest

// NewExpectedRackCreateRequest instantiates a new ExpectedRackCreateRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewExpectedRackCreateRequest(siteId string, rackId string, rackProfileId string) *ExpectedRackCreateRequest {
	this := ExpectedRackCreateRequest{}
	this.SiteId = siteId
	this.RackId = rackId
	this.RackProfileId = rackProfileId
	return &this
}

// NewExpectedRackCreateRequestWithDefaults instantiates a new ExpectedRackCreateRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewExpectedRackCreateRequestWithDefaults() *ExpectedRackCreateRequest {
	this := ExpectedRackCreateRequest{}
	return &this
}

// GetSiteId returns the SiteId field value
func (o *ExpectedRackCreateRequest) GetSiteId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.SiteId
}

// GetSiteIdOk returns a tuple with the SiteId field value
// and a boolean to check if the value has been set.
func (o *ExpectedRackCreateRequest) GetSiteIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.SiteId, true
}

// SetSiteId sets field value
func (o *ExpectedRackCreateRequest) SetSiteId(v string) {
	o.SiteId = v
}

// GetRackId returns the RackId field value
func (o *ExpectedRackCreateRequest) GetRackId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.RackId
}

// GetRackIdOk returns a tuple with the RackId field value
// and a boolean to check if the value has been set.
func (o *ExpectedRackCreateRequest) GetRackIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.RackId, true
}

// SetRackId sets field value
func (o *ExpectedRackCreateRequest) SetRackId(v string) {
	o.RackId = v
}

// GetRackProfileId returns the RackProfileId field value
func (o *ExpectedRackCreateRequest) GetRackProfileId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.RackProfileId
}

// GetRackProfileIdOk returns a tuple with the RackProfileId field value
// and a boolean to check if the value has been set.
func (o *ExpectedRackCreateRequest) GetRackProfileIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.RackProfileId, true
}

// SetRackProfileId sets field value
func (o *ExpectedRackCreateRequest) SetRackProfileId(v string) {
	o.RackProfileId = v
}

// GetName returns the Name field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ExpectedRackCreateRequest) GetName() string {
	if o == nil || IsNil(o.Name.Get()) {
		var ret string
		return ret
	}
	return *o.Name.Get()
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ExpectedRackCreateRequest) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Name.Get(), o.Name.IsSet()
}

// HasName returns a boolean if a field has been set.
func (o *ExpectedRackCreateRequest) HasName() bool {
	if o != nil && o.Name.IsSet() {
		return true
	}

	return false
}

// SetName gets a reference to the given NullableString and assigns it to the Name field.
func (o *ExpectedRackCreateRequest) SetName(v string) {
	o.Name.Set(&v)
}

// SetNameNil sets the value for Name to be an explicit nil
func (o *ExpectedRackCreateRequest) SetNameNil() {
	o.Name.Set(nil)
}

// UnsetName ensures that no value is present for Name, not even an explicit nil
func (o *ExpectedRackCreateRequest) UnsetName() {
	o.Name.Unset()
}

// GetDescription returns the Description field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ExpectedRackCreateRequest) GetDescription() string {
	if o == nil || IsNil(o.Description.Get()) {
		var ret string
		return ret
	}
	return *o.Description.Get()
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ExpectedRackCreateRequest) GetDescriptionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Description.Get(), o.Description.IsSet()
}

// HasDescription returns a boolean if a field has been set.
func (o *ExpectedRackCreateRequest) HasDescription() bool {
	if o != nil && o.Description.IsSet() {
		return true
	}

	return false
}

// SetDescription gets a reference to the given NullableString and assigns it to the Description field.
func (o *ExpectedRackCreateRequest) SetDescription(v string) {
	o.Description.Set(&v)
}

// SetDescriptionNil sets the value for Description to be an explicit nil
func (o *ExpectedRackCreateRequest) SetDescriptionNil() {
	o.Description.Set(nil)
}

// UnsetDescription ensures that no value is present for Description, not even an explicit nil
func (o *ExpectedRackCreateRequest) UnsetDescription() {
	o.Description.Unset()
}

// GetLabels returns the Labels field value if set, zero value otherwise.
func (o *ExpectedRackCreateRequest) GetLabels() map[string]string {
	if o == nil || IsNil(o.Labels) {
		var ret map[string]string
		return ret
	}
	return o.Labels
}

// GetLabelsOk returns a tuple with the Labels field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ExpectedRackCreateRequest) GetLabelsOk() (map[string]string, bool) {
	if o == nil || IsNil(o.Labels) {
		return map[string]string{}, false
	}
	return o.Labels, true
}

// HasLabels returns a boolean if a field has been set.
func (o *ExpectedRackCreateRequest) HasLabels() bool {
	if o != nil && !IsNil(o.Labels) {
		return true
	}

	return false
}

// SetLabels gets a reference to the given map[string]string and assigns it to the Labels field.
func (o *ExpectedRackCreateRequest) SetLabels(v map[string]string) {
	o.Labels = v
}

func (o ExpectedRackCreateRequest) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ExpectedRackCreateRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["siteId"] = o.SiteId
	toSerialize["rackId"] = o.RackId
	toSerialize["rackProfileId"] = o.RackProfileId
	if o.Name.IsSet() {
		toSerialize["name"] = o.Name.Get()
	}
	if o.Description.IsSet() {
		toSerialize["description"] = o.Description.Get()
	}
	if !IsNil(o.Labels) {
		toSerialize["labels"] = o.Labels
	}
	return toSerialize, nil
}

func (o *ExpectedRackCreateRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"siteId",
		"rackId",
		"rackProfileId",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if value, exists := allProperties[requiredProperty]; !exists || value == nil {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varExpectedRackCreateRequest := _ExpectedRackCreateRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varExpectedRackCreateRequest)

	if err != nil {
		return err
	}

	*o = ExpectedRackCreateRequest(varExpectedRackCreateRequest)

	return err
}

type NullableExpectedRackCreateRequest struct {
	value *ExpectedRackCreateRequest
	isSet bool
}

func (v NullableExpectedRackCreateRequest) Get() *ExpectedRackCreateRequest {
	return v.value
}

func (v *NullableExpectedRackCreateRequest) Set(val *ExpectedRackCreateRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableExpectedRackCreateRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableExpectedRackCreateRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableExpectedRackCreateRequest(val *ExpectedRackCreateRequest) *NullableExpectedRackCreateRequest {
	return &NullableExpectedRackCreateRequest{value: val, isSet: true}
}

func (v NullableExpectedRackCreateRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableExpectedRackCreateRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
