// SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
// SPDX-License-Identifier: Apache-2.0

/*
NVIDIA Infra Controller REST API

NVIDIA Infra Controller REST API allows users to create and manage resources, e.g., VPCs, Subnets, and Instances, across all connected NVIDIA Infra Controller datacenters, also referred to as Sites.

API version: 2.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package standard

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the MachinePowerControlRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &MachinePowerControlRequest{}

// MachinePowerControlRequest Request to power control a Machine
type MachinePowerControlRequest struct {
	// Redfish power control action to apply to the Machine. ACPowercycle is not supported on Viking systems.
	Action string `json:"action"`
	// Acknowledges that an Instance is currently attached to the Machine and this action may disrupt Tenant workload on the Instance.
	AcknowledgeAttachedInstance *bool `json:"acknowledgeAttachedInstance,omitempty"`
}

type _MachinePowerControlRequest MachinePowerControlRequest

// NewMachinePowerControlRequest instantiates a new MachinePowerControlRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewMachinePowerControlRequest(action string) *MachinePowerControlRequest {
	this := MachinePowerControlRequest{}
	this.Action = action
	return &this
}

// NewMachinePowerControlRequestWithDefaults instantiates a new MachinePowerControlRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewMachinePowerControlRequestWithDefaults() *MachinePowerControlRequest {
	this := MachinePowerControlRequest{}
	return &this
}

// GetAction returns the Action field value
func (o *MachinePowerControlRequest) GetAction() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Action
}

// GetActionOk returns a tuple with the Action field value
// and a boolean to check if the value has been set.
func (o *MachinePowerControlRequest) GetActionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Action, true
}

// SetAction sets field value
func (o *MachinePowerControlRequest) SetAction(v string) {
	o.Action = v
}

// GetAcknowledgeAttachedInstance returns the AcknowledgeAttachedInstance field value if set, zero value otherwise.
func (o *MachinePowerControlRequest) GetAcknowledgeAttachedInstance() bool {
	if o == nil || IsNil(o.AcknowledgeAttachedInstance) {
		var ret bool
		return ret
	}
	return *o.AcknowledgeAttachedInstance
}

// GetAcknowledgeAttachedInstanceOk returns a tuple with the AcknowledgeAttachedInstance field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MachinePowerControlRequest) GetAcknowledgeAttachedInstanceOk() (*bool, bool) {
	if o == nil || IsNil(o.AcknowledgeAttachedInstance) {
		return nil, false
	}
	return o.AcknowledgeAttachedInstance, true
}

// HasAcknowledgeAttachedInstance returns a boolean if a field has been set.
func (o *MachinePowerControlRequest) HasAcknowledgeAttachedInstance() bool {
	if o != nil && !IsNil(o.AcknowledgeAttachedInstance) {
		return true
	}

	return false
}

// SetAcknowledgeAttachedInstance gets a reference to the given bool and assigns it to the AcknowledgeAttachedInstance field.
func (o *MachinePowerControlRequest) SetAcknowledgeAttachedInstance(v bool) {
	o.AcknowledgeAttachedInstance = &v
}

func (o MachinePowerControlRequest) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o MachinePowerControlRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["action"] = o.Action
	if !IsNil(o.AcknowledgeAttachedInstance) {
		toSerialize["acknowledgeAttachedInstance"] = o.AcknowledgeAttachedInstance
	}
	return toSerialize, nil
}

func (o *MachinePowerControlRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"action",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if value, exists := allProperties[requiredProperty]; !exists || value == nil {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varMachinePowerControlRequest := _MachinePowerControlRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varMachinePowerControlRequest)

	if err != nil {
		return err
	}

	*o = MachinePowerControlRequest(varMachinePowerControlRequest)

	return err
}

type NullableMachinePowerControlRequest struct {
	value *MachinePowerControlRequest
	isSet bool
}

func (v NullableMachinePowerControlRequest) Get() *MachinePowerControlRequest {
	return v.value
}

func (v *NullableMachinePowerControlRequest) Set(val *MachinePowerControlRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableMachinePowerControlRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableMachinePowerControlRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableMachinePowerControlRequest(val *MachinePowerControlRequest) *NullableMachinePowerControlRequest {
	return &NullableMachinePowerControlRequest{value: val, isSet: true}
}

func (v NullableMachinePowerControlRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableMachinePowerControlRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
