// SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
// SPDX-License-Identifier: Apache-2.0

/*
NVIDIA Infra Controller REST API

NVIDIA Infra Controller REST API allows users to create and manage resources, e.g., VPCs, Subnets, and Instances, across all connected NVIDIA Infra Controller datacenters, also referred to as Sites.

API version: 2.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package standard

import (
	"encoding/json"
)

// checks if the NetworkSecurityGroupUpdateRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &NetworkSecurityGroupUpdateRequest{}

// NetworkSecurityGroupUpdateRequest Request data to update a Network Security Group
type NetworkSecurityGroupUpdateRequest struct {
	// Name of the Network Security Group
	Name NullableString `json:"name,omitempty"`
	// Description of the Network Security Group
	Description NullableString `json:"description,omitempty"`
	// Egress rules with protocol and destination ports defined but without source ports defined should automatically be made stateful.
	StatefulEgress *bool `json:"statefulEgress,omitempty"`
	// Update rules of the Network Security Group. The rules will be replaced with the rules sent in the request. Any rules not included in the request will be removed. To retain existing rules, fetch them first and include them.
	Rules []NetworkSecurityGroupRule `json:"rules,omitempty"`
	// User-defined key-value labels for the Network Security Group
	Labels map[string]string `json:"labels,omitempty"`
}

// NewNetworkSecurityGroupUpdateRequest instantiates a new NetworkSecurityGroupUpdateRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewNetworkSecurityGroupUpdateRequest() *NetworkSecurityGroupUpdateRequest {
	this := NetworkSecurityGroupUpdateRequest{}
	return &this
}

// NewNetworkSecurityGroupUpdateRequestWithDefaults instantiates a new NetworkSecurityGroupUpdateRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewNetworkSecurityGroupUpdateRequestWithDefaults() *NetworkSecurityGroupUpdateRequest {
	this := NetworkSecurityGroupUpdateRequest{}
	return &this
}

// GetName returns the Name field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *NetworkSecurityGroupUpdateRequest) GetName() string {
	if o == nil || IsNil(o.Name.Get()) {
		var ret string
		return ret
	}
	return *o.Name.Get()
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *NetworkSecurityGroupUpdateRequest) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Name.Get(), o.Name.IsSet()
}

// HasName returns a boolean if a field has been set.
func (o *NetworkSecurityGroupUpdateRequest) HasName() bool {
	if o != nil && o.Name.IsSet() {
		return true
	}

	return false
}

// SetName gets a reference to the given NullableString and assigns it to the Name field.
func (o *NetworkSecurityGroupUpdateRequest) SetName(v string) {
	o.Name.Set(&v)
}

// SetNameNil sets the value for Name to be an explicit nil
func (o *NetworkSecurityGroupUpdateRequest) SetNameNil() {
	o.Name.Set(nil)
}

// UnsetName ensures that no value is present for Name, not even an explicit nil
func (o *NetworkSecurityGroupUpdateRequest) UnsetName() {
	o.Name.Unset()
}

// GetDescription returns the Description field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *NetworkSecurityGroupUpdateRequest) GetDescription() string {
	if o == nil || IsNil(o.Description.Get()) {
		var ret string
		return ret
	}
	return *o.Description.Get()
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *NetworkSecurityGroupUpdateRequest) GetDescriptionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Description.Get(), o.Description.IsSet()
}

// HasDescription returns a boolean if a field has been set.
func (o *NetworkSecurityGroupUpdateRequest) HasDescription() bool {
	if o != nil && o.Description.IsSet() {
		return true
	}

	return false
}

// SetDescription gets a reference to the given NullableString and assigns it to the Description field.
func (o *NetworkSecurityGroupUpdateRequest) SetDescription(v string) {
	o.Description.Set(&v)
}

// SetDescriptionNil sets the value for Description to be an explicit nil
func (o *NetworkSecurityGroupUpdateRequest) SetDescriptionNil() {
	o.Description.Set(nil)
}

// UnsetDescription ensures that no value is present for Description, not even an explicit nil
func (o *NetworkSecurityGroupUpdateRequest) UnsetDescription() {
	o.Description.Unset()
}

// GetStatefulEgress returns the StatefulEgress field value if set, zero value otherwise.
func (o *NetworkSecurityGroupUpdateRequest) GetStatefulEgress() bool {
	if o == nil || IsNil(o.StatefulEgress) {
		var ret bool
		return ret
	}
	return *o.StatefulEgress
}

// GetStatefulEgressOk returns a tuple with the StatefulEgress field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *NetworkSecurityGroupUpdateRequest) GetStatefulEgressOk() (*bool, bool) {
	if o == nil || IsNil(o.StatefulEgress) {
		return nil, false
	}
	return o.StatefulEgress, true
}

// HasStatefulEgress returns a boolean if a field has been set.
func (o *NetworkSecurityGroupUpdateRequest) HasStatefulEgress() bool {
	if o != nil && !IsNil(o.StatefulEgress) {
		return true
	}

	return false
}

// SetStatefulEgress gets a reference to the given bool and assigns it to the StatefulEgress field.
func (o *NetworkSecurityGroupUpdateRequest) SetStatefulEgress(v bool) {
	o.StatefulEgress = &v
}

// GetRules returns the Rules field value if set, zero value otherwise.
func (o *NetworkSecurityGroupUpdateRequest) GetRules() []NetworkSecurityGroupRule {
	if o == nil || IsNil(o.Rules) {
		var ret []NetworkSecurityGroupRule
		return ret
	}
	return o.Rules
}

// GetRulesOk returns a tuple with the Rules field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *NetworkSecurityGroupUpdateRequest) GetRulesOk() ([]NetworkSecurityGroupRule, bool) {
	if o == nil || IsNil(o.Rules) {
		return nil, false
	}
	return o.Rules, true
}

// HasRules returns a boolean if a field has been set.
func (o *NetworkSecurityGroupUpdateRequest) HasRules() bool {
	if o != nil && !IsNil(o.Rules) {
		return true
	}

	return false
}

// SetRules gets a reference to the given []NetworkSecurityGroupRule and assigns it to the Rules field.
func (o *NetworkSecurityGroupUpdateRequest) SetRules(v []NetworkSecurityGroupRule) {
	o.Rules = v
}

// GetLabels returns the Labels field value if set, zero value otherwise.
func (o *NetworkSecurityGroupUpdateRequest) GetLabels() map[string]string {
	if o == nil || IsNil(o.Labels) {
		var ret map[string]string
		return ret
	}
	return o.Labels
}

// GetLabelsOk returns a tuple with the Labels field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *NetworkSecurityGroupUpdateRequest) GetLabelsOk() (map[string]string, bool) {
	if o == nil || IsNil(o.Labels) {
		return map[string]string{}, false
	}
	return o.Labels, true
}

// HasLabels returns a boolean if a field has been set.
func (o *NetworkSecurityGroupUpdateRequest) HasLabels() bool {
	if o != nil && !IsNil(o.Labels) {
		return true
	}

	return false
}

// SetLabels gets a reference to the given map[string]string and assigns it to the Labels field.
func (o *NetworkSecurityGroupUpdateRequest) SetLabels(v map[string]string) {
	o.Labels = v
}

func (o NetworkSecurityGroupUpdateRequest) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o NetworkSecurityGroupUpdateRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.Name.IsSet() {
		toSerialize["name"] = o.Name.Get()
	}
	if o.Description.IsSet() {
		toSerialize["description"] = o.Description.Get()
	}
	if !IsNil(o.StatefulEgress) {
		toSerialize["statefulEgress"] = o.StatefulEgress
	}
	if !IsNil(o.Rules) {
		toSerialize["rules"] = o.Rules
	}
	if !IsNil(o.Labels) {
		toSerialize["labels"] = o.Labels
	}
	return toSerialize, nil
}

type NullableNetworkSecurityGroupUpdateRequest struct {
	value *NetworkSecurityGroupUpdateRequest
	isSet bool
}

func (v NullableNetworkSecurityGroupUpdateRequest) Get() *NetworkSecurityGroupUpdateRequest {
	return v.value
}

func (v *NullableNetworkSecurityGroupUpdateRequest) Set(val *NetworkSecurityGroupUpdateRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableNetworkSecurityGroupUpdateRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableNetworkSecurityGroupUpdateRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableNetworkSecurityGroupUpdateRequest(val *NetworkSecurityGroupUpdateRequest) *NullableNetworkSecurityGroupUpdateRequest {
	return &NullableNetworkSecurityGroupUpdateRequest{value: val, isSet: true}
}

func (v NullableNetworkSecurityGroupUpdateRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableNetworkSecurityGroupUpdateRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
