// SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
// SPDX-License-Identifier: Apache-2.0

/*
NVIDIA Infra Controller REST API

NVIDIA Infra Controller REST API allows users to create and manage resources, e.g., VPCs, Subnets, and Instances, across all connected NVIDIA Infra Controller datacenters, also referred to as Sites.

API version: 2.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package standard

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the VpcCreateRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &VpcCreateRequest{}

// VpcCreateRequest Request data to create a VPC
type VpcCreateRequest struct {
	// Optional user-specified UUID for the VPC
	Id *string `json:"id,omitempty"`
	// Name of the VPC
	Name string `json:"name"`
	// Optional description for the VPC
	Description NullableString `json:"description,omitempty"`
	// ID of the Site where the VPC should be created
	SiteId string `json:"siteId"`
	// Network virtualization type of the VPC. If no value is specified, then defaults to `FNN` if Site has native networking enabled, or `ETHERNET_VIRTUALIZER` if native networking is disabled. Flat VPCs hold instances on zero-DPU hosts (or hosts with their DPU in NIC mode) and are never auto-selected -- `FLAT` must be specified explicitly.
	NetworkVirtualizationType NullableString `json:"networkVirtualizationType,omitempty"`
	// Specify routing profile for the VPC. Only supported when `networkVirtualizationType` is set to `FNN`, or when `networkVirtualizationType` is omitted and Site has Native Networking enabled. Requires Tenant to have elevated privilege. Current accepted values are `privileged-internal`, `internal`, and `external`.
	RoutingProfile NullableString `json:"routingProfile,omitempty"`
	// ID of the Network Security Group to attach to the VPC
	NetworkSecurityGroupId NullableString `json:"networkSecurityGroupId,omitempty"`
	// Explicitly requested VNI for the VPC
	Vni NullableInt32 `json:"vni,omitempty"`
	// ID of the default NVLink Logical Partition that GPUs for all Instances in the VPC will attach to
	NvLinkLogicalPartitionId NullableString `json:"nvLinkLogicalPartitionId,omitempty"`
	// String key-value pairs describing VPC labels. Up to 10 key-value pairs can be specified
	Labels map[string]string `json:"labels,omitempty"`
}

type _VpcCreateRequest VpcCreateRequest

// NewVpcCreateRequest instantiates a new VpcCreateRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewVpcCreateRequest(name string, siteId string) *VpcCreateRequest {
	this := VpcCreateRequest{}
	this.Name = name
	this.SiteId = siteId
	return &this
}

// NewVpcCreateRequestWithDefaults instantiates a new VpcCreateRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewVpcCreateRequestWithDefaults() *VpcCreateRequest {
	this := VpcCreateRequest{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *VpcCreateRequest) GetId() string {
	if o == nil || IsNil(o.Id) {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *VpcCreateRequest) GetIdOk() (*string, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *VpcCreateRequest) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *VpcCreateRequest) SetId(v string) {
	o.Id = &v
}

// GetName returns the Name field value
func (o *VpcCreateRequest) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *VpcCreateRequest) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *VpcCreateRequest) SetName(v string) {
	o.Name = v
}

// GetDescription returns the Description field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *VpcCreateRequest) GetDescription() string {
	if o == nil || IsNil(o.Description.Get()) {
		var ret string
		return ret
	}
	return *o.Description.Get()
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *VpcCreateRequest) GetDescriptionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Description.Get(), o.Description.IsSet()
}

// HasDescription returns a boolean if a field has been set.
func (o *VpcCreateRequest) HasDescription() bool {
	if o != nil && o.Description.IsSet() {
		return true
	}

	return false
}

// SetDescription gets a reference to the given NullableString and assigns it to the Description field.
func (o *VpcCreateRequest) SetDescription(v string) {
	o.Description.Set(&v)
}

// SetDescriptionNil sets the value for Description to be an explicit nil
func (o *VpcCreateRequest) SetDescriptionNil() {
	o.Description.Set(nil)
}

// UnsetDescription ensures that no value is present for Description, not even an explicit nil
func (o *VpcCreateRequest) UnsetDescription() {
	o.Description.Unset()
}

// GetSiteId returns the SiteId field value
func (o *VpcCreateRequest) GetSiteId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.SiteId
}

// GetSiteIdOk returns a tuple with the SiteId field value
// and a boolean to check if the value has been set.
func (o *VpcCreateRequest) GetSiteIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.SiteId, true
}

// SetSiteId sets field value
func (o *VpcCreateRequest) SetSiteId(v string) {
	o.SiteId = v
}

// GetNetworkVirtualizationType returns the NetworkVirtualizationType field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *VpcCreateRequest) GetNetworkVirtualizationType() string {
	if o == nil || IsNil(o.NetworkVirtualizationType.Get()) {
		var ret string
		return ret
	}
	return *o.NetworkVirtualizationType.Get()
}

// GetNetworkVirtualizationTypeOk returns a tuple with the NetworkVirtualizationType field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *VpcCreateRequest) GetNetworkVirtualizationTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.NetworkVirtualizationType.Get(), o.NetworkVirtualizationType.IsSet()
}

// HasNetworkVirtualizationType returns a boolean if a field has been set.
func (o *VpcCreateRequest) HasNetworkVirtualizationType() bool {
	if o != nil && o.NetworkVirtualizationType.IsSet() {
		return true
	}

	return false
}

// SetNetworkVirtualizationType gets a reference to the given NullableString and assigns it to the NetworkVirtualizationType field.
func (o *VpcCreateRequest) SetNetworkVirtualizationType(v string) {
	o.NetworkVirtualizationType.Set(&v)
}

// SetNetworkVirtualizationTypeNil sets the value for NetworkVirtualizationType to be an explicit nil
func (o *VpcCreateRequest) SetNetworkVirtualizationTypeNil() {
	o.NetworkVirtualizationType.Set(nil)
}

// UnsetNetworkVirtualizationType ensures that no value is present for NetworkVirtualizationType, not even an explicit nil
func (o *VpcCreateRequest) UnsetNetworkVirtualizationType() {
	o.NetworkVirtualizationType.Unset()
}

// GetRoutingProfile returns the RoutingProfile field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *VpcCreateRequest) GetRoutingProfile() string {
	if o == nil || IsNil(o.RoutingProfile.Get()) {
		var ret string
		return ret
	}
	return *o.RoutingProfile.Get()
}

// GetRoutingProfileOk returns a tuple with the RoutingProfile field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *VpcCreateRequest) GetRoutingProfileOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.RoutingProfile.Get(), o.RoutingProfile.IsSet()
}

// HasRoutingProfile returns a boolean if a field has been set.
func (o *VpcCreateRequest) HasRoutingProfile() bool {
	if o != nil && o.RoutingProfile.IsSet() {
		return true
	}

	return false
}

// SetRoutingProfile gets a reference to the given NullableString and assigns it to the RoutingProfile field.
func (o *VpcCreateRequest) SetRoutingProfile(v string) {
	o.RoutingProfile.Set(&v)
}

// SetRoutingProfileNil sets the value for RoutingProfile to be an explicit nil
func (o *VpcCreateRequest) SetRoutingProfileNil() {
	o.RoutingProfile.Set(nil)
}

// UnsetRoutingProfile ensures that no value is present for RoutingProfile, not even an explicit nil
func (o *VpcCreateRequest) UnsetRoutingProfile() {
	o.RoutingProfile.Unset()
}

// GetNetworkSecurityGroupId returns the NetworkSecurityGroupId field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *VpcCreateRequest) GetNetworkSecurityGroupId() string {
	if o == nil || IsNil(o.NetworkSecurityGroupId.Get()) {
		var ret string
		return ret
	}
	return *o.NetworkSecurityGroupId.Get()
}

// GetNetworkSecurityGroupIdOk returns a tuple with the NetworkSecurityGroupId field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *VpcCreateRequest) GetNetworkSecurityGroupIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.NetworkSecurityGroupId.Get(), o.NetworkSecurityGroupId.IsSet()
}

// HasNetworkSecurityGroupId returns a boolean if a field has been set.
func (o *VpcCreateRequest) HasNetworkSecurityGroupId() bool {
	if o != nil && o.NetworkSecurityGroupId.IsSet() {
		return true
	}

	return false
}

// SetNetworkSecurityGroupId gets a reference to the given NullableString and assigns it to the NetworkSecurityGroupId field.
func (o *VpcCreateRequest) SetNetworkSecurityGroupId(v string) {
	o.NetworkSecurityGroupId.Set(&v)
}

// SetNetworkSecurityGroupIdNil sets the value for NetworkSecurityGroupId to be an explicit nil
func (o *VpcCreateRequest) SetNetworkSecurityGroupIdNil() {
	o.NetworkSecurityGroupId.Set(nil)
}

// UnsetNetworkSecurityGroupId ensures that no value is present for NetworkSecurityGroupId, not even an explicit nil
func (o *VpcCreateRequest) UnsetNetworkSecurityGroupId() {
	o.NetworkSecurityGroupId.Unset()
}

// GetVni returns the Vni field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *VpcCreateRequest) GetVni() int32 {
	if o == nil || IsNil(o.Vni.Get()) {
		var ret int32
		return ret
	}
	return *o.Vni.Get()
}

// GetVniOk returns a tuple with the Vni field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *VpcCreateRequest) GetVniOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.Vni.Get(), o.Vni.IsSet()
}

// HasVni returns a boolean if a field has been set.
func (o *VpcCreateRequest) HasVni() bool {
	if o != nil && o.Vni.IsSet() {
		return true
	}

	return false
}

// SetVni gets a reference to the given NullableInt32 and assigns it to the Vni field.
func (o *VpcCreateRequest) SetVni(v int32) {
	o.Vni.Set(&v)
}

// SetVniNil sets the value for Vni to be an explicit nil
func (o *VpcCreateRequest) SetVniNil() {
	o.Vni.Set(nil)
}

// UnsetVni ensures that no value is present for Vni, not even an explicit nil
func (o *VpcCreateRequest) UnsetVni() {
	o.Vni.Unset()
}

// GetNvLinkLogicalPartitionId returns the NvLinkLogicalPartitionId field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *VpcCreateRequest) GetNvLinkLogicalPartitionId() string {
	if o == nil || IsNil(o.NvLinkLogicalPartitionId.Get()) {
		var ret string
		return ret
	}
	return *o.NvLinkLogicalPartitionId.Get()
}

// GetNvLinkLogicalPartitionIdOk returns a tuple with the NvLinkLogicalPartitionId field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *VpcCreateRequest) GetNvLinkLogicalPartitionIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.NvLinkLogicalPartitionId.Get(), o.NvLinkLogicalPartitionId.IsSet()
}

// HasNvLinkLogicalPartitionId returns a boolean if a field has been set.
func (o *VpcCreateRequest) HasNvLinkLogicalPartitionId() bool {
	if o != nil && o.NvLinkLogicalPartitionId.IsSet() {
		return true
	}

	return false
}

// SetNvLinkLogicalPartitionId gets a reference to the given NullableString and assigns it to the NvLinkLogicalPartitionId field.
func (o *VpcCreateRequest) SetNvLinkLogicalPartitionId(v string) {
	o.NvLinkLogicalPartitionId.Set(&v)
}

// SetNvLinkLogicalPartitionIdNil sets the value for NvLinkLogicalPartitionId to be an explicit nil
func (o *VpcCreateRequest) SetNvLinkLogicalPartitionIdNil() {
	o.NvLinkLogicalPartitionId.Set(nil)
}

// UnsetNvLinkLogicalPartitionId ensures that no value is present for NvLinkLogicalPartitionId, not even an explicit nil
func (o *VpcCreateRequest) UnsetNvLinkLogicalPartitionId() {
	o.NvLinkLogicalPartitionId.Unset()
}

// GetLabels returns the Labels field value if set, zero value otherwise.
func (o *VpcCreateRequest) GetLabels() map[string]string {
	if o == nil || IsNil(o.Labels) {
		var ret map[string]string
		return ret
	}
	return o.Labels
}

// GetLabelsOk returns a tuple with the Labels field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *VpcCreateRequest) GetLabelsOk() (map[string]string, bool) {
	if o == nil || IsNil(o.Labels) {
		return map[string]string{}, false
	}
	return o.Labels, true
}

// HasLabels returns a boolean if a field has been set.
func (o *VpcCreateRequest) HasLabels() bool {
	if o != nil && !IsNil(o.Labels) {
		return true
	}

	return false
}

// SetLabels gets a reference to the given map[string]string and assigns it to the Labels field.
func (o *VpcCreateRequest) SetLabels(v map[string]string) {
	o.Labels = v
}

func (o VpcCreateRequest) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o VpcCreateRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	toSerialize["name"] = o.Name
	if o.Description.IsSet() {
		toSerialize["description"] = o.Description.Get()
	}
	toSerialize["siteId"] = o.SiteId
	if o.NetworkVirtualizationType.IsSet() {
		toSerialize["networkVirtualizationType"] = o.NetworkVirtualizationType.Get()
	}
	if o.RoutingProfile.IsSet() {
		toSerialize["routingProfile"] = o.RoutingProfile.Get()
	}
	if o.NetworkSecurityGroupId.IsSet() {
		toSerialize["networkSecurityGroupId"] = o.NetworkSecurityGroupId.Get()
	}
	if o.Vni.IsSet() {
		toSerialize["vni"] = o.Vni.Get()
	}
	if o.NvLinkLogicalPartitionId.IsSet() {
		toSerialize["nvLinkLogicalPartitionId"] = o.NvLinkLogicalPartitionId.Get()
	}
	if !IsNil(o.Labels) {
		toSerialize["labels"] = o.Labels
	}
	return toSerialize, nil
}

func (o *VpcCreateRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"name",
		"siteId",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if value, exists := allProperties[requiredProperty]; !exists || value == nil {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varVpcCreateRequest := _VpcCreateRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varVpcCreateRequest)

	if err != nil {
		return err
	}

	*o = VpcCreateRequest(varVpcCreateRequest)

	return err
}

type NullableVpcCreateRequest struct {
	value *VpcCreateRequest
	isSet bool
}

func (v NullableVpcCreateRequest) Get() *VpcCreateRequest {
	return v.value
}

func (v *NullableVpcCreateRequest) Set(val *VpcCreateRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableVpcCreateRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableVpcCreateRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableVpcCreateRequest(val *VpcCreateRequest) *NullableVpcCreateRequest {
	return &NullableVpcCreateRequest{value: val, isSet: true}
}

func (v NullableVpcCreateRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableVpcCreateRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
