// SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
// SPDX-License-Identifier: Apache-2.0

/*
NVIDIA Infra Controller REST API

NVIDIA Infra Controller REST API allows users to create and manage resources, e.g., VPCs, Subnets, and Instances, across all connected NVIDIA Infra Controller datacenters, also referred to as Sites.

API version: 2.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package standard

import (
	"encoding/json"
)

// checks if the VpcUpdateRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &VpcUpdateRequest{}

// VpcUpdateRequest Request data to update a VPC
type VpcUpdateRequest struct {
	// Updated name of the VPC
	Name NullableString `json:"name,omitempty"`
	// Updated description of the VPC
	Description NullableString `json:"description,omitempty"`
	// ID of the Network Security Group to attach to the VPC
	NetworkSecurityGroupId NullableString `json:"networkSecurityGroupId,omitempty"`
	// ID of the default NVLink Logical Partition that GPUs for all Instances in the VPC will attach to. Can only be updated if VPC currently has no active Instances
	NvLinkLogicalPartitionId NullableString `json:"nvLinkLogicalPartitionId,omitempty"`
	// Update labels of the VPC. Up to 10 key-value pairs can be specified. The labels will be replaced with the labels sent in the request. Any labels not included in the request will be removed. To retain existing labels, fetch them first and include them in this request.
	Labels map[string]string `json:"labels,omitempty"`
}

// NewVpcUpdateRequest instantiates a new VpcUpdateRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewVpcUpdateRequest() *VpcUpdateRequest {
	this := VpcUpdateRequest{}
	return &this
}

// NewVpcUpdateRequestWithDefaults instantiates a new VpcUpdateRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewVpcUpdateRequestWithDefaults() *VpcUpdateRequest {
	this := VpcUpdateRequest{}
	return &this
}

// GetName returns the Name field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *VpcUpdateRequest) GetName() string {
	if o == nil || IsNil(o.Name.Get()) {
		var ret string
		return ret
	}
	return *o.Name.Get()
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *VpcUpdateRequest) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Name.Get(), o.Name.IsSet()
}

// HasName returns a boolean if a field has been set.
func (o *VpcUpdateRequest) HasName() bool {
	if o != nil && o.Name.IsSet() {
		return true
	}

	return false
}

// SetName gets a reference to the given NullableString and assigns it to the Name field.
func (o *VpcUpdateRequest) SetName(v string) {
	o.Name.Set(&v)
}

// SetNameNil sets the value for Name to be an explicit nil
func (o *VpcUpdateRequest) SetNameNil() {
	o.Name.Set(nil)
}

// UnsetName ensures that no value is present for Name, not even an explicit nil
func (o *VpcUpdateRequest) UnsetName() {
	o.Name.Unset()
}

// GetDescription returns the Description field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *VpcUpdateRequest) GetDescription() string {
	if o == nil || IsNil(o.Description.Get()) {
		var ret string
		return ret
	}
	return *o.Description.Get()
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *VpcUpdateRequest) GetDescriptionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Description.Get(), o.Description.IsSet()
}

// HasDescription returns a boolean if a field has been set.
func (o *VpcUpdateRequest) HasDescription() bool {
	if o != nil && o.Description.IsSet() {
		return true
	}

	return false
}

// SetDescription gets a reference to the given NullableString and assigns it to the Description field.
func (o *VpcUpdateRequest) SetDescription(v string) {
	o.Description.Set(&v)
}

// SetDescriptionNil sets the value for Description to be an explicit nil
func (o *VpcUpdateRequest) SetDescriptionNil() {
	o.Description.Set(nil)
}

// UnsetDescription ensures that no value is present for Description, not even an explicit nil
func (o *VpcUpdateRequest) UnsetDescription() {
	o.Description.Unset()
}

// GetNetworkSecurityGroupId returns the NetworkSecurityGroupId field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *VpcUpdateRequest) GetNetworkSecurityGroupId() string {
	if o == nil || IsNil(o.NetworkSecurityGroupId.Get()) {
		var ret string
		return ret
	}
	return *o.NetworkSecurityGroupId.Get()
}

// GetNetworkSecurityGroupIdOk returns a tuple with the NetworkSecurityGroupId field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *VpcUpdateRequest) GetNetworkSecurityGroupIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.NetworkSecurityGroupId.Get(), o.NetworkSecurityGroupId.IsSet()
}

// HasNetworkSecurityGroupId returns a boolean if a field has been set.
func (o *VpcUpdateRequest) HasNetworkSecurityGroupId() bool {
	if o != nil && o.NetworkSecurityGroupId.IsSet() {
		return true
	}

	return false
}

// SetNetworkSecurityGroupId gets a reference to the given NullableString and assigns it to the NetworkSecurityGroupId field.
func (o *VpcUpdateRequest) SetNetworkSecurityGroupId(v string) {
	o.NetworkSecurityGroupId.Set(&v)
}

// SetNetworkSecurityGroupIdNil sets the value for NetworkSecurityGroupId to be an explicit nil
func (o *VpcUpdateRequest) SetNetworkSecurityGroupIdNil() {
	o.NetworkSecurityGroupId.Set(nil)
}

// UnsetNetworkSecurityGroupId ensures that no value is present for NetworkSecurityGroupId, not even an explicit nil
func (o *VpcUpdateRequest) UnsetNetworkSecurityGroupId() {
	o.NetworkSecurityGroupId.Unset()
}

// GetNvLinkLogicalPartitionId returns the NvLinkLogicalPartitionId field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *VpcUpdateRequest) GetNvLinkLogicalPartitionId() string {
	if o == nil || IsNil(o.NvLinkLogicalPartitionId.Get()) {
		var ret string
		return ret
	}
	return *o.NvLinkLogicalPartitionId.Get()
}

// GetNvLinkLogicalPartitionIdOk returns a tuple with the NvLinkLogicalPartitionId field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *VpcUpdateRequest) GetNvLinkLogicalPartitionIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.NvLinkLogicalPartitionId.Get(), o.NvLinkLogicalPartitionId.IsSet()
}

// HasNvLinkLogicalPartitionId returns a boolean if a field has been set.
func (o *VpcUpdateRequest) HasNvLinkLogicalPartitionId() bool {
	if o != nil && o.NvLinkLogicalPartitionId.IsSet() {
		return true
	}

	return false
}

// SetNvLinkLogicalPartitionId gets a reference to the given NullableString and assigns it to the NvLinkLogicalPartitionId field.
func (o *VpcUpdateRequest) SetNvLinkLogicalPartitionId(v string) {
	o.NvLinkLogicalPartitionId.Set(&v)
}

// SetNvLinkLogicalPartitionIdNil sets the value for NvLinkLogicalPartitionId to be an explicit nil
func (o *VpcUpdateRequest) SetNvLinkLogicalPartitionIdNil() {
	o.NvLinkLogicalPartitionId.Set(nil)
}

// UnsetNvLinkLogicalPartitionId ensures that no value is present for NvLinkLogicalPartitionId, not even an explicit nil
func (o *VpcUpdateRequest) UnsetNvLinkLogicalPartitionId() {
	o.NvLinkLogicalPartitionId.Unset()
}

// GetLabels returns the Labels field value if set, zero value otherwise.
func (o *VpcUpdateRequest) GetLabels() map[string]string {
	if o == nil || IsNil(o.Labels) {
		var ret map[string]string
		return ret
	}
	return o.Labels
}

// GetLabelsOk returns a tuple with the Labels field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *VpcUpdateRequest) GetLabelsOk() (map[string]string, bool) {
	if o == nil || IsNil(o.Labels) {
		return map[string]string{}, false
	}
	return o.Labels, true
}

// HasLabels returns a boolean if a field has been set.
func (o *VpcUpdateRequest) HasLabels() bool {
	if o != nil && !IsNil(o.Labels) {
		return true
	}

	return false
}

// SetLabels gets a reference to the given map[string]string and assigns it to the Labels field.
func (o *VpcUpdateRequest) SetLabels(v map[string]string) {
	o.Labels = v
}

func (o VpcUpdateRequest) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o VpcUpdateRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.Name.IsSet() {
		toSerialize["name"] = o.Name.Get()
	}
	if o.Description.IsSet() {
		toSerialize["description"] = o.Description.Get()
	}
	if o.NetworkSecurityGroupId.IsSet() {
		toSerialize["networkSecurityGroupId"] = o.NetworkSecurityGroupId.Get()
	}
	if o.NvLinkLogicalPartitionId.IsSet() {
		toSerialize["nvLinkLogicalPartitionId"] = o.NvLinkLogicalPartitionId.Get()
	}
	if !IsNil(o.Labels) {
		toSerialize["labels"] = o.Labels
	}
	return toSerialize, nil
}

type NullableVpcUpdateRequest struct {
	value *VpcUpdateRequest
	isSet bool
}

func (v NullableVpcUpdateRequest) Get() *VpcUpdateRequest {
	return v.value
}

func (v *NullableVpcUpdateRequest) Set(val *VpcUpdateRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableVpcUpdateRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableVpcUpdateRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableVpcUpdateRequest(val *VpcUpdateRequest) *NullableVpcUpdateRequest {
	return &NullableVpcUpdateRequest{value: val, isSet: true}
}

func (v NullableVpcUpdateRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableVpcUpdateRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
