// SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
// SPDX-License-Identifier: Apache-2.0

/*
NVIDIA Infra Controller REST API

NVIDIA Infra Controller REST API allows users to create and manage resources, e.g., VPCs, Subnets, and Instances, across all connected NVIDIA Infra Controller datacenters, also referred to as Sites.

API version: 2.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package standard

import (
	"encoding/json"
	"time"
)

// checks if the Site type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &Site{}

// Site Site is a datacenter that is running NVIDIA Infra Controller (NICo) services
type Site struct {
	// Unique UUID v4 identifier for the Site in NICo Cloud
	Id *string `json:"id,omitempty"`
	// Name of the Site
	Name *string `json:"name,omitempty"`
	// Optional description for the Site
	Description NullableString `json:"description,omitempty"`
	// NGC organization ID of the Infrastructure Provider that owns the Site
	Org *string `json:"org,omitempty"`
	// ID of the Infrastructure Provider that owns the Site
	InfrastructureProviderId *string `json:"infrastructureProviderId,omitempty"`
	// Version of the Site Controller software
	SiteControllerVersion NullableString `json:"siteControllerVersion,omitempty"`
	// Version of the Site Agent software
	SiteAgentVersion NullableString `json:"siteAgentVersion,omitempty"`
	// Token that can be used to register a Site. Value only exposed to Provider
	RegistrationToken NullableString `json:"registrationToken,omitempty"`
	// Date/time when registration token expires. Value only exposed to Provider
	RegistrationTokenExpiration NullableTime `json:"registrationTokenExpiration,omitempty"`
	// Serial console hostname of the site controller
	SerialConsoleHostname NullableString `json:"serialConsoleHostname,omitempty"`
	// Indicates if Serial Console is enabled for the Site by the Provider
	IsSerialConsoleEnabled *bool `json:"isSerialConsoleEnabled,omitempty"`
	// Maximum idle time in seconds before Serial Console is disconnected
	SerialConsoleIdleTimeout NullableInt32 `json:"serialConsoleIdleTimeout,omitempty"`
	// Maximum length of Serial Console session in seconds
	SerialConsoleMaxSessionLength NullableInt32 `json:"serialConsoleMaxSessionLength,omitempty"`
	// Only visible to Tenant retrieving the Site. Indicates if Serial Console access using SSH Keys is enabled by Tenant
	IsSerialConsoleSSHKeysEnabled *bool `json:"isSerialConsoleSSHKeysEnabled,omitempty"`
	// Indicates if the Site is currently reachable from Cloud
	IsOnline *bool `json:"isOnline,omitempty"`
	// Status of the Site
	Status *SiteStatus `json:"status,omitempty"`
	// Chronological status history for the Site
	StatusHistory []StatusDetail `json:"statusHistory,omitempty"`
	// Date/time when the Site was created
	Created *time.Time `json:"created,omitempty"`
	// Date/time when the Site was last updated
	Updated *time.Time `json:"updated,omitempty"`
	// Site location information
	Location *SiteLocation `json:"location,omitempty"`
	// Site contact information
	Contact *SiteContact `json:"contact,omitempty"`
	// Site capabilities used for feature availability and configuration
	Capabilities *SiteCapabilities `json:"capabilities,omitempty"`
	// Machine counts by status for the Site
	MachineStats *SiteMachineStats `json:"machineStats,omitempty"`
	// GPU counts grouped by GPU type for the Site. Populated when includeGpuStats is set
	GpuStats []MachineGPUStats `json:"gpuStats,omitempty"`
}

// NewSite instantiates a new Site object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSite() *Site {
	this := Site{}
	return &this
}

// NewSiteWithDefaults instantiates a new Site object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSiteWithDefaults() *Site {
	this := Site{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *Site) GetId() string {
	if o == nil || IsNil(o.Id) {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Site) GetIdOk() (*string, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *Site) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *Site) SetId(v string) {
	o.Id = &v
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *Site) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Site) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *Site) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *Site) SetName(v string) {
	o.Name = &v
}

// GetDescription returns the Description field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *Site) GetDescription() string {
	if o == nil || IsNil(o.Description.Get()) {
		var ret string
		return ret
	}
	return *o.Description.Get()
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *Site) GetDescriptionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Description.Get(), o.Description.IsSet()
}

// HasDescription returns a boolean if a field has been set.
func (o *Site) HasDescription() bool {
	if o != nil && o.Description.IsSet() {
		return true
	}

	return false
}

// SetDescription gets a reference to the given NullableString and assigns it to the Description field.
func (o *Site) SetDescription(v string) {
	o.Description.Set(&v)
}

// SetDescriptionNil sets the value for Description to be an explicit nil
func (o *Site) SetDescriptionNil() {
	o.Description.Set(nil)
}

// UnsetDescription ensures that no value is present for Description, not even an explicit nil
func (o *Site) UnsetDescription() {
	o.Description.Unset()
}

// GetOrg returns the Org field value if set, zero value otherwise.
func (o *Site) GetOrg() string {
	if o == nil || IsNil(o.Org) {
		var ret string
		return ret
	}
	return *o.Org
}

// GetOrgOk returns a tuple with the Org field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Site) GetOrgOk() (*string, bool) {
	if o == nil || IsNil(o.Org) {
		return nil, false
	}
	return o.Org, true
}

// HasOrg returns a boolean if a field has been set.
func (o *Site) HasOrg() bool {
	if o != nil && !IsNil(o.Org) {
		return true
	}

	return false
}

// SetOrg gets a reference to the given string and assigns it to the Org field.
func (o *Site) SetOrg(v string) {
	o.Org = &v
}

// GetInfrastructureProviderId returns the InfrastructureProviderId field value if set, zero value otherwise.
func (o *Site) GetInfrastructureProviderId() string {
	if o == nil || IsNil(o.InfrastructureProviderId) {
		var ret string
		return ret
	}
	return *o.InfrastructureProviderId
}

// GetInfrastructureProviderIdOk returns a tuple with the InfrastructureProviderId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Site) GetInfrastructureProviderIdOk() (*string, bool) {
	if o == nil || IsNil(o.InfrastructureProviderId) {
		return nil, false
	}
	return o.InfrastructureProviderId, true
}

// HasInfrastructureProviderId returns a boolean if a field has been set.
func (o *Site) HasInfrastructureProviderId() bool {
	if o != nil && !IsNil(o.InfrastructureProviderId) {
		return true
	}

	return false
}

// SetInfrastructureProviderId gets a reference to the given string and assigns it to the InfrastructureProviderId field.
func (o *Site) SetInfrastructureProviderId(v string) {
	o.InfrastructureProviderId = &v
}

// GetSiteControllerVersion returns the SiteControllerVersion field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *Site) GetSiteControllerVersion() string {
	if o == nil || IsNil(o.SiteControllerVersion.Get()) {
		var ret string
		return ret
	}
	return *o.SiteControllerVersion.Get()
}

// GetSiteControllerVersionOk returns a tuple with the SiteControllerVersion field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *Site) GetSiteControllerVersionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.SiteControllerVersion.Get(), o.SiteControllerVersion.IsSet()
}

// HasSiteControllerVersion returns a boolean if a field has been set.
func (o *Site) HasSiteControllerVersion() bool {
	if o != nil && o.SiteControllerVersion.IsSet() {
		return true
	}

	return false
}

// SetSiteControllerVersion gets a reference to the given NullableString and assigns it to the SiteControllerVersion field.
func (o *Site) SetSiteControllerVersion(v string) {
	o.SiteControllerVersion.Set(&v)
}

// SetSiteControllerVersionNil sets the value for SiteControllerVersion to be an explicit nil
func (o *Site) SetSiteControllerVersionNil() {
	o.SiteControllerVersion.Set(nil)
}

// UnsetSiteControllerVersion ensures that no value is present for SiteControllerVersion, not even an explicit nil
func (o *Site) UnsetSiteControllerVersion() {
	o.SiteControllerVersion.Unset()
}

// GetSiteAgentVersion returns the SiteAgentVersion field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *Site) GetSiteAgentVersion() string {
	if o == nil || IsNil(o.SiteAgentVersion.Get()) {
		var ret string
		return ret
	}
	return *o.SiteAgentVersion.Get()
}

// GetSiteAgentVersionOk returns a tuple with the SiteAgentVersion field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *Site) GetSiteAgentVersionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.SiteAgentVersion.Get(), o.SiteAgentVersion.IsSet()
}

// HasSiteAgentVersion returns a boolean if a field has been set.
func (o *Site) HasSiteAgentVersion() bool {
	if o != nil && o.SiteAgentVersion.IsSet() {
		return true
	}

	return false
}

// SetSiteAgentVersion gets a reference to the given NullableString and assigns it to the SiteAgentVersion field.
func (o *Site) SetSiteAgentVersion(v string) {
	o.SiteAgentVersion.Set(&v)
}

// SetSiteAgentVersionNil sets the value for SiteAgentVersion to be an explicit nil
func (o *Site) SetSiteAgentVersionNil() {
	o.SiteAgentVersion.Set(nil)
}

// UnsetSiteAgentVersion ensures that no value is present for SiteAgentVersion, not even an explicit nil
func (o *Site) UnsetSiteAgentVersion() {
	o.SiteAgentVersion.Unset()
}

// GetRegistrationToken returns the RegistrationToken field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *Site) GetRegistrationToken() string {
	if o == nil || IsNil(o.RegistrationToken.Get()) {
		var ret string
		return ret
	}
	return *o.RegistrationToken.Get()
}

// GetRegistrationTokenOk returns a tuple with the RegistrationToken field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *Site) GetRegistrationTokenOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.RegistrationToken.Get(), o.RegistrationToken.IsSet()
}

// HasRegistrationToken returns a boolean if a field has been set.
func (o *Site) HasRegistrationToken() bool {
	if o != nil && o.RegistrationToken.IsSet() {
		return true
	}

	return false
}

// SetRegistrationToken gets a reference to the given NullableString and assigns it to the RegistrationToken field.
func (o *Site) SetRegistrationToken(v string) {
	o.RegistrationToken.Set(&v)
}

// SetRegistrationTokenNil sets the value for RegistrationToken to be an explicit nil
func (o *Site) SetRegistrationTokenNil() {
	o.RegistrationToken.Set(nil)
}

// UnsetRegistrationToken ensures that no value is present for RegistrationToken, not even an explicit nil
func (o *Site) UnsetRegistrationToken() {
	o.RegistrationToken.Unset()
}

// GetRegistrationTokenExpiration returns the RegistrationTokenExpiration field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *Site) GetRegistrationTokenExpiration() time.Time {
	if o == nil || IsNil(o.RegistrationTokenExpiration.Get()) {
		var ret time.Time
		return ret
	}
	return *o.RegistrationTokenExpiration.Get()
}

// GetRegistrationTokenExpirationOk returns a tuple with the RegistrationTokenExpiration field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *Site) GetRegistrationTokenExpirationOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return o.RegistrationTokenExpiration.Get(), o.RegistrationTokenExpiration.IsSet()
}

// HasRegistrationTokenExpiration returns a boolean if a field has been set.
func (o *Site) HasRegistrationTokenExpiration() bool {
	if o != nil && o.RegistrationTokenExpiration.IsSet() {
		return true
	}

	return false
}

// SetRegistrationTokenExpiration gets a reference to the given NullableTime and assigns it to the RegistrationTokenExpiration field.
func (o *Site) SetRegistrationTokenExpiration(v time.Time) {
	o.RegistrationTokenExpiration.Set(&v)
}

// SetRegistrationTokenExpirationNil sets the value for RegistrationTokenExpiration to be an explicit nil
func (o *Site) SetRegistrationTokenExpirationNil() {
	o.RegistrationTokenExpiration.Set(nil)
}

// UnsetRegistrationTokenExpiration ensures that no value is present for RegistrationTokenExpiration, not even an explicit nil
func (o *Site) UnsetRegistrationTokenExpiration() {
	o.RegistrationTokenExpiration.Unset()
}

// GetSerialConsoleHostname returns the SerialConsoleHostname field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *Site) GetSerialConsoleHostname() string {
	if o == nil || IsNil(o.SerialConsoleHostname.Get()) {
		var ret string
		return ret
	}
	return *o.SerialConsoleHostname.Get()
}

// GetSerialConsoleHostnameOk returns a tuple with the SerialConsoleHostname field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *Site) GetSerialConsoleHostnameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.SerialConsoleHostname.Get(), o.SerialConsoleHostname.IsSet()
}

// HasSerialConsoleHostname returns a boolean if a field has been set.
func (o *Site) HasSerialConsoleHostname() bool {
	if o != nil && o.SerialConsoleHostname.IsSet() {
		return true
	}

	return false
}

// SetSerialConsoleHostname gets a reference to the given NullableString and assigns it to the SerialConsoleHostname field.
func (o *Site) SetSerialConsoleHostname(v string) {
	o.SerialConsoleHostname.Set(&v)
}

// SetSerialConsoleHostnameNil sets the value for SerialConsoleHostname to be an explicit nil
func (o *Site) SetSerialConsoleHostnameNil() {
	o.SerialConsoleHostname.Set(nil)
}

// UnsetSerialConsoleHostname ensures that no value is present for SerialConsoleHostname, not even an explicit nil
func (o *Site) UnsetSerialConsoleHostname() {
	o.SerialConsoleHostname.Unset()
}

// GetIsSerialConsoleEnabled returns the IsSerialConsoleEnabled field value if set, zero value otherwise.
func (o *Site) GetIsSerialConsoleEnabled() bool {
	if o == nil || IsNil(o.IsSerialConsoleEnabled) {
		var ret bool
		return ret
	}
	return *o.IsSerialConsoleEnabled
}

// GetIsSerialConsoleEnabledOk returns a tuple with the IsSerialConsoleEnabled field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Site) GetIsSerialConsoleEnabledOk() (*bool, bool) {
	if o == nil || IsNil(o.IsSerialConsoleEnabled) {
		return nil, false
	}
	return o.IsSerialConsoleEnabled, true
}

// HasIsSerialConsoleEnabled returns a boolean if a field has been set.
func (o *Site) HasIsSerialConsoleEnabled() bool {
	if o != nil && !IsNil(o.IsSerialConsoleEnabled) {
		return true
	}

	return false
}

// SetIsSerialConsoleEnabled gets a reference to the given bool and assigns it to the IsSerialConsoleEnabled field.
func (o *Site) SetIsSerialConsoleEnabled(v bool) {
	o.IsSerialConsoleEnabled = &v
}

// GetSerialConsoleIdleTimeout returns the SerialConsoleIdleTimeout field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *Site) GetSerialConsoleIdleTimeout() int32 {
	if o == nil || IsNil(o.SerialConsoleIdleTimeout.Get()) {
		var ret int32
		return ret
	}
	return *o.SerialConsoleIdleTimeout.Get()
}

// GetSerialConsoleIdleTimeoutOk returns a tuple with the SerialConsoleIdleTimeout field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *Site) GetSerialConsoleIdleTimeoutOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.SerialConsoleIdleTimeout.Get(), o.SerialConsoleIdleTimeout.IsSet()
}

// HasSerialConsoleIdleTimeout returns a boolean if a field has been set.
func (o *Site) HasSerialConsoleIdleTimeout() bool {
	if o != nil && o.SerialConsoleIdleTimeout.IsSet() {
		return true
	}

	return false
}

// SetSerialConsoleIdleTimeout gets a reference to the given NullableInt32 and assigns it to the SerialConsoleIdleTimeout field.
func (o *Site) SetSerialConsoleIdleTimeout(v int32) {
	o.SerialConsoleIdleTimeout.Set(&v)
}

// SetSerialConsoleIdleTimeoutNil sets the value for SerialConsoleIdleTimeout to be an explicit nil
func (o *Site) SetSerialConsoleIdleTimeoutNil() {
	o.SerialConsoleIdleTimeout.Set(nil)
}

// UnsetSerialConsoleIdleTimeout ensures that no value is present for SerialConsoleIdleTimeout, not even an explicit nil
func (o *Site) UnsetSerialConsoleIdleTimeout() {
	o.SerialConsoleIdleTimeout.Unset()
}

// GetSerialConsoleMaxSessionLength returns the SerialConsoleMaxSessionLength field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *Site) GetSerialConsoleMaxSessionLength() int32 {
	if o == nil || IsNil(o.SerialConsoleMaxSessionLength.Get()) {
		var ret int32
		return ret
	}
	return *o.SerialConsoleMaxSessionLength.Get()
}

// GetSerialConsoleMaxSessionLengthOk returns a tuple with the SerialConsoleMaxSessionLength field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *Site) GetSerialConsoleMaxSessionLengthOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.SerialConsoleMaxSessionLength.Get(), o.SerialConsoleMaxSessionLength.IsSet()
}

// HasSerialConsoleMaxSessionLength returns a boolean if a field has been set.
func (o *Site) HasSerialConsoleMaxSessionLength() bool {
	if o != nil && o.SerialConsoleMaxSessionLength.IsSet() {
		return true
	}

	return false
}

// SetSerialConsoleMaxSessionLength gets a reference to the given NullableInt32 and assigns it to the SerialConsoleMaxSessionLength field.
func (o *Site) SetSerialConsoleMaxSessionLength(v int32) {
	o.SerialConsoleMaxSessionLength.Set(&v)
}

// SetSerialConsoleMaxSessionLengthNil sets the value for SerialConsoleMaxSessionLength to be an explicit nil
func (o *Site) SetSerialConsoleMaxSessionLengthNil() {
	o.SerialConsoleMaxSessionLength.Set(nil)
}

// UnsetSerialConsoleMaxSessionLength ensures that no value is present for SerialConsoleMaxSessionLength, not even an explicit nil
func (o *Site) UnsetSerialConsoleMaxSessionLength() {
	o.SerialConsoleMaxSessionLength.Unset()
}

// GetIsSerialConsoleSSHKeysEnabled returns the IsSerialConsoleSSHKeysEnabled field value if set, zero value otherwise.
func (o *Site) GetIsSerialConsoleSSHKeysEnabled() bool {
	if o == nil || IsNil(o.IsSerialConsoleSSHKeysEnabled) {
		var ret bool
		return ret
	}
	return *o.IsSerialConsoleSSHKeysEnabled
}

// GetIsSerialConsoleSSHKeysEnabledOk returns a tuple with the IsSerialConsoleSSHKeysEnabled field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Site) GetIsSerialConsoleSSHKeysEnabledOk() (*bool, bool) {
	if o == nil || IsNil(o.IsSerialConsoleSSHKeysEnabled) {
		return nil, false
	}
	return o.IsSerialConsoleSSHKeysEnabled, true
}

// HasIsSerialConsoleSSHKeysEnabled returns a boolean if a field has been set.
func (o *Site) HasIsSerialConsoleSSHKeysEnabled() bool {
	if o != nil && !IsNil(o.IsSerialConsoleSSHKeysEnabled) {
		return true
	}

	return false
}

// SetIsSerialConsoleSSHKeysEnabled gets a reference to the given bool and assigns it to the IsSerialConsoleSSHKeysEnabled field.
func (o *Site) SetIsSerialConsoleSSHKeysEnabled(v bool) {
	o.IsSerialConsoleSSHKeysEnabled = &v
}

// GetIsOnline returns the IsOnline field value if set, zero value otherwise.
func (o *Site) GetIsOnline() bool {
	if o == nil || IsNil(o.IsOnline) {
		var ret bool
		return ret
	}
	return *o.IsOnline
}

// GetIsOnlineOk returns a tuple with the IsOnline field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Site) GetIsOnlineOk() (*bool, bool) {
	if o == nil || IsNil(o.IsOnline) {
		return nil, false
	}
	return o.IsOnline, true
}

// HasIsOnline returns a boolean if a field has been set.
func (o *Site) HasIsOnline() bool {
	if o != nil && !IsNil(o.IsOnline) {
		return true
	}

	return false
}

// SetIsOnline gets a reference to the given bool and assigns it to the IsOnline field.
func (o *Site) SetIsOnline(v bool) {
	o.IsOnline = &v
}

// GetStatus returns the Status field value if set, zero value otherwise.
func (o *Site) GetStatus() SiteStatus {
	if o == nil || IsNil(o.Status) {
		var ret SiteStatus
		return ret
	}
	return *o.Status
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Site) GetStatusOk() (*SiteStatus, bool) {
	if o == nil || IsNil(o.Status) {
		return nil, false
	}
	return o.Status, true
}

// HasStatus returns a boolean if a field has been set.
func (o *Site) HasStatus() bool {
	if o != nil && !IsNil(o.Status) {
		return true
	}

	return false
}

// SetStatus gets a reference to the given SiteStatus and assigns it to the Status field.
func (o *Site) SetStatus(v SiteStatus) {
	o.Status = &v
}

// GetStatusHistory returns the StatusHistory field value if set, zero value otherwise.
func (o *Site) GetStatusHistory() []StatusDetail {
	if o == nil || IsNil(o.StatusHistory) {
		var ret []StatusDetail
		return ret
	}
	return o.StatusHistory
}

// GetStatusHistoryOk returns a tuple with the StatusHistory field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Site) GetStatusHistoryOk() ([]StatusDetail, bool) {
	if o == nil || IsNil(o.StatusHistory) {
		return nil, false
	}
	return o.StatusHistory, true
}

// HasStatusHistory returns a boolean if a field has been set.
func (o *Site) HasStatusHistory() bool {
	if o != nil && !IsNil(o.StatusHistory) {
		return true
	}

	return false
}

// SetStatusHistory gets a reference to the given []StatusDetail and assigns it to the StatusHistory field.
func (o *Site) SetStatusHistory(v []StatusDetail) {
	o.StatusHistory = v
}

// GetCreated returns the Created field value if set, zero value otherwise.
func (o *Site) GetCreated() time.Time {
	if o == nil || IsNil(o.Created) {
		var ret time.Time
		return ret
	}
	return *o.Created
}

// GetCreatedOk returns a tuple with the Created field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Site) GetCreatedOk() (*time.Time, bool) {
	if o == nil || IsNil(o.Created) {
		return nil, false
	}
	return o.Created, true
}

// HasCreated returns a boolean if a field has been set.
func (o *Site) HasCreated() bool {
	if o != nil && !IsNil(o.Created) {
		return true
	}

	return false
}

// SetCreated gets a reference to the given time.Time and assigns it to the Created field.
func (o *Site) SetCreated(v time.Time) {
	o.Created = &v
}

// GetUpdated returns the Updated field value if set, zero value otherwise.
func (o *Site) GetUpdated() time.Time {
	if o == nil || IsNil(o.Updated) {
		var ret time.Time
		return ret
	}
	return *o.Updated
}

// GetUpdatedOk returns a tuple with the Updated field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Site) GetUpdatedOk() (*time.Time, bool) {
	if o == nil || IsNil(o.Updated) {
		return nil, false
	}
	return o.Updated, true
}

// HasUpdated returns a boolean if a field has been set.
func (o *Site) HasUpdated() bool {
	if o != nil && !IsNil(o.Updated) {
		return true
	}

	return false
}

// SetUpdated gets a reference to the given time.Time and assigns it to the Updated field.
func (o *Site) SetUpdated(v time.Time) {
	o.Updated = &v
}

// GetLocation returns the Location field value if set, zero value otherwise.
func (o *Site) GetLocation() SiteLocation {
	if o == nil || IsNil(o.Location) {
		var ret SiteLocation
		return ret
	}
	return *o.Location
}

// GetLocationOk returns a tuple with the Location field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Site) GetLocationOk() (*SiteLocation, bool) {
	if o == nil || IsNil(o.Location) {
		return nil, false
	}
	return o.Location, true
}

// HasLocation returns a boolean if a field has been set.
func (o *Site) HasLocation() bool {
	if o != nil && !IsNil(o.Location) {
		return true
	}

	return false
}

// SetLocation gets a reference to the given SiteLocation and assigns it to the Location field.
func (o *Site) SetLocation(v SiteLocation) {
	o.Location = &v
}

// GetContact returns the Contact field value if set, zero value otherwise.
func (o *Site) GetContact() SiteContact {
	if o == nil || IsNil(o.Contact) {
		var ret SiteContact
		return ret
	}
	return *o.Contact
}

// GetContactOk returns a tuple with the Contact field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Site) GetContactOk() (*SiteContact, bool) {
	if o == nil || IsNil(o.Contact) {
		return nil, false
	}
	return o.Contact, true
}

// HasContact returns a boolean if a field has been set.
func (o *Site) HasContact() bool {
	if o != nil && !IsNil(o.Contact) {
		return true
	}

	return false
}

// SetContact gets a reference to the given SiteContact and assigns it to the Contact field.
func (o *Site) SetContact(v SiteContact) {
	o.Contact = &v
}

// GetCapabilities returns the Capabilities field value if set, zero value otherwise.
func (o *Site) GetCapabilities() SiteCapabilities {
	if o == nil || IsNil(o.Capabilities) {
		var ret SiteCapabilities
		return ret
	}
	return *o.Capabilities
}

// GetCapabilitiesOk returns a tuple with the Capabilities field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Site) GetCapabilitiesOk() (*SiteCapabilities, bool) {
	if o == nil || IsNil(o.Capabilities) {
		return nil, false
	}
	return o.Capabilities, true
}

// HasCapabilities returns a boolean if a field has been set.
func (o *Site) HasCapabilities() bool {
	if o != nil && !IsNil(o.Capabilities) {
		return true
	}

	return false
}

// SetCapabilities gets a reference to the given SiteCapabilities and assigns it to the Capabilities field.
func (o *Site) SetCapabilities(v SiteCapabilities) {
	o.Capabilities = &v
}

// GetMachineStats returns the MachineStats field value if set, zero value otherwise.
func (o *Site) GetMachineStats() SiteMachineStats {
	if o == nil || IsNil(o.MachineStats) {
		var ret SiteMachineStats
		return ret
	}
	return *o.MachineStats
}

// GetMachineStatsOk returns a tuple with the MachineStats field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Site) GetMachineStatsOk() (*SiteMachineStats, bool) {
	if o == nil || IsNil(o.MachineStats) {
		return nil, false
	}
	return o.MachineStats, true
}

// HasMachineStats returns a boolean if a field has been set.
func (o *Site) HasMachineStats() bool {
	if o != nil && !IsNil(o.MachineStats) {
		return true
	}

	return false
}

// SetMachineStats gets a reference to the given SiteMachineStats and assigns it to the MachineStats field.
func (o *Site) SetMachineStats(v SiteMachineStats) {
	o.MachineStats = &v
}

// GetGpuStats returns the GpuStats field value if set, zero value otherwise.
func (o *Site) GetGpuStats() []MachineGPUStats {
	if o == nil || IsNil(o.GpuStats) {
		var ret []MachineGPUStats
		return ret
	}
	return o.GpuStats
}

// GetGpuStatsOk returns a tuple with the GpuStats field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Site) GetGpuStatsOk() ([]MachineGPUStats, bool) {
	if o == nil || IsNil(o.GpuStats) {
		return nil, false
	}
	return o.GpuStats, true
}

// HasGpuStats returns a boolean if a field has been set.
func (o *Site) HasGpuStats() bool {
	if o != nil && !IsNil(o.GpuStats) {
		return true
	}

	return false
}

// SetGpuStats gets a reference to the given []MachineGPUStats and assigns it to the GpuStats field.
func (o *Site) SetGpuStats(v []MachineGPUStats) {
	o.GpuStats = v
}

func (o Site) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o Site) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if o.Description.IsSet() {
		toSerialize["description"] = o.Description.Get()
	}
	if !IsNil(o.Org) {
		toSerialize["org"] = o.Org
	}
	if !IsNil(o.InfrastructureProviderId) {
		toSerialize["infrastructureProviderId"] = o.InfrastructureProviderId
	}
	if o.SiteControllerVersion.IsSet() {
		toSerialize["siteControllerVersion"] = o.SiteControllerVersion.Get()
	}
	if o.SiteAgentVersion.IsSet() {
		toSerialize["siteAgentVersion"] = o.SiteAgentVersion.Get()
	}
	if o.RegistrationToken.IsSet() {
		toSerialize["registrationToken"] = o.RegistrationToken.Get()
	}
	if o.RegistrationTokenExpiration.IsSet() {
		toSerialize["registrationTokenExpiration"] = o.RegistrationTokenExpiration.Get()
	}
	if o.SerialConsoleHostname.IsSet() {
		toSerialize["serialConsoleHostname"] = o.SerialConsoleHostname.Get()
	}
	if !IsNil(o.IsSerialConsoleEnabled) {
		toSerialize["isSerialConsoleEnabled"] = o.IsSerialConsoleEnabled
	}
	if o.SerialConsoleIdleTimeout.IsSet() {
		toSerialize["serialConsoleIdleTimeout"] = o.SerialConsoleIdleTimeout.Get()
	}
	if o.SerialConsoleMaxSessionLength.IsSet() {
		toSerialize["serialConsoleMaxSessionLength"] = o.SerialConsoleMaxSessionLength.Get()
	}
	if !IsNil(o.IsSerialConsoleSSHKeysEnabled) {
		toSerialize["isSerialConsoleSSHKeysEnabled"] = o.IsSerialConsoleSSHKeysEnabled
	}
	if !IsNil(o.IsOnline) {
		toSerialize["isOnline"] = o.IsOnline
	}
	if !IsNil(o.Status) {
		toSerialize["status"] = o.Status
	}
	if !IsNil(o.StatusHistory) {
		toSerialize["statusHistory"] = o.StatusHistory
	}
	if !IsNil(o.Created) {
		toSerialize["created"] = o.Created
	}
	if !IsNil(o.Updated) {
		toSerialize["updated"] = o.Updated
	}
	if !IsNil(o.Location) {
		toSerialize["location"] = o.Location
	}
	if !IsNil(o.Contact) {
		toSerialize["contact"] = o.Contact
	}
	if !IsNil(o.Capabilities) {
		toSerialize["capabilities"] = o.Capabilities
	}
	if !IsNil(o.MachineStats) {
		toSerialize["machineStats"] = o.MachineStats
	}
	if !IsNil(o.GpuStats) {
		toSerialize["gpuStats"] = o.GpuStats
	}
	return toSerialize, nil
}

type NullableSite struct {
	value *Site
	isSet bool
}

func (v NullableSite) Get() *Site {
	return v.value
}

func (v *NullableSite) Set(val *Site) {
	v.value = val
	v.isSet = true
}

func (v NullableSite) IsSet() bool {
	return v.isSet
}

func (v *NullableSite) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSite(val *Site) *NullableSite {
	return &NullableSite{value: val, isSet: true}
}

func (v NullableSite) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSite) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
