// SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
// SPDX-License-Identifier: Apache-2.0

/*
NVIDIA Infra Controller REST API

NVIDIA Infra Controller REST API allows users to create and manage resources, e.g., VPCs, Subnets, and Instances, across all connected NVIDIA Infra Controller datacenters, also referred to as Sites.

API version: 2.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package standard

import (
	"encoding/json"
)

// checks if the InstanceUpdateRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &InstanceUpdateRequest{}

// InstanceUpdateRequest Request data to update Instance
type InstanceUpdateRequest struct {
	// Updated name for the Instance
	Name NullableString `json:"name,omitempty"`
	// Updated description of the Instance
	Description NullableString `json:"description,omitempty"`
	// Trigger power cycle for Instance
	TriggerReboot NullableBool `json:"triggerReboot,omitempty"`
	// When specified along with triggerReboot, the Instance will boot using the custom iPXE specified by OS. If Instance has alwaysBootWithCustomIpxe flag set then this value will be ignored.
	RebootWithCustomIpxe NullableBool `json:"rebootWithCustomIpxe,omitempty"`
	// When specified, pending Instance updates such as DPU reprovisioning are applied on reboot
	ApplyUpdatesOnReboot NullableBool `json:"applyUpdatesOnReboot,omitempty"`
	// The UUID of the desired operating system.
	OperatingSystemId NullableString `json:"operatingSystemId,omitempty"`
	// The iPXE script content to be used for booting.
	IpxeScript NullableString `json:"ipxeScript,omitempty"`
	// Specify a new list of SSH Key Group IDs that will provide Serial over LAN and SSH access.  This will overwrite an existing list.
	SshKeyGroupIds []string `json:"sshKeyGroupIds,omitempty"`
	// ID of the Network Security Group to attach to the Instance
	NetworkSecurityGroupId NullableString `json:"networkSecurityGroupId,omitempty"`
	// Any user-data to be sent to the booting OS.  For example, cloud-init data.
	UserData NullableString `json:"userData,omitempty"`
	// Whether the custom iPXE data should be used for every boot.
	AlwaysBootWithCustomIpxe NullableBool `json:"alwaysBootWithCustomIpxe,omitempty"`
	// Indicates whether the Phone Home service should be enabled or disabled for the Instance
	PhoneHomeEnabled NullableBool `json:"phoneHomeEnabled,omitempty"`
	// Update labels of the Instance. The labels will be replaced with the labels sent in the request. Any labels not included in the request will be removed. To retain existing labels, fetch them first and include them in this request.
	Labels map[string]string `json:"labels,omitempty"`
	// IDs of additional VPCs the Instance should attach to through non-primary interfaces. This field may only be specified when every entry in `interfaces` uses `vpcPrefixId`. IDs must be unique, must be valid UUIDs, and must not include the primary `vpcId`.
	SecondaryVpcIds []string `json:"secondaryVpcIds,omitempty"`
	// Update Interfaces of the Instance. Mutually exclusive with `autoNetwork`: when `autoNetwork` is true this list MUST be empty.
	Interfaces []InterfaceCreateRequest `json:"interfaces,omitempty"`
	// When set, asks NICo to auto-resolve the Instance's network interfaces from the host's underlay (HostInband) segments. `null` leaves the value unchanged; `true` (re-)resolves; `false` returns to explicit interface configuration. When `true`, the Instance's VPC MUST already have `networkVirtualizationType: FLAT`, `interfaces` MUST be empty or omitted, and `secondaryVpcIds` MUST be empty or omitted.
	AutoNetwork NullableBool `json:"autoNetwork,omitempty"`
	// Update InfiniBand Interfaces of the Instance
	InfinibandInterfaces []InfiniBandInterfaceCreateRequest `json:"infinibandInterfaces,omitempty"`
	// Update NVLink Interfaces of the Instance. A subset of GPUs may be specified. Each item references a GPU index (`deviceInstance`) and an NVLink Logical Partition. Different interfaces may reference different NVLink Logical Partitions. Partial updates are not allowed; specified interfaces will delete or replace existing Interfaces. Updating is not allowed if the Instance's VPC has the `nvLinkLogicalPartitionId` attribute set.
	NvLinkInterfaces []NVLinkInterfaceCreateOrUpdateRequest `json:"nvLinkInterfaces,omitempty"`
	// Updated set of DPU Extension Services to deploy to the DPUs of this Instance
	DpuExtensionServiceDeployments []DpuExtensionServiceDeploymentRequest `json:"dpuExtensionServiceDeployments,omitempty"`
}

// NewInstanceUpdateRequest instantiates a new InstanceUpdateRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewInstanceUpdateRequest() *InstanceUpdateRequest {
	this := InstanceUpdateRequest{}
	return &this
}

// NewInstanceUpdateRequestWithDefaults instantiates a new InstanceUpdateRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewInstanceUpdateRequestWithDefaults() *InstanceUpdateRequest {
	this := InstanceUpdateRequest{}
	return &this
}

// GetName returns the Name field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *InstanceUpdateRequest) GetName() string {
	if o == nil || IsNil(o.Name.Get()) {
		var ret string
		return ret
	}
	return *o.Name.Get()
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *InstanceUpdateRequest) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Name.Get(), o.Name.IsSet()
}

// HasName returns a boolean if a field has been set.
func (o *InstanceUpdateRequest) HasName() bool {
	if o != nil && o.Name.IsSet() {
		return true
	}

	return false
}

// SetName gets a reference to the given NullableString and assigns it to the Name field.
func (o *InstanceUpdateRequest) SetName(v string) {
	o.Name.Set(&v)
}

// SetNameNil sets the value for Name to be an explicit nil
func (o *InstanceUpdateRequest) SetNameNil() {
	o.Name.Set(nil)
}

// UnsetName ensures that no value is present for Name, not even an explicit nil
func (o *InstanceUpdateRequest) UnsetName() {
	o.Name.Unset()
}

// GetDescription returns the Description field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *InstanceUpdateRequest) GetDescription() string {
	if o == nil || IsNil(o.Description.Get()) {
		var ret string
		return ret
	}
	return *o.Description.Get()
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *InstanceUpdateRequest) GetDescriptionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Description.Get(), o.Description.IsSet()
}

// HasDescription returns a boolean if a field has been set.
func (o *InstanceUpdateRequest) HasDescription() bool {
	if o != nil && o.Description.IsSet() {
		return true
	}

	return false
}

// SetDescription gets a reference to the given NullableString and assigns it to the Description field.
func (o *InstanceUpdateRequest) SetDescription(v string) {
	o.Description.Set(&v)
}

// SetDescriptionNil sets the value for Description to be an explicit nil
func (o *InstanceUpdateRequest) SetDescriptionNil() {
	o.Description.Set(nil)
}

// UnsetDescription ensures that no value is present for Description, not even an explicit nil
func (o *InstanceUpdateRequest) UnsetDescription() {
	o.Description.Unset()
}

// GetTriggerReboot returns the TriggerReboot field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *InstanceUpdateRequest) GetTriggerReboot() bool {
	if o == nil || IsNil(o.TriggerReboot.Get()) {
		var ret bool
		return ret
	}
	return *o.TriggerReboot.Get()
}

// GetTriggerRebootOk returns a tuple with the TriggerReboot field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *InstanceUpdateRequest) GetTriggerRebootOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return o.TriggerReboot.Get(), o.TriggerReboot.IsSet()
}

// HasTriggerReboot returns a boolean if a field has been set.
func (o *InstanceUpdateRequest) HasTriggerReboot() bool {
	if o != nil && o.TriggerReboot.IsSet() {
		return true
	}

	return false
}

// SetTriggerReboot gets a reference to the given NullableBool and assigns it to the TriggerReboot field.
func (o *InstanceUpdateRequest) SetTriggerReboot(v bool) {
	o.TriggerReboot.Set(&v)
}

// SetTriggerRebootNil sets the value for TriggerReboot to be an explicit nil
func (o *InstanceUpdateRequest) SetTriggerRebootNil() {
	o.TriggerReboot.Set(nil)
}

// UnsetTriggerReboot ensures that no value is present for TriggerReboot, not even an explicit nil
func (o *InstanceUpdateRequest) UnsetTriggerReboot() {
	o.TriggerReboot.Unset()
}

// GetRebootWithCustomIpxe returns the RebootWithCustomIpxe field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *InstanceUpdateRequest) GetRebootWithCustomIpxe() bool {
	if o == nil || IsNil(o.RebootWithCustomIpxe.Get()) {
		var ret bool
		return ret
	}
	return *o.RebootWithCustomIpxe.Get()
}

// GetRebootWithCustomIpxeOk returns a tuple with the RebootWithCustomIpxe field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *InstanceUpdateRequest) GetRebootWithCustomIpxeOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return o.RebootWithCustomIpxe.Get(), o.RebootWithCustomIpxe.IsSet()
}

// HasRebootWithCustomIpxe returns a boolean if a field has been set.
func (o *InstanceUpdateRequest) HasRebootWithCustomIpxe() bool {
	if o != nil && o.RebootWithCustomIpxe.IsSet() {
		return true
	}

	return false
}

// SetRebootWithCustomIpxe gets a reference to the given NullableBool and assigns it to the RebootWithCustomIpxe field.
func (o *InstanceUpdateRequest) SetRebootWithCustomIpxe(v bool) {
	o.RebootWithCustomIpxe.Set(&v)
}

// SetRebootWithCustomIpxeNil sets the value for RebootWithCustomIpxe to be an explicit nil
func (o *InstanceUpdateRequest) SetRebootWithCustomIpxeNil() {
	o.RebootWithCustomIpxe.Set(nil)
}

// UnsetRebootWithCustomIpxe ensures that no value is present for RebootWithCustomIpxe, not even an explicit nil
func (o *InstanceUpdateRequest) UnsetRebootWithCustomIpxe() {
	o.RebootWithCustomIpxe.Unset()
}

// GetApplyUpdatesOnReboot returns the ApplyUpdatesOnReboot field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *InstanceUpdateRequest) GetApplyUpdatesOnReboot() bool {
	if o == nil || IsNil(o.ApplyUpdatesOnReboot.Get()) {
		var ret bool
		return ret
	}
	return *o.ApplyUpdatesOnReboot.Get()
}

// GetApplyUpdatesOnRebootOk returns a tuple with the ApplyUpdatesOnReboot field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *InstanceUpdateRequest) GetApplyUpdatesOnRebootOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return o.ApplyUpdatesOnReboot.Get(), o.ApplyUpdatesOnReboot.IsSet()
}

// HasApplyUpdatesOnReboot returns a boolean if a field has been set.
func (o *InstanceUpdateRequest) HasApplyUpdatesOnReboot() bool {
	if o != nil && o.ApplyUpdatesOnReboot.IsSet() {
		return true
	}

	return false
}

// SetApplyUpdatesOnReboot gets a reference to the given NullableBool and assigns it to the ApplyUpdatesOnReboot field.
func (o *InstanceUpdateRequest) SetApplyUpdatesOnReboot(v bool) {
	o.ApplyUpdatesOnReboot.Set(&v)
}

// SetApplyUpdatesOnRebootNil sets the value for ApplyUpdatesOnReboot to be an explicit nil
func (o *InstanceUpdateRequest) SetApplyUpdatesOnRebootNil() {
	o.ApplyUpdatesOnReboot.Set(nil)
}

// UnsetApplyUpdatesOnReboot ensures that no value is present for ApplyUpdatesOnReboot, not even an explicit nil
func (o *InstanceUpdateRequest) UnsetApplyUpdatesOnReboot() {
	o.ApplyUpdatesOnReboot.Unset()
}

// GetOperatingSystemId returns the OperatingSystemId field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *InstanceUpdateRequest) GetOperatingSystemId() string {
	if o == nil || IsNil(o.OperatingSystemId.Get()) {
		var ret string
		return ret
	}
	return *o.OperatingSystemId.Get()
}

// GetOperatingSystemIdOk returns a tuple with the OperatingSystemId field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *InstanceUpdateRequest) GetOperatingSystemIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.OperatingSystemId.Get(), o.OperatingSystemId.IsSet()
}

// HasOperatingSystemId returns a boolean if a field has been set.
func (o *InstanceUpdateRequest) HasOperatingSystemId() bool {
	if o != nil && o.OperatingSystemId.IsSet() {
		return true
	}

	return false
}

// SetOperatingSystemId gets a reference to the given NullableString and assigns it to the OperatingSystemId field.
func (o *InstanceUpdateRequest) SetOperatingSystemId(v string) {
	o.OperatingSystemId.Set(&v)
}

// SetOperatingSystemIdNil sets the value for OperatingSystemId to be an explicit nil
func (o *InstanceUpdateRequest) SetOperatingSystemIdNil() {
	o.OperatingSystemId.Set(nil)
}

// UnsetOperatingSystemId ensures that no value is present for OperatingSystemId, not even an explicit nil
func (o *InstanceUpdateRequest) UnsetOperatingSystemId() {
	o.OperatingSystemId.Unset()
}

// GetIpxeScript returns the IpxeScript field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *InstanceUpdateRequest) GetIpxeScript() string {
	if o == nil || IsNil(o.IpxeScript.Get()) {
		var ret string
		return ret
	}
	return *o.IpxeScript.Get()
}

// GetIpxeScriptOk returns a tuple with the IpxeScript field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *InstanceUpdateRequest) GetIpxeScriptOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.IpxeScript.Get(), o.IpxeScript.IsSet()
}

// HasIpxeScript returns a boolean if a field has been set.
func (o *InstanceUpdateRequest) HasIpxeScript() bool {
	if o != nil && o.IpxeScript.IsSet() {
		return true
	}

	return false
}

// SetIpxeScript gets a reference to the given NullableString and assigns it to the IpxeScript field.
func (o *InstanceUpdateRequest) SetIpxeScript(v string) {
	o.IpxeScript.Set(&v)
}

// SetIpxeScriptNil sets the value for IpxeScript to be an explicit nil
func (o *InstanceUpdateRequest) SetIpxeScriptNil() {
	o.IpxeScript.Set(nil)
}

// UnsetIpxeScript ensures that no value is present for IpxeScript, not even an explicit nil
func (o *InstanceUpdateRequest) UnsetIpxeScript() {
	o.IpxeScript.Unset()
}

// GetSshKeyGroupIds returns the SshKeyGroupIds field value if set, zero value otherwise.
func (o *InstanceUpdateRequest) GetSshKeyGroupIds() []string {
	if o == nil || IsNil(o.SshKeyGroupIds) {
		var ret []string
		return ret
	}
	return o.SshKeyGroupIds
}

// GetSshKeyGroupIdsOk returns a tuple with the SshKeyGroupIds field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InstanceUpdateRequest) GetSshKeyGroupIdsOk() ([]string, bool) {
	if o == nil || IsNil(o.SshKeyGroupIds) {
		return nil, false
	}
	return o.SshKeyGroupIds, true
}

// HasSshKeyGroupIds returns a boolean if a field has been set.
func (o *InstanceUpdateRequest) HasSshKeyGroupIds() bool {
	if o != nil && !IsNil(o.SshKeyGroupIds) {
		return true
	}

	return false
}

// SetSshKeyGroupIds gets a reference to the given []string and assigns it to the SshKeyGroupIds field.
func (o *InstanceUpdateRequest) SetSshKeyGroupIds(v []string) {
	o.SshKeyGroupIds = v
}

// GetNetworkSecurityGroupId returns the NetworkSecurityGroupId field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *InstanceUpdateRequest) GetNetworkSecurityGroupId() string {
	if o == nil || IsNil(o.NetworkSecurityGroupId.Get()) {
		var ret string
		return ret
	}
	return *o.NetworkSecurityGroupId.Get()
}

// GetNetworkSecurityGroupIdOk returns a tuple with the NetworkSecurityGroupId field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *InstanceUpdateRequest) GetNetworkSecurityGroupIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.NetworkSecurityGroupId.Get(), o.NetworkSecurityGroupId.IsSet()
}

// HasNetworkSecurityGroupId returns a boolean if a field has been set.
func (o *InstanceUpdateRequest) HasNetworkSecurityGroupId() bool {
	if o != nil && o.NetworkSecurityGroupId.IsSet() {
		return true
	}

	return false
}

// SetNetworkSecurityGroupId gets a reference to the given NullableString and assigns it to the NetworkSecurityGroupId field.
func (o *InstanceUpdateRequest) SetNetworkSecurityGroupId(v string) {
	o.NetworkSecurityGroupId.Set(&v)
}

// SetNetworkSecurityGroupIdNil sets the value for NetworkSecurityGroupId to be an explicit nil
func (o *InstanceUpdateRequest) SetNetworkSecurityGroupIdNil() {
	o.NetworkSecurityGroupId.Set(nil)
}

// UnsetNetworkSecurityGroupId ensures that no value is present for NetworkSecurityGroupId, not even an explicit nil
func (o *InstanceUpdateRequest) UnsetNetworkSecurityGroupId() {
	o.NetworkSecurityGroupId.Unset()
}

// GetUserData returns the UserData field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *InstanceUpdateRequest) GetUserData() string {
	if o == nil || IsNil(o.UserData.Get()) {
		var ret string
		return ret
	}
	return *o.UserData.Get()
}

// GetUserDataOk returns a tuple with the UserData field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *InstanceUpdateRequest) GetUserDataOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.UserData.Get(), o.UserData.IsSet()
}

// HasUserData returns a boolean if a field has been set.
func (o *InstanceUpdateRequest) HasUserData() bool {
	if o != nil && o.UserData.IsSet() {
		return true
	}

	return false
}

// SetUserData gets a reference to the given NullableString and assigns it to the UserData field.
func (o *InstanceUpdateRequest) SetUserData(v string) {
	o.UserData.Set(&v)
}

// SetUserDataNil sets the value for UserData to be an explicit nil
func (o *InstanceUpdateRequest) SetUserDataNil() {
	o.UserData.Set(nil)
}

// UnsetUserData ensures that no value is present for UserData, not even an explicit nil
func (o *InstanceUpdateRequest) UnsetUserData() {
	o.UserData.Unset()
}

// GetAlwaysBootWithCustomIpxe returns the AlwaysBootWithCustomIpxe field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *InstanceUpdateRequest) GetAlwaysBootWithCustomIpxe() bool {
	if o == nil || IsNil(o.AlwaysBootWithCustomIpxe.Get()) {
		var ret bool
		return ret
	}
	return *o.AlwaysBootWithCustomIpxe.Get()
}

// GetAlwaysBootWithCustomIpxeOk returns a tuple with the AlwaysBootWithCustomIpxe field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *InstanceUpdateRequest) GetAlwaysBootWithCustomIpxeOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return o.AlwaysBootWithCustomIpxe.Get(), o.AlwaysBootWithCustomIpxe.IsSet()
}

// HasAlwaysBootWithCustomIpxe returns a boolean if a field has been set.
func (o *InstanceUpdateRequest) HasAlwaysBootWithCustomIpxe() bool {
	if o != nil && o.AlwaysBootWithCustomIpxe.IsSet() {
		return true
	}

	return false
}

// SetAlwaysBootWithCustomIpxe gets a reference to the given NullableBool and assigns it to the AlwaysBootWithCustomIpxe field.
func (o *InstanceUpdateRequest) SetAlwaysBootWithCustomIpxe(v bool) {
	o.AlwaysBootWithCustomIpxe.Set(&v)
}

// SetAlwaysBootWithCustomIpxeNil sets the value for AlwaysBootWithCustomIpxe to be an explicit nil
func (o *InstanceUpdateRequest) SetAlwaysBootWithCustomIpxeNil() {
	o.AlwaysBootWithCustomIpxe.Set(nil)
}

// UnsetAlwaysBootWithCustomIpxe ensures that no value is present for AlwaysBootWithCustomIpxe, not even an explicit nil
func (o *InstanceUpdateRequest) UnsetAlwaysBootWithCustomIpxe() {
	o.AlwaysBootWithCustomIpxe.Unset()
}

// GetPhoneHomeEnabled returns the PhoneHomeEnabled field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *InstanceUpdateRequest) GetPhoneHomeEnabled() bool {
	if o == nil || IsNil(o.PhoneHomeEnabled.Get()) {
		var ret bool
		return ret
	}
	return *o.PhoneHomeEnabled.Get()
}

// GetPhoneHomeEnabledOk returns a tuple with the PhoneHomeEnabled field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *InstanceUpdateRequest) GetPhoneHomeEnabledOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return o.PhoneHomeEnabled.Get(), o.PhoneHomeEnabled.IsSet()
}

// HasPhoneHomeEnabled returns a boolean if a field has been set.
func (o *InstanceUpdateRequest) HasPhoneHomeEnabled() bool {
	if o != nil && o.PhoneHomeEnabled.IsSet() {
		return true
	}

	return false
}

// SetPhoneHomeEnabled gets a reference to the given NullableBool and assigns it to the PhoneHomeEnabled field.
func (o *InstanceUpdateRequest) SetPhoneHomeEnabled(v bool) {
	o.PhoneHomeEnabled.Set(&v)
}

// SetPhoneHomeEnabledNil sets the value for PhoneHomeEnabled to be an explicit nil
func (o *InstanceUpdateRequest) SetPhoneHomeEnabledNil() {
	o.PhoneHomeEnabled.Set(nil)
}

// UnsetPhoneHomeEnabled ensures that no value is present for PhoneHomeEnabled, not even an explicit nil
func (o *InstanceUpdateRequest) UnsetPhoneHomeEnabled() {
	o.PhoneHomeEnabled.Unset()
}

// GetLabels returns the Labels field value if set, zero value otherwise.
func (o *InstanceUpdateRequest) GetLabels() map[string]string {
	if o == nil || IsNil(o.Labels) {
		var ret map[string]string
		return ret
	}
	return o.Labels
}

// GetLabelsOk returns a tuple with the Labels field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InstanceUpdateRequest) GetLabelsOk() (map[string]string, bool) {
	if o == nil || IsNil(o.Labels) {
		return map[string]string{}, false
	}
	return o.Labels, true
}

// HasLabels returns a boolean if a field has been set.
func (o *InstanceUpdateRequest) HasLabels() bool {
	if o != nil && !IsNil(o.Labels) {
		return true
	}

	return false
}

// SetLabels gets a reference to the given map[string]string and assigns it to the Labels field.
func (o *InstanceUpdateRequest) SetLabels(v map[string]string) {
	o.Labels = v
}

// GetSecondaryVpcIds returns the SecondaryVpcIds field value if set, zero value otherwise.
func (o *InstanceUpdateRequest) GetSecondaryVpcIds() []string {
	if o == nil || IsNil(o.SecondaryVpcIds) {
		var ret []string
		return ret
	}
	return o.SecondaryVpcIds
}

// GetSecondaryVpcIdsOk returns a tuple with the SecondaryVpcIds field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InstanceUpdateRequest) GetSecondaryVpcIdsOk() ([]string, bool) {
	if o == nil || IsNil(o.SecondaryVpcIds) {
		return nil, false
	}
	return o.SecondaryVpcIds, true
}

// HasSecondaryVpcIds returns a boolean if a field has been set.
func (o *InstanceUpdateRequest) HasSecondaryVpcIds() bool {
	if o != nil && !IsNil(o.SecondaryVpcIds) {
		return true
	}

	return false
}

// SetSecondaryVpcIds gets a reference to the given []string and assigns it to the SecondaryVpcIds field.
func (o *InstanceUpdateRequest) SetSecondaryVpcIds(v []string) {
	o.SecondaryVpcIds = v
}

// GetInterfaces returns the Interfaces field value if set, zero value otherwise.
func (o *InstanceUpdateRequest) GetInterfaces() []InterfaceCreateRequest {
	if o == nil || IsNil(o.Interfaces) {
		var ret []InterfaceCreateRequest
		return ret
	}
	return o.Interfaces
}

// GetInterfacesOk returns a tuple with the Interfaces field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InstanceUpdateRequest) GetInterfacesOk() ([]InterfaceCreateRequest, bool) {
	if o == nil || IsNil(o.Interfaces) {
		return nil, false
	}
	return o.Interfaces, true
}

// HasInterfaces returns a boolean if a field has been set.
func (o *InstanceUpdateRequest) HasInterfaces() bool {
	if o != nil && !IsNil(o.Interfaces) {
		return true
	}

	return false
}

// SetInterfaces gets a reference to the given []InterfaceCreateRequest and assigns it to the Interfaces field.
func (o *InstanceUpdateRequest) SetInterfaces(v []InterfaceCreateRequest) {
	o.Interfaces = v
}

// GetAutoNetwork returns the AutoNetwork field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *InstanceUpdateRequest) GetAutoNetwork() bool {
	if o == nil || IsNil(o.AutoNetwork.Get()) {
		var ret bool
		return ret
	}
	return *o.AutoNetwork.Get()
}

// GetAutoNetworkOk returns a tuple with the AutoNetwork field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *InstanceUpdateRequest) GetAutoNetworkOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return o.AutoNetwork.Get(), o.AutoNetwork.IsSet()
}

// HasAutoNetwork returns a boolean if a field has been set.
func (o *InstanceUpdateRequest) HasAutoNetwork() bool {
	if o != nil && o.AutoNetwork.IsSet() {
		return true
	}

	return false
}

// SetAutoNetwork gets a reference to the given NullableBool and assigns it to the AutoNetwork field.
func (o *InstanceUpdateRequest) SetAutoNetwork(v bool) {
	o.AutoNetwork.Set(&v)
}

// SetAutoNetworkNil sets the value for AutoNetwork to be an explicit nil
func (o *InstanceUpdateRequest) SetAutoNetworkNil() {
	o.AutoNetwork.Set(nil)
}

// UnsetAutoNetwork ensures that no value is present for AutoNetwork, not even an explicit nil
func (o *InstanceUpdateRequest) UnsetAutoNetwork() {
	o.AutoNetwork.Unset()
}

// GetInfinibandInterfaces returns the InfinibandInterfaces field value if set, zero value otherwise.
func (o *InstanceUpdateRequest) GetInfinibandInterfaces() []InfiniBandInterfaceCreateRequest {
	if o == nil || IsNil(o.InfinibandInterfaces) {
		var ret []InfiniBandInterfaceCreateRequest
		return ret
	}
	return o.InfinibandInterfaces
}

// GetInfinibandInterfacesOk returns a tuple with the InfinibandInterfaces field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InstanceUpdateRequest) GetInfinibandInterfacesOk() ([]InfiniBandInterfaceCreateRequest, bool) {
	if o == nil || IsNil(o.InfinibandInterfaces) {
		return nil, false
	}
	return o.InfinibandInterfaces, true
}

// HasInfinibandInterfaces returns a boolean if a field has been set.
func (o *InstanceUpdateRequest) HasInfinibandInterfaces() bool {
	if o != nil && !IsNil(o.InfinibandInterfaces) {
		return true
	}

	return false
}

// SetInfinibandInterfaces gets a reference to the given []InfiniBandInterfaceCreateRequest and assigns it to the InfinibandInterfaces field.
func (o *InstanceUpdateRequest) SetInfinibandInterfaces(v []InfiniBandInterfaceCreateRequest) {
	o.InfinibandInterfaces = v
}

// GetNvLinkInterfaces returns the NvLinkInterfaces field value if set, zero value otherwise.
func (o *InstanceUpdateRequest) GetNvLinkInterfaces() []NVLinkInterfaceCreateOrUpdateRequest {
	if o == nil || IsNil(o.NvLinkInterfaces) {
		var ret []NVLinkInterfaceCreateOrUpdateRequest
		return ret
	}
	return o.NvLinkInterfaces
}

// GetNvLinkInterfacesOk returns a tuple with the NvLinkInterfaces field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InstanceUpdateRequest) GetNvLinkInterfacesOk() ([]NVLinkInterfaceCreateOrUpdateRequest, bool) {
	if o == nil || IsNil(o.NvLinkInterfaces) {
		return nil, false
	}
	return o.NvLinkInterfaces, true
}

// HasNvLinkInterfaces returns a boolean if a field has been set.
func (o *InstanceUpdateRequest) HasNvLinkInterfaces() bool {
	if o != nil && !IsNil(o.NvLinkInterfaces) {
		return true
	}

	return false
}

// SetNvLinkInterfaces gets a reference to the given []NVLinkInterfaceCreateOrUpdateRequest and assigns it to the NvLinkInterfaces field.
func (o *InstanceUpdateRequest) SetNvLinkInterfaces(v []NVLinkInterfaceCreateOrUpdateRequest) {
	o.NvLinkInterfaces = v
}

// GetDpuExtensionServiceDeployments returns the DpuExtensionServiceDeployments field value if set, zero value otherwise.
func (o *InstanceUpdateRequest) GetDpuExtensionServiceDeployments() []DpuExtensionServiceDeploymentRequest {
	if o == nil || IsNil(o.DpuExtensionServiceDeployments) {
		var ret []DpuExtensionServiceDeploymentRequest
		return ret
	}
	return o.DpuExtensionServiceDeployments
}

// GetDpuExtensionServiceDeploymentsOk returns a tuple with the DpuExtensionServiceDeployments field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InstanceUpdateRequest) GetDpuExtensionServiceDeploymentsOk() ([]DpuExtensionServiceDeploymentRequest, bool) {
	if o == nil || IsNil(o.DpuExtensionServiceDeployments) {
		return nil, false
	}
	return o.DpuExtensionServiceDeployments, true
}

// HasDpuExtensionServiceDeployments returns a boolean if a field has been set.
func (o *InstanceUpdateRequest) HasDpuExtensionServiceDeployments() bool {
	if o != nil && !IsNil(o.DpuExtensionServiceDeployments) {
		return true
	}

	return false
}

// SetDpuExtensionServiceDeployments gets a reference to the given []DpuExtensionServiceDeploymentRequest and assigns it to the DpuExtensionServiceDeployments field.
func (o *InstanceUpdateRequest) SetDpuExtensionServiceDeployments(v []DpuExtensionServiceDeploymentRequest) {
	o.DpuExtensionServiceDeployments = v
}

func (o InstanceUpdateRequest) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o InstanceUpdateRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.Name.IsSet() {
		toSerialize["name"] = o.Name.Get()
	}
	if o.Description.IsSet() {
		toSerialize["description"] = o.Description.Get()
	}
	if o.TriggerReboot.IsSet() {
		toSerialize["triggerReboot"] = o.TriggerReboot.Get()
	}
	if o.RebootWithCustomIpxe.IsSet() {
		toSerialize["rebootWithCustomIpxe"] = o.RebootWithCustomIpxe.Get()
	}
	if o.ApplyUpdatesOnReboot.IsSet() {
		toSerialize["applyUpdatesOnReboot"] = o.ApplyUpdatesOnReboot.Get()
	}
	if o.OperatingSystemId.IsSet() {
		toSerialize["operatingSystemId"] = o.OperatingSystemId.Get()
	}
	if o.IpxeScript.IsSet() {
		toSerialize["ipxeScript"] = o.IpxeScript.Get()
	}
	if !IsNil(o.SshKeyGroupIds) {
		toSerialize["sshKeyGroupIds"] = o.SshKeyGroupIds
	}
	if o.NetworkSecurityGroupId.IsSet() {
		toSerialize["networkSecurityGroupId"] = o.NetworkSecurityGroupId.Get()
	}
	if o.UserData.IsSet() {
		toSerialize["userData"] = o.UserData.Get()
	}
	if o.AlwaysBootWithCustomIpxe.IsSet() {
		toSerialize["alwaysBootWithCustomIpxe"] = o.AlwaysBootWithCustomIpxe.Get()
	}
	if o.PhoneHomeEnabled.IsSet() {
		toSerialize["phoneHomeEnabled"] = o.PhoneHomeEnabled.Get()
	}
	if !IsNil(o.Labels) {
		toSerialize["labels"] = o.Labels
	}
	if !IsNil(o.SecondaryVpcIds) {
		toSerialize["secondaryVpcIds"] = o.SecondaryVpcIds
	}
	if !IsNil(o.Interfaces) {
		toSerialize["interfaces"] = o.Interfaces
	}
	if o.AutoNetwork.IsSet() {
		toSerialize["autoNetwork"] = o.AutoNetwork.Get()
	}
	if !IsNil(o.InfinibandInterfaces) {
		toSerialize["infinibandInterfaces"] = o.InfinibandInterfaces
	}
	if !IsNil(o.NvLinkInterfaces) {
		toSerialize["nvLinkInterfaces"] = o.NvLinkInterfaces
	}
	if !IsNil(o.DpuExtensionServiceDeployments) {
		toSerialize["dpuExtensionServiceDeployments"] = o.DpuExtensionServiceDeployments
	}
	return toSerialize, nil
}

type NullableInstanceUpdateRequest struct {
	value *InstanceUpdateRequest
	isSet bool
}

func (v NullableInstanceUpdateRequest) Get() *InstanceUpdateRequest {
	return v.value
}

func (v *NullableInstanceUpdateRequest) Set(val *InstanceUpdateRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableInstanceUpdateRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableInstanceUpdateRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableInstanceUpdateRequest(val *InstanceUpdateRequest) *NullableInstanceUpdateRequest {
	return &NullableInstanceUpdateRequest{value: val, isSet: true}
}

func (v NullableInstanceUpdateRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableInstanceUpdateRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
