// SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
// SPDX-License-Identifier: Apache-2.0

/*
NVIDIA Infra Controller REST API

NVIDIA Infra Controller REST API allows users to create and manage resources, e.g., VPCs, Subnets, and Instances, across all connected NVIDIA Infra Controller datacenters, also referred to as Sites.

API version: 2.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package standard

import (
	"encoding/json"
)

// checks if the ExpectedRackUpdateRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ExpectedRackUpdateRequest{}

// ExpectedRackUpdateRequest Request data to update an existing Expected Rack.  For single updates (PATCH /expected-rack/{id}), the `id` field is optional in the body and will be ignored if provided (the `id` from the URL path is used).  Chassis identity and physical location information are conveyed via well-known label keys in `labels`: - `chassis.manufacturer`, `chassis.serial-number`, `chassis.model` - `location.region`, `location.datacenter`, `location.room`, `location.position`
type ExpectedRackUpdateRequest struct {
	// Unique identifier (UUID) of the Expected Rack to update. Optional for single Expected Rack update (must be empty or match the id from the URL path).
	Id NullableString `json:"id,omitempty"`
	// Optional new operator-supplied rack identifier. If provided, must be non-empty and unique within the Site.
	RackId NullableString `json:"rackId,omitempty"`
	// Optional new Rack Profile identifier. If provided, must be non-empty.
	RackProfileId NullableString `json:"rackProfileId,omitempty"`
	// Human-readable name of the Expected Rack
	Name NullableString `json:"name,omitempty"`
	// Human-readable description of the Expected Rack
	Description NullableString `json:"description,omitempty"`
	// User-defined key-value pairs for organizing and categorizing Expected Racks. Well-known keys (`chassis.*`, `location.*`) are used to convey chassis identity and physical location.
	Labels map[string]string `json:"labels,omitempty"`
}

// NewExpectedRackUpdateRequest instantiates a new ExpectedRackUpdateRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewExpectedRackUpdateRequest() *ExpectedRackUpdateRequest {
	this := ExpectedRackUpdateRequest{}
	return &this
}

// NewExpectedRackUpdateRequestWithDefaults instantiates a new ExpectedRackUpdateRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewExpectedRackUpdateRequestWithDefaults() *ExpectedRackUpdateRequest {
	this := ExpectedRackUpdateRequest{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ExpectedRackUpdateRequest) GetId() string {
	if o == nil || IsNil(o.Id.Get()) {
		var ret string
		return ret
	}
	return *o.Id.Get()
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ExpectedRackUpdateRequest) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Id.Get(), o.Id.IsSet()
}

// HasId returns a boolean if a field has been set.
func (o *ExpectedRackUpdateRequest) HasId() bool {
	if o != nil && o.Id.IsSet() {
		return true
	}

	return false
}

// SetId gets a reference to the given NullableString and assigns it to the Id field.
func (o *ExpectedRackUpdateRequest) SetId(v string) {
	o.Id.Set(&v)
}

// SetIdNil sets the value for Id to be an explicit nil
func (o *ExpectedRackUpdateRequest) SetIdNil() {
	o.Id.Set(nil)
}

// UnsetId ensures that no value is present for Id, not even an explicit nil
func (o *ExpectedRackUpdateRequest) UnsetId() {
	o.Id.Unset()
}

// GetRackId returns the RackId field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ExpectedRackUpdateRequest) GetRackId() string {
	if o == nil || IsNil(o.RackId.Get()) {
		var ret string
		return ret
	}
	return *o.RackId.Get()
}

// GetRackIdOk returns a tuple with the RackId field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ExpectedRackUpdateRequest) GetRackIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.RackId.Get(), o.RackId.IsSet()
}

// HasRackId returns a boolean if a field has been set.
func (o *ExpectedRackUpdateRequest) HasRackId() bool {
	if o != nil && o.RackId.IsSet() {
		return true
	}

	return false
}

// SetRackId gets a reference to the given NullableString and assigns it to the RackId field.
func (o *ExpectedRackUpdateRequest) SetRackId(v string) {
	o.RackId.Set(&v)
}

// SetRackIdNil sets the value for RackId to be an explicit nil
func (o *ExpectedRackUpdateRequest) SetRackIdNil() {
	o.RackId.Set(nil)
}

// UnsetRackId ensures that no value is present for RackId, not even an explicit nil
func (o *ExpectedRackUpdateRequest) UnsetRackId() {
	o.RackId.Unset()
}

// GetRackProfileId returns the RackProfileId field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ExpectedRackUpdateRequest) GetRackProfileId() string {
	if o == nil || IsNil(o.RackProfileId.Get()) {
		var ret string
		return ret
	}
	return *o.RackProfileId.Get()
}

// GetRackProfileIdOk returns a tuple with the RackProfileId field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ExpectedRackUpdateRequest) GetRackProfileIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.RackProfileId.Get(), o.RackProfileId.IsSet()
}

// HasRackProfileId returns a boolean if a field has been set.
func (o *ExpectedRackUpdateRequest) HasRackProfileId() bool {
	if o != nil && o.RackProfileId.IsSet() {
		return true
	}

	return false
}

// SetRackProfileId gets a reference to the given NullableString and assigns it to the RackProfileId field.
func (o *ExpectedRackUpdateRequest) SetRackProfileId(v string) {
	o.RackProfileId.Set(&v)
}

// SetRackProfileIdNil sets the value for RackProfileId to be an explicit nil
func (o *ExpectedRackUpdateRequest) SetRackProfileIdNil() {
	o.RackProfileId.Set(nil)
}

// UnsetRackProfileId ensures that no value is present for RackProfileId, not even an explicit nil
func (o *ExpectedRackUpdateRequest) UnsetRackProfileId() {
	o.RackProfileId.Unset()
}

// GetName returns the Name field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ExpectedRackUpdateRequest) GetName() string {
	if o == nil || IsNil(o.Name.Get()) {
		var ret string
		return ret
	}
	return *o.Name.Get()
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ExpectedRackUpdateRequest) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Name.Get(), o.Name.IsSet()
}

// HasName returns a boolean if a field has been set.
func (o *ExpectedRackUpdateRequest) HasName() bool {
	if o != nil && o.Name.IsSet() {
		return true
	}

	return false
}

// SetName gets a reference to the given NullableString and assigns it to the Name field.
func (o *ExpectedRackUpdateRequest) SetName(v string) {
	o.Name.Set(&v)
}

// SetNameNil sets the value for Name to be an explicit nil
func (o *ExpectedRackUpdateRequest) SetNameNil() {
	o.Name.Set(nil)
}

// UnsetName ensures that no value is present for Name, not even an explicit nil
func (o *ExpectedRackUpdateRequest) UnsetName() {
	o.Name.Unset()
}

// GetDescription returns the Description field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ExpectedRackUpdateRequest) GetDescription() string {
	if o == nil || IsNil(o.Description.Get()) {
		var ret string
		return ret
	}
	return *o.Description.Get()
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ExpectedRackUpdateRequest) GetDescriptionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Description.Get(), o.Description.IsSet()
}

// HasDescription returns a boolean if a field has been set.
func (o *ExpectedRackUpdateRequest) HasDescription() bool {
	if o != nil && o.Description.IsSet() {
		return true
	}

	return false
}

// SetDescription gets a reference to the given NullableString and assigns it to the Description field.
func (o *ExpectedRackUpdateRequest) SetDescription(v string) {
	o.Description.Set(&v)
}

// SetDescriptionNil sets the value for Description to be an explicit nil
func (o *ExpectedRackUpdateRequest) SetDescriptionNil() {
	o.Description.Set(nil)
}

// UnsetDescription ensures that no value is present for Description, not even an explicit nil
func (o *ExpectedRackUpdateRequest) UnsetDescription() {
	o.Description.Unset()
}

// GetLabels returns the Labels field value if set, zero value otherwise.
func (o *ExpectedRackUpdateRequest) GetLabels() map[string]string {
	if o == nil || IsNil(o.Labels) {
		var ret map[string]string
		return ret
	}
	return o.Labels
}

// GetLabelsOk returns a tuple with the Labels field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ExpectedRackUpdateRequest) GetLabelsOk() (map[string]string, bool) {
	if o == nil || IsNil(o.Labels) {
		return map[string]string{}, false
	}
	return o.Labels, true
}

// HasLabels returns a boolean if a field has been set.
func (o *ExpectedRackUpdateRequest) HasLabels() bool {
	if o != nil && !IsNil(o.Labels) {
		return true
	}

	return false
}

// SetLabels gets a reference to the given map[string]string and assigns it to the Labels field.
func (o *ExpectedRackUpdateRequest) SetLabels(v map[string]string) {
	o.Labels = v
}

func (o ExpectedRackUpdateRequest) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ExpectedRackUpdateRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.Id.IsSet() {
		toSerialize["id"] = o.Id.Get()
	}
	if o.RackId.IsSet() {
		toSerialize["rackId"] = o.RackId.Get()
	}
	if o.RackProfileId.IsSet() {
		toSerialize["rackProfileId"] = o.RackProfileId.Get()
	}
	if o.Name.IsSet() {
		toSerialize["name"] = o.Name.Get()
	}
	if o.Description.IsSet() {
		toSerialize["description"] = o.Description.Get()
	}
	if !IsNil(o.Labels) {
		toSerialize["labels"] = o.Labels
	}
	return toSerialize, nil
}

type NullableExpectedRackUpdateRequest struct {
	value *ExpectedRackUpdateRequest
	isSet bool
}

func (v NullableExpectedRackUpdateRequest) Get() *ExpectedRackUpdateRequest {
	return v.value
}

func (v *NullableExpectedRackUpdateRequest) Set(val *ExpectedRackUpdateRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableExpectedRackUpdateRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableExpectedRackUpdateRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableExpectedRackUpdateRequest(val *ExpectedRackUpdateRequest) *NullableExpectedRackUpdateRequest {
	return &NullableExpectedRackUpdateRequest{value: val, isSet: true}
}

func (v NullableExpectedRackUpdateRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableExpectedRackUpdateRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
