// SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
// SPDX-License-Identifier: Apache-2.0

/*
NVIDIA Infra Controller REST API

NVIDIA Infra Controller REST API allows users to create and manage resources, e.g., VPCs, Subnets, and Instances, across all connected NVIDIA Infra Controller datacenters, also referred to as Sites.

API version: 2.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package standard

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the InstanceCreateRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &InstanceCreateRequest{}

// InstanceCreateRequest Request data to create Instance
type InstanceCreateRequest struct {
	// Name of the Instance
	Name string `json:"name"`
	// Description of the Instance, optional
	Description NullableString `json:"description,omitempty"`
	// ID of the Tenant creating the Instance
	TenantId string `json:"tenantId"`
	// ID of the Instance Type to use for Instance
	InstanceTypeId NullableString `json:"instanceTypeId,omitempty"`
	// ID of of specific Machine to use for Instance. Requires Targeted Instance Creation capability enabled for Tenant
	MachineId NullableString `json:"machineId,omitempty"`
	// ID of the VPC the Instance should belong to
	VpcId string `json:"vpcId"`
	// IDs of additional VPCs the Instance should attach to through non-primary interfaces. This field may only be specified when every entry in `interfaces` uses `vpcPrefixId`. IDs must be unique, must be valid UUIDs, and must not include the primary `vpcId`.
	SecondaryVpcIds []string `json:"secondaryVpcIds,omitempty"`
	// Can only be specified if allowOverride is set to true in Operating System
	UserData NullableString `json:"userData,omitempty"`
	// Must be specified if iPXE Script field is empty
	OperatingSystemId NullableString `json:"operatingSystemId,omitempty"`
	// ID of the desired Network Security Group to attach to the Instance
	NetworkSecurityGroupId NullableString `json:"networkSecurityGroupId,omitempty"`
	// Override iPXE script specified in OS, must be specified if Operating System is not specified
	IpxeScript NullableString `json:"ipxeScript,omitempty"`
	// When set to true, the iPXE script specified by OS or overridden here will always be run when rebooting the Instance. OS must be of iPXE type.
	AlwaysBootWithCustomIpxe *bool `json:"alwaysBootWithCustomIpxe,omitempty"`
	// When set to true, the Instance will be enabled with the Phone Home service.
	PhoneHomeEnabled *bool `json:"phoneHomeEnabled,omitempty"`
	// User-defined key-value labels
	Labels map[string]string `json:"labels,omitempty"`
	// At least one interface must be specified unless `autoNetwork` is true. Either Subnet or VPC Prefix interfaces allowed. Only one of the Subnets or VPC Prefixes can be attached over Physical interface. If only one Subnet is specified, then it will be attached over physical interface regardless of the value of isPhysical. In case of VPC Prefix, isPhysical will always be true. Mutually exclusive with `autoNetwork`: when `autoNetwork` is true this list MUST be empty.
	Interfaces []InterfaceCreateRequest `json:"interfaces,omitempty"`
	// When true, asks NICo to auto-resolve the Instance's network interfaces from the host's underlay (HostInband) network segments. Intended for instances on zero-DPU hosts (or hosts with their DPU in NIC mode). When true: (1) the target VPC's `networkVirtualizationType` MUST be `FLAT`, (2) `interfaces` MUST be empty or omitted, and (3) `secondaryVpcIds` MUST be empty or omitted. Resolved interfaces surface on the Instance's read response.
	AutoNetwork *bool `json:"autoNetwork,omitempty"`
	// Associate one or more Partitions with this Instance
	InfinibandInterfaces []InfiniBandInterfaceCreateRequest `json:"infinibandInterfaces,omitempty"`
	// DPU Extension Services to deploy to the DPUs of this Instance
	DpuExtensionServiceDeployments []DpuExtensionServiceDeploymentRequest `json:"dpuExtensionServiceDeployments,omitempty"`
	// Define Interfaces to associate Instance GPUs with NVLink Logical Partitions. A subset of GPUs may be specified (it is not required to include all GPUs). Each item references one GPU index (`deviceInstance`) and one NVLink Logical Partition. Different interfaces may reference different NVLink Logical Partitions.
	NvLinkInterfaces []NVLinkInterfaceCreateOrUpdateRequest `json:"nvLinkInterfaces,omitempty"`
	// Specify list of SSH Key Group IDs that will provide Serial over LAN access
	SshKeyGroupIds []string `json:"sshKeyGroupIds,omitempty"`
	// Set to true in order to target Machines are in maintenance or have health alerts preventing regular provision flow. Requires Targeted Instance Creation capability enabled for Tenant
	AllowUnhealthyMachine *bool `json:"allowUnhealthyMachine,omitempty"`
}

type _InstanceCreateRequest InstanceCreateRequest

// NewInstanceCreateRequest instantiates a new InstanceCreateRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewInstanceCreateRequest(name string, tenantId string, vpcId string) *InstanceCreateRequest {
	this := InstanceCreateRequest{}
	this.Name = name
	this.TenantId = tenantId
	this.VpcId = vpcId
	return &this
}

// NewInstanceCreateRequestWithDefaults instantiates a new InstanceCreateRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewInstanceCreateRequestWithDefaults() *InstanceCreateRequest {
	this := InstanceCreateRequest{}
	return &this
}

// GetName returns the Name field value
func (o *InstanceCreateRequest) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *InstanceCreateRequest) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *InstanceCreateRequest) SetName(v string) {
	o.Name = v
}

// GetDescription returns the Description field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *InstanceCreateRequest) GetDescription() string {
	if o == nil || IsNil(o.Description.Get()) {
		var ret string
		return ret
	}
	return *o.Description.Get()
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *InstanceCreateRequest) GetDescriptionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Description.Get(), o.Description.IsSet()
}

// HasDescription returns a boolean if a field has been set.
func (o *InstanceCreateRequest) HasDescription() bool {
	if o != nil && o.Description.IsSet() {
		return true
	}

	return false
}

// SetDescription gets a reference to the given NullableString and assigns it to the Description field.
func (o *InstanceCreateRequest) SetDescription(v string) {
	o.Description.Set(&v)
}

// SetDescriptionNil sets the value for Description to be an explicit nil
func (o *InstanceCreateRequest) SetDescriptionNil() {
	o.Description.Set(nil)
}

// UnsetDescription ensures that no value is present for Description, not even an explicit nil
func (o *InstanceCreateRequest) UnsetDescription() {
	o.Description.Unset()
}

// GetTenantId returns the TenantId field value
func (o *InstanceCreateRequest) GetTenantId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.TenantId
}

// GetTenantIdOk returns a tuple with the TenantId field value
// and a boolean to check if the value has been set.
func (o *InstanceCreateRequest) GetTenantIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TenantId, true
}

// SetTenantId sets field value
func (o *InstanceCreateRequest) SetTenantId(v string) {
	o.TenantId = v
}

// GetInstanceTypeId returns the InstanceTypeId field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *InstanceCreateRequest) GetInstanceTypeId() string {
	if o == nil || IsNil(o.InstanceTypeId.Get()) {
		var ret string
		return ret
	}
	return *o.InstanceTypeId.Get()
}

// GetInstanceTypeIdOk returns a tuple with the InstanceTypeId field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *InstanceCreateRequest) GetInstanceTypeIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.InstanceTypeId.Get(), o.InstanceTypeId.IsSet()
}

// HasInstanceTypeId returns a boolean if a field has been set.
func (o *InstanceCreateRequest) HasInstanceTypeId() bool {
	if o != nil && o.InstanceTypeId.IsSet() {
		return true
	}

	return false
}

// SetInstanceTypeId gets a reference to the given NullableString and assigns it to the InstanceTypeId field.
func (o *InstanceCreateRequest) SetInstanceTypeId(v string) {
	o.InstanceTypeId.Set(&v)
}

// SetInstanceTypeIdNil sets the value for InstanceTypeId to be an explicit nil
func (o *InstanceCreateRequest) SetInstanceTypeIdNil() {
	o.InstanceTypeId.Set(nil)
}

// UnsetInstanceTypeId ensures that no value is present for InstanceTypeId, not even an explicit nil
func (o *InstanceCreateRequest) UnsetInstanceTypeId() {
	o.InstanceTypeId.Unset()
}

// GetMachineId returns the MachineId field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *InstanceCreateRequest) GetMachineId() string {
	if o == nil || IsNil(o.MachineId.Get()) {
		var ret string
		return ret
	}
	return *o.MachineId.Get()
}

// GetMachineIdOk returns a tuple with the MachineId field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *InstanceCreateRequest) GetMachineIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.MachineId.Get(), o.MachineId.IsSet()
}

// HasMachineId returns a boolean if a field has been set.
func (o *InstanceCreateRequest) HasMachineId() bool {
	if o != nil && o.MachineId.IsSet() {
		return true
	}

	return false
}

// SetMachineId gets a reference to the given NullableString and assigns it to the MachineId field.
func (o *InstanceCreateRequest) SetMachineId(v string) {
	o.MachineId.Set(&v)
}

// SetMachineIdNil sets the value for MachineId to be an explicit nil
func (o *InstanceCreateRequest) SetMachineIdNil() {
	o.MachineId.Set(nil)
}

// UnsetMachineId ensures that no value is present for MachineId, not even an explicit nil
func (o *InstanceCreateRequest) UnsetMachineId() {
	o.MachineId.Unset()
}

// GetVpcId returns the VpcId field value
func (o *InstanceCreateRequest) GetVpcId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.VpcId
}

// GetVpcIdOk returns a tuple with the VpcId field value
// and a boolean to check if the value has been set.
func (o *InstanceCreateRequest) GetVpcIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.VpcId, true
}

// SetVpcId sets field value
func (o *InstanceCreateRequest) SetVpcId(v string) {
	o.VpcId = v
}

// GetSecondaryVpcIds returns the SecondaryVpcIds field value if set, zero value otherwise.
func (o *InstanceCreateRequest) GetSecondaryVpcIds() []string {
	if o == nil || IsNil(o.SecondaryVpcIds) {
		var ret []string
		return ret
	}
	return o.SecondaryVpcIds
}

// GetSecondaryVpcIdsOk returns a tuple with the SecondaryVpcIds field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InstanceCreateRequest) GetSecondaryVpcIdsOk() ([]string, bool) {
	if o == nil || IsNil(o.SecondaryVpcIds) {
		return nil, false
	}
	return o.SecondaryVpcIds, true
}

// HasSecondaryVpcIds returns a boolean if a field has been set.
func (o *InstanceCreateRequest) HasSecondaryVpcIds() bool {
	if o != nil && !IsNil(o.SecondaryVpcIds) {
		return true
	}

	return false
}

// SetSecondaryVpcIds gets a reference to the given []string and assigns it to the SecondaryVpcIds field.
func (o *InstanceCreateRequest) SetSecondaryVpcIds(v []string) {
	o.SecondaryVpcIds = v
}

// GetUserData returns the UserData field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *InstanceCreateRequest) GetUserData() string {
	if o == nil || IsNil(o.UserData.Get()) {
		var ret string
		return ret
	}
	return *o.UserData.Get()
}

// GetUserDataOk returns a tuple with the UserData field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *InstanceCreateRequest) GetUserDataOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.UserData.Get(), o.UserData.IsSet()
}

// HasUserData returns a boolean if a field has been set.
func (o *InstanceCreateRequest) HasUserData() bool {
	if o != nil && o.UserData.IsSet() {
		return true
	}

	return false
}

// SetUserData gets a reference to the given NullableString and assigns it to the UserData field.
func (o *InstanceCreateRequest) SetUserData(v string) {
	o.UserData.Set(&v)
}

// SetUserDataNil sets the value for UserData to be an explicit nil
func (o *InstanceCreateRequest) SetUserDataNil() {
	o.UserData.Set(nil)
}

// UnsetUserData ensures that no value is present for UserData, not even an explicit nil
func (o *InstanceCreateRequest) UnsetUserData() {
	o.UserData.Unset()
}

// GetOperatingSystemId returns the OperatingSystemId field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *InstanceCreateRequest) GetOperatingSystemId() string {
	if o == nil || IsNil(o.OperatingSystemId.Get()) {
		var ret string
		return ret
	}
	return *o.OperatingSystemId.Get()
}

// GetOperatingSystemIdOk returns a tuple with the OperatingSystemId field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *InstanceCreateRequest) GetOperatingSystemIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.OperatingSystemId.Get(), o.OperatingSystemId.IsSet()
}

// HasOperatingSystemId returns a boolean if a field has been set.
func (o *InstanceCreateRequest) HasOperatingSystemId() bool {
	if o != nil && o.OperatingSystemId.IsSet() {
		return true
	}

	return false
}

// SetOperatingSystemId gets a reference to the given NullableString and assigns it to the OperatingSystemId field.
func (o *InstanceCreateRequest) SetOperatingSystemId(v string) {
	o.OperatingSystemId.Set(&v)
}

// SetOperatingSystemIdNil sets the value for OperatingSystemId to be an explicit nil
func (o *InstanceCreateRequest) SetOperatingSystemIdNil() {
	o.OperatingSystemId.Set(nil)
}

// UnsetOperatingSystemId ensures that no value is present for OperatingSystemId, not even an explicit nil
func (o *InstanceCreateRequest) UnsetOperatingSystemId() {
	o.OperatingSystemId.Unset()
}

// GetNetworkSecurityGroupId returns the NetworkSecurityGroupId field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *InstanceCreateRequest) GetNetworkSecurityGroupId() string {
	if o == nil || IsNil(o.NetworkSecurityGroupId.Get()) {
		var ret string
		return ret
	}
	return *o.NetworkSecurityGroupId.Get()
}

// GetNetworkSecurityGroupIdOk returns a tuple with the NetworkSecurityGroupId field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *InstanceCreateRequest) GetNetworkSecurityGroupIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.NetworkSecurityGroupId.Get(), o.NetworkSecurityGroupId.IsSet()
}

// HasNetworkSecurityGroupId returns a boolean if a field has been set.
func (o *InstanceCreateRequest) HasNetworkSecurityGroupId() bool {
	if o != nil && o.NetworkSecurityGroupId.IsSet() {
		return true
	}

	return false
}

// SetNetworkSecurityGroupId gets a reference to the given NullableString and assigns it to the NetworkSecurityGroupId field.
func (o *InstanceCreateRequest) SetNetworkSecurityGroupId(v string) {
	o.NetworkSecurityGroupId.Set(&v)
}

// SetNetworkSecurityGroupIdNil sets the value for NetworkSecurityGroupId to be an explicit nil
func (o *InstanceCreateRequest) SetNetworkSecurityGroupIdNil() {
	o.NetworkSecurityGroupId.Set(nil)
}

// UnsetNetworkSecurityGroupId ensures that no value is present for NetworkSecurityGroupId, not even an explicit nil
func (o *InstanceCreateRequest) UnsetNetworkSecurityGroupId() {
	o.NetworkSecurityGroupId.Unset()
}

// GetIpxeScript returns the IpxeScript field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *InstanceCreateRequest) GetIpxeScript() string {
	if o == nil || IsNil(o.IpxeScript.Get()) {
		var ret string
		return ret
	}
	return *o.IpxeScript.Get()
}

// GetIpxeScriptOk returns a tuple with the IpxeScript field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *InstanceCreateRequest) GetIpxeScriptOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.IpxeScript.Get(), o.IpxeScript.IsSet()
}

// HasIpxeScript returns a boolean if a field has been set.
func (o *InstanceCreateRequest) HasIpxeScript() bool {
	if o != nil && o.IpxeScript.IsSet() {
		return true
	}

	return false
}

// SetIpxeScript gets a reference to the given NullableString and assigns it to the IpxeScript field.
func (o *InstanceCreateRequest) SetIpxeScript(v string) {
	o.IpxeScript.Set(&v)
}

// SetIpxeScriptNil sets the value for IpxeScript to be an explicit nil
func (o *InstanceCreateRequest) SetIpxeScriptNil() {
	o.IpxeScript.Set(nil)
}

// UnsetIpxeScript ensures that no value is present for IpxeScript, not even an explicit nil
func (o *InstanceCreateRequest) UnsetIpxeScript() {
	o.IpxeScript.Unset()
}

// GetAlwaysBootWithCustomIpxe returns the AlwaysBootWithCustomIpxe field value if set, zero value otherwise.
func (o *InstanceCreateRequest) GetAlwaysBootWithCustomIpxe() bool {
	if o == nil || IsNil(o.AlwaysBootWithCustomIpxe) {
		var ret bool
		return ret
	}
	return *o.AlwaysBootWithCustomIpxe
}

// GetAlwaysBootWithCustomIpxeOk returns a tuple with the AlwaysBootWithCustomIpxe field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InstanceCreateRequest) GetAlwaysBootWithCustomIpxeOk() (*bool, bool) {
	if o == nil || IsNil(o.AlwaysBootWithCustomIpxe) {
		return nil, false
	}
	return o.AlwaysBootWithCustomIpxe, true
}

// HasAlwaysBootWithCustomIpxe returns a boolean if a field has been set.
func (o *InstanceCreateRequest) HasAlwaysBootWithCustomIpxe() bool {
	if o != nil && !IsNil(o.AlwaysBootWithCustomIpxe) {
		return true
	}

	return false
}

// SetAlwaysBootWithCustomIpxe gets a reference to the given bool and assigns it to the AlwaysBootWithCustomIpxe field.
func (o *InstanceCreateRequest) SetAlwaysBootWithCustomIpxe(v bool) {
	o.AlwaysBootWithCustomIpxe = &v
}

// GetPhoneHomeEnabled returns the PhoneHomeEnabled field value if set, zero value otherwise.
func (o *InstanceCreateRequest) GetPhoneHomeEnabled() bool {
	if o == nil || IsNil(o.PhoneHomeEnabled) {
		var ret bool
		return ret
	}
	return *o.PhoneHomeEnabled
}

// GetPhoneHomeEnabledOk returns a tuple with the PhoneHomeEnabled field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InstanceCreateRequest) GetPhoneHomeEnabledOk() (*bool, bool) {
	if o == nil || IsNil(o.PhoneHomeEnabled) {
		return nil, false
	}
	return o.PhoneHomeEnabled, true
}

// HasPhoneHomeEnabled returns a boolean if a field has been set.
func (o *InstanceCreateRequest) HasPhoneHomeEnabled() bool {
	if o != nil && !IsNil(o.PhoneHomeEnabled) {
		return true
	}

	return false
}

// SetPhoneHomeEnabled gets a reference to the given bool and assigns it to the PhoneHomeEnabled field.
func (o *InstanceCreateRequest) SetPhoneHomeEnabled(v bool) {
	o.PhoneHomeEnabled = &v
}

// GetLabels returns the Labels field value if set, zero value otherwise.
func (o *InstanceCreateRequest) GetLabels() map[string]string {
	if o == nil || IsNil(o.Labels) {
		var ret map[string]string
		return ret
	}
	return o.Labels
}

// GetLabelsOk returns a tuple with the Labels field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InstanceCreateRequest) GetLabelsOk() (map[string]string, bool) {
	if o == nil || IsNil(o.Labels) {
		return map[string]string{}, false
	}
	return o.Labels, true
}

// HasLabels returns a boolean if a field has been set.
func (o *InstanceCreateRequest) HasLabels() bool {
	if o != nil && !IsNil(o.Labels) {
		return true
	}

	return false
}

// SetLabels gets a reference to the given map[string]string and assigns it to the Labels field.
func (o *InstanceCreateRequest) SetLabels(v map[string]string) {
	o.Labels = v
}

// GetInterfaces returns the Interfaces field value if set, zero value otherwise.
func (o *InstanceCreateRequest) GetInterfaces() []InterfaceCreateRequest {
	if o == nil || IsNil(o.Interfaces) {
		var ret []InterfaceCreateRequest
		return ret
	}
	return o.Interfaces
}

// GetInterfacesOk returns a tuple with the Interfaces field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InstanceCreateRequest) GetInterfacesOk() ([]InterfaceCreateRequest, bool) {
	if o == nil || IsNil(o.Interfaces) {
		return nil, false
	}
	return o.Interfaces, true
}

// HasInterfaces returns a boolean if a field has been set.
func (o *InstanceCreateRequest) HasInterfaces() bool {
	if o != nil && !IsNil(o.Interfaces) {
		return true
	}

	return false
}

// SetInterfaces gets a reference to the given []InterfaceCreateRequest and assigns it to the Interfaces field.
func (o *InstanceCreateRequest) SetInterfaces(v []InterfaceCreateRequest) {
	o.Interfaces = v
}

// GetAutoNetwork returns the AutoNetwork field value if set, zero value otherwise.
func (o *InstanceCreateRequest) GetAutoNetwork() bool {
	if o == nil || IsNil(o.AutoNetwork) {
		var ret bool
		return ret
	}
	return *o.AutoNetwork
}

// GetAutoNetworkOk returns a tuple with the AutoNetwork field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InstanceCreateRequest) GetAutoNetworkOk() (*bool, bool) {
	if o == nil || IsNil(o.AutoNetwork) {
		return nil, false
	}
	return o.AutoNetwork, true
}

// HasAutoNetwork returns a boolean if a field has been set.
func (o *InstanceCreateRequest) HasAutoNetwork() bool {
	if o != nil && !IsNil(o.AutoNetwork) {
		return true
	}

	return false
}

// SetAutoNetwork gets a reference to the given bool and assigns it to the AutoNetwork field.
func (o *InstanceCreateRequest) SetAutoNetwork(v bool) {
	o.AutoNetwork = &v
}

// GetInfinibandInterfaces returns the InfinibandInterfaces field value if set, zero value otherwise.
func (o *InstanceCreateRequest) GetInfinibandInterfaces() []InfiniBandInterfaceCreateRequest {
	if o == nil || IsNil(o.InfinibandInterfaces) {
		var ret []InfiniBandInterfaceCreateRequest
		return ret
	}
	return o.InfinibandInterfaces
}

// GetInfinibandInterfacesOk returns a tuple with the InfinibandInterfaces field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InstanceCreateRequest) GetInfinibandInterfacesOk() ([]InfiniBandInterfaceCreateRequest, bool) {
	if o == nil || IsNil(o.InfinibandInterfaces) {
		return nil, false
	}
	return o.InfinibandInterfaces, true
}

// HasInfinibandInterfaces returns a boolean if a field has been set.
func (o *InstanceCreateRequest) HasInfinibandInterfaces() bool {
	if o != nil && !IsNil(o.InfinibandInterfaces) {
		return true
	}

	return false
}

// SetInfinibandInterfaces gets a reference to the given []InfiniBandInterfaceCreateRequest and assigns it to the InfinibandInterfaces field.
func (o *InstanceCreateRequest) SetInfinibandInterfaces(v []InfiniBandInterfaceCreateRequest) {
	o.InfinibandInterfaces = v
}

// GetDpuExtensionServiceDeployments returns the DpuExtensionServiceDeployments field value if set, zero value otherwise.
func (o *InstanceCreateRequest) GetDpuExtensionServiceDeployments() []DpuExtensionServiceDeploymentRequest {
	if o == nil || IsNil(o.DpuExtensionServiceDeployments) {
		var ret []DpuExtensionServiceDeploymentRequest
		return ret
	}
	return o.DpuExtensionServiceDeployments
}

// GetDpuExtensionServiceDeploymentsOk returns a tuple with the DpuExtensionServiceDeployments field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InstanceCreateRequest) GetDpuExtensionServiceDeploymentsOk() ([]DpuExtensionServiceDeploymentRequest, bool) {
	if o == nil || IsNil(o.DpuExtensionServiceDeployments) {
		return nil, false
	}
	return o.DpuExtensionServiceDeployments, true
}

// HasDpuExtensionServiceDeployments returns a boolean if a field has been set.
func (o *InstanceCreateRequest) HasDpuExtensionServiceDeployments() bool {
	if o != nil && !IsNil(o.DpuExtensionServiceDeployments) {
		return true
	}

	return false
}

// SetDpuExtensionServiceDeployments gets a reference to the given []DpuExtensionServiceDeploymentRequest and assigns it to the DpuExtensionServiceDeployments field.
func (o *InstanceCreateRequest) SetDpuExtensionServiceDeployments(v []DpuExtensionServiceDeploymentRequest) {
	o.DpuExtensionServiceDeployments = v
}

// GetNvLinkInterfaces returns the NvLinkInterfaces field value if set, zero value otherwise.
func (o *InstanceCreateRequest) GetNvLinkInterfaces() []NVLinkInterfaceCreateOrUpdateRequest {
	if o == nil || IsNil(o.NvLinkInterfaces) {
		var ret []NVLinkInterfaceCreateOrUpdateRequest
		return ret
	}
	return o.NvLinkInterfaces
}

// GetNvLinkInterfacesOk returns a tuple with the NvLinkInterfaces field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InstanceCreateRequest) GetNvLinkInterfacesOk() ([]NVLinkInterfaceCreateOrUpdateRequest, bool) {
	if o == nil || IsNil(o.NvLinkInterfaces) {
		return nil, false
	}
	return o.NvLinkInterfaces, true
}

// HasNvLinkInterfaces returns a boolean if a field has been set.
func (o *InstanceCreateRequest) HasNvLinkInterfaces() bool {
	if o != nil && !IsNil(o.NvLinkInterfaces) {
		return true
	}

	return false
}

// SetNvLinkInterfaces gets a reference to the given []NVLinkInterfaceCreateOrUpdateRequest and assigns it to the NvLinkInterfaces field.
func (o *InstanceCreateRequest) SetNvLinkInterfaces(v []NVLinkInterfaceCreateOrUpdateRequest) {
	o.NvLinkInterfaces = v
}

// GetSshKeyGroupIds returns the SshKeyGroupIds field value if set, zero value otherwise.
func (o *InstanceCreateRequest) GetSshKeyGroupIds() []string {
	if o == nil || IsNil(o.SshKeyGroupIds) {
		var ret []string
		return ret
	}
	return o.SshKeyGroupIds
}

// GetSshKeyGroupIdsOk returns a tuple with the SshKeyGroupIds field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InstanceCreateRequest) GetSshKeyGroupIdsOk() ([]string, bool) {
	if o == nil || IsNil(o.SshKeyGroupIds) {
		return nil, false
	}
	return o.SshKeyGroupIds, true
}

// HasSshKeyGroupIds returns a boolean if a field has been set.
func (o *InstanceCreateRequest) HasSshKeyGroupIds() bool {
	if o != nil && !IsNil(o.SshKeyGroupIds) {
		return true
	}

	return false
}

// SetSshKeyGroupIds gets a reference to the given []string and assigns it to the SshKeyGroupIds field.
func (o *InstanceCreateRequest) SetSshKeyGroupIds(v []string) {
	o.SshKeyGroupIds = v
}

// GetAllowUnhealthyMachine returns the AllowUnhealthyMachine field value if set, zero value otherwise.
func (o *InstanceCreateRequest) GetAllowUnhealthyMachine() bool {
	if o == nil || IsNil(o.AllowUnhealthyMachine) {
		var ret bool
		return ret
	}
	return *o.AllowUnhealthyMachine
}

// GetAllowUnhealthyMachineOk returns a tuple with the AllowUnhealthyMachine field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InstanceCreateRequest) GetAllowUnhealthyMachineOk() (*bool, bool) {
	if o == nil || IsNil(o.AllowUnhealthyMachine) {
		return nil, false
	}
	return o.AllowUnhealthyMachine, true
}

// HasAllowUnhealthyMachine returns a boolean if a field has been set.
func (o *InstanceCreateRequest) HasAllowUnhealthyMachine() bool {
	if o != nil && !IsNil(o.AllowUnhealthyMachine) {
		return true
	}

	return false
}

// SetAllowUnhealthyMachine gets a reference to the given bool and assigns it to the AllowUnhealthyMachine field.
func (o *InstanceCreateRequest) SetAllowUnhealthyMachine(v bool) {
	o.AllowUnhealthyMachine = &v
}

func (o InstanceCreateRequest) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o InstanceCreateRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["name"] = o.Name
	if o.Description.IsSet() {
		toSerialize["description"] = o.Description.Get()
	}
	toSerialize["tenantId"] = o.TenantId
	if o.InstanceTypeId.IsSet() {
		toSerialize["instanceTypeId"] = o.InstanceTypeId.Get()
	}
	if o.MachineId.IsSet() {
		toSerialize["machineId"] = o.MachineId.Get()
	}
	toSerialize["vpcId"] = o.VpcId
	if !IsNil(o.SecondaryVpcIds) {
		toSerialize["secondaryVpcIds"] = o.SecondaryVpcIds
	}
	if o.UserData.IsSet() {
		toSerialize["userData"] = o.UserData.Get()
	}
	if o.OperatingSystemId.IsSet() {
		toSerialize["operatingSystemId"] = o.OperatingSystemId.Get()
	}
	if o.NetworkSecurityGroupId.IsSet() {
		toSerialize["networkSecurityGroupId"] = o.NetworkSecurityGroupId.Get()
	}
	if o.IpxeScript.IsSet() {
		toSerialize["ipxeScript"] = o.IpxeScript.Get()
	}
	if !IsNil(o.AlwaysBootWithCustomIpxe) {
		toSerialize["alwaysBootWithCustomIpxe"] = o.AlwaysBootWithCustomIpxe
	}
	if !IsNil(o.PhoneHomeEnabled) {
		toSerialize["phoneHomeEnabled"] = o.PhoneHomeEnabled
	}
	if !IsNil(o.Labels) {
		toSerialize["labels"] = o.Labels
	}
	if !IsNil(o.Interfaces) {
		toSerialize["interfaces"] = o.Interfaces
	}
	if !IsNil(o.AutoNetwork) {
		toSerialize["autoNetwork"] = o.AutoNetwork
	}
	if !IsNil(o.InfinibandInterfaces) {
		toSerialize["infinibandInterfaces"] = o.InfinibandInterfaces
	}
	if !IsNil(o.DpuExtensionServiceDeployments) {
		toSerialize["dpuExtensionServiceDeployments"] = o.DpuExtensionServiceDeployments
	}
	if !IsNil(o.NvLinkInterfaces) {
		toSerialize["nvLinkInterfaces"] = o.NvLinkInterfaces
	}
	if !IsNil(o.SshKeyGroupIds) {
		toSerialize["sshKeyGroupIds"] = o.SshKeyGroupIds
	}
	if !IsNil(o.AllowUnhealthyMachine) {
		toSerialize["allowUnhealthyMachine"] = o.AllowUnhealthyMachine
	}
	return toSerialize, nil
}

func (o *InstanceCreateRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"name",
		"tenantId",
		"vpcId",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if value, exists := allProperties[requiredProperty]; !exists || value == nil {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varInstanceCreateRequest := _InstanceCreateRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varInstanceCreateRequest)

	if err != nil {
		return err
	}

	*o = InstanceCreateRequest(varInstanceCreateRequest)

	return err
}

type NullableInstanceCreateRequest struct {
	value *InstanceCreateRequest
	isSet bool
}

func (v NullableInstanceCreateRequest) Get() *InstanceCreateRequest {
	return v.value
}

func (v *NullableInstanceCreateRequest) Set(val *InstanceCreateRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableInstanceCreateRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableInstanceCreateRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableInstanceCreateRequest(val *InstanceCreateRequest) *NullableInstanceCreateRequest {
	return &NullableInstanceCreateRequest{value: val, isSet: true}
}

func (v NullableInstanceCreateRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableInstanceCreateRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
